var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.arrayIteratorImpl=function(a){var p=0;return function(){return p<a.length?{done:!1,value:a[p++]}:{done:!0}}};$jscomp.arrayIterator=function(a){return{next:$jscomp.arrayIteratorImpl(a)}};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,p,t){a!=Array.prototype&&a!=Object.prototype&&(a[p]=t.value)};$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);$jscomp.SYMBOL_PREFIX="jscomp_symbol_";$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};
$jscomp.SymbolClass=function(a,p){this.$jscomp$symbol$id_=a;$jscomp.defineProperty(this,"description",{configurable:!0,writable:!0,value:p})};$jscomp.SymbolClass.prototype.toString=function(){return this.$jscomp$symbol$id_};$jscomp.Symbol=function(){function a(t){if(this instanceof a)throw new TypeError("Symbol is not a constructor");return new $jscomp.SymbolClass($jscomp.SYMBOL_PREFIX+(t||"")+"_"+p++,t)}var p=0;return a}();
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var a=$jscomp.global.Symbol.iterator;a||(a=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("Symbol.iterator"));"function"!=typeof Array.prototype[a]&&$jscomp.defineProperty(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return $jscomp.iteratorPrototype($jscomp.arrayIteratorImpl(this))}});$jscomp.initSymbolIterator=function(){}};
$jscomp.initSymbolAsyncIterator=function(){$jscomp.initSymbol();var a=$jscomp.global.Symbol.asyncIterator;a||(a=$jscomp.global.Symbol.asyncIterator=$jscomp.global.Symbol("Symbol.asyncIterator"));$jscomp.initSymbolAsyncIterator=function(){}};$jscomp.iteratorPrototype=function(a){$jscomp.initSymbolIterator();a={next:a};a[$jscomp.global.Symbol.iterator]=function(){return this};return a};
$jscomp.iteratorFromArray=function(a,p){$jscomp.initSymbolIterator();a instanceof String&&(a+="");var t=0,q={next:function(){if(t<a.length){var A=t++;return{value:p(A,a[A]),done:!1}}q.next=function(){return{done:!0,value:void 0}};return q.next()}};q[Symbol.iterator]=function(){return q};return q};
$jscomp.polyfill=function(a,p,t,q){if(p){t=$jscomp.global;a=a.split(".");for(q=0;q<a.length-1;q++){var A=a[q];A in t||(t[A]={});t=t[A]}a=a[a.length-1];q=t[a];p=p(q);p!=q&&null!=p&&$jscomp.defineProperty(t,a,{configurable:!0,writable:!0,value:p})}};$jscomp.polyfill("Array.prototype.keys",function(a){return a?a:function(){return $jscomp.iteratorFromArray(this,function(a){return a})}},"es6","es3");
(function(a){function p(a){try{var n={};Object.keys(a).filter(function(a){return-1==["domain","test","version","schemaVersion"].indexOf(a)}).forEach(function(b){var h=a[b]||{},w=[];Object.keys(h).forEach(function(a){h[a].forEach(function(b){b.type=a;w.push(b)})});var d=t(w,"denial"===b||"fullPage"===b||"error"===b?"node":"text");d[0]&&(n[b]="string"===typeof d[0]||"number"===typeof d[0]?d[0]:!!d[0])})}catch(b){console&&console.debug&&console.debug("While calculating detector values",b)}return n}function t(a,
n,b){function h(b,f,d){if("node"===f)return b;if("text"===f)return b.map(function(b){var f=a.field||a.attribute,c=b;f?(f&&f.split(".")).forEach(function(a){c=c[a]}):c=b.text||b.innerText||b.textContent;return d?p(d,c):c})}function p(a,b){if(2<a.length){var f=new RegExp(a[0],a[1]);var d=a[2]}else f=new RegExp(a[0]),d=a[1];if(d){var c=f.exec(b),n=/^\$([0-9]+)$/.exec(d);if(c)return n[1]?(f=parseInt(n[1]),c[f]):b.replace(f,d)}else return console.warn("Sed without substitution",a),null}b=b||window.location.href;
if(Array.isArray(a))return a.map(function(a){var f=t(a,n,b);f&&Array.isArray(f)&&a.exclude&&(f=f.filter(function(b){return-1===a.exclude.indexOf(b)}));return f}).reduce(function(a,b){null!=b&&(Array.isArray(b)?b.forEach(function(b){null!=b&&a.push(b)}):a.push(b));return a},[]);if(!a)return null;b=b&&decodeURIComponent(b);var d=a.type,f=a.value,c=a.sed;"string"===typeof a&&(d="css",f=a);if("constant"===d)return[f];if("css"===d||"jquery"===d){n=n||(c?"text":"node");if(f){var w;"css"===d?w=document.querySelectorAll(f):
"jquery"===d&&window.$&&(w=window.$(f));d=Array.prototype.slice.call(w);return h(d,n,c)}throw"CSS selector value nto specified"+JSON.stringify(a);}if("url"===d){if(n&&"text"!==n)throw"URL selectors can only return text";n="text";d=b?b:decodeURIComponent(window.location.pathname);c&&(d=p(c,d));return[d]}if("xpath"===d){n=n||(c?"text":"node");d=q(f);if("string"===typeof d)return c?[p(c,d)]:[d];if(Array.isArray(d))return h(d,n,c)}else{if("meta"===d)return n=n||"text",c=document.getElementsByTagName("meta"),
c=_.filter(c,function(a){return a.property===f||a.name===f}),_.map(c,function(a){return a.content});throw"Cannot evaluate type:"+d;}}function q(a,c){c=c||document;if(document.evaluate){var b=document.evaluate(a,c,null,0,null);if(0<b.resultType&&4>b.resultType){var h=null;2===b.resultType?h=b.stringValue:3===b.resultType?h=""+b.booleanValue:1===b.resultType&&(h=""+b.numberValue);return h}if(4<=b.resultType){h=null;if(4===b.resultType||5===b.resultType){h=[];for(var n;null!=(n=b.iterateNext());)h.push(n)}else if(8===
b.resultType||9===b.resultType)h=[b.singleNodeValue];else if(6===b.resultType||7===b.resultType)h=[b.snapshotItem()];return h}}else return[]}function A(a,c){var b=document.createElement("script");b.src=a;b.type="text/javascript";b.async=!0;if(c)for(var h in c)if(null!=h)if(b.dataset)b.dataset[h]=c[h];else{var n=c[h],d=h.replace(/[A-Z]/g,function(a){return"-"+a[0].toLowerCase()});b.setAttribute("data-"+d,n)}(h=document.getElementsByTagName("script"))&&0<h.length?h[0].parentNode.insertBefore(b,h[0]):
document.head.appendChild(b);return b}function R(a){return(Math.random().toString(36)+"00000000000000000").slice(2,a+2)}function F(c,n,b){function h(){console.log("Piwik is not available")}if(a.Hermes)return a.Hermes;var q={userRHKey:c,install:F,config:function(b){function d(){if(document.hidden){N=new Date;var a={activePageDuration:N.getTime()-O.getTime(),activeElementHref:document.activeElement&&document.activeElement.href};r(x.INACTIVE,a)}else O=new Date,a={inactivePageDuration:O.getTime()-N.getTime(),
activeElementHref:document.activeElement&&document.activeElement.href},r(x.ACTIVE,a)}function f(){if(""===B(G+x.CLOSE)){w(G+x.CLOSE,!0,1);var a={openPageDuration:(new Date).getTime()-Q,activeElementHref:document.activeElement&&document.activeElement.href};r(x.CLOSE,a)}}function q(a){try{var b=a&&a.sendPageSrc,c=a.evalPage&&a.detectors;try{var d=c&&p(a.detectors)||{}}catch(S){d={}}""===B(G+x.OPEN)&&w(G+x.OPEN,!0,1);r(x.OPEN,d,b)}catch(S){r(x.ERROR,{error:"3."+S.message},!1)}}function m(a,b){function c(){if(!h){h=
!0;for(var a=0;a<g.length;a++)g[a].fn.call(b,g[a].ctx);g=[]}}function e(){"complete"===document.readyState&&c()}b.addEventListener?b.addEventListener("beforeunload",f):b.onbeforeunload=f;document.addEventListener&&document.addEventListener("visibilitychange",d);b=b||b;var g=[],h=!1,n=!1;b[a||"hermesDocReady"]=function(a,d){h?setTimeout(function(){a(d)},1):(g.push({fn:a,ctx:d}),"complete"===document.readyState||!document.attachEvent&&"interactive"===document.readyState?setTimeout(c,1):n||(document.addEventListener?
(document.addEventListener("DOMContentLoaded",c,!1),b.addEventListener("load",c,!1)):(document.attachEvent("onreadystatechange",e),b.attachEvent("onload",c)),n=!0))}}function z(){for(var a=document.getElementsByTagName("script"),b,c=0;c<a.length;c++){var d=a.item(c);if(d.src&&-1!=d.src.indexOf("CaptureData")){b=d;break}}b&&b.parentNode&&b.parentNode.removeChild(b)}function r(d,e,f){function h(){if(a.XMLHttpRequest){var b=new XMLHttpRequest;if("withCredentials"in b)b.withCredentials=!0;else if("undefined"!=
typeof XDomainRequest)b=new XDomainRequest;else return}else b=new ActiveXObject("Microsoft.XMLHTTP");return b}var p=e&&e.id,q=p&&0<(""+p.trim()).length;q&&(e.id="####");b.sendGet&&z();var k="NA";try{k=e.error||""}catch(E){}var m=null;try{var l=B("detector");if(l&&(l=JSON.parse(l),l.denial&&l.denial.xpath)){var r=t(l.denial.xpath);r&&0<r.length&&(m=!0)}}catch(E){}b.sendGet&&A(n+"/api/CaptureData?userRHKey="+encodeURIComponent(c)+"&actionType="+d+"&cookie="+encodeURIComponent(H)+"&scookie="+encodeURIComponent(I)+
"&eMsg="+encodeURIComponent(k)+(f?"&reqDet=true":"")+(m?"&den=true":""));if(b.sendPost){l={};r="";m=h();try{m.onload=function(b){function g(a,b,e,f,k){f=f||document.documentElement.innerHTML;if(q)try{var l=p.replace(/[.*+?^${}()|[\]\\]/g,"\\$&");f=f.replace(new RegExp(l,"g"),"####")}catch(W){console&&console.debug&&console.debug(W)}e=e||0;b=b||4E5;k=k||Math.ceil(f.length/b);l=f.slice(e*b,Math.min((e+1)*b,f.length));l="userRHKey="+encodeURIComponent(c)+"&hrmEvtId="+a+"&maxLength="+b+"&chunkNo="+e+
"&numOfChunks="+k+"&pageSource="+encodeURIComponent(l);var m=h();m.onload=function(c){e<k-1&&g(a,b,e+1,f,k)};m.open("POST",n+"/api/CaptureData?userRHKey="+encodeURIComponent(c)+"&actionType="+d+"&cookie="+encodeURIComponent(H)+"&scookie="+encodeURIComponent(I),!0);"withCredentials"in m&&m.setRequestHeader("Content-Type","application/x-www-form-urlencoded; charset=UTF-8");m.send(l)}b&&b.target&&(b.target.response&&(b=JSON.parse(b.target.response),b.evtId&&"open"==d&&(a.Hermes.hrmEvtId=b.evtId,"deferred"===
f&&g(b.evtId,4E5))),v&&v.dataset&&v.dataset.chromeExtId&&(a.postMessage({msg:"R!",actionType:d,data:e},"*"),chrome.runtime.sendMessage(v.dataset.chromeExtId,{msg:"R"},function(a){})))}}catch(E){r=r+"1."+E.message+"\n"}try{var w=null,x=null,P=null,D=B(J),V=B(K);g&&(g.memory&&(w={jsHeapSizeLimit:g.memory.jsHeapSizeLimit,totalJSHeapSize:g.memory.totalJSHeapSize,usedJSHeapSize:g.memory.usedJSHeapSize}),g.timing&&(x={connectEnd:g.timing.connectEnd,connectStart:g.timing.connectStart,domComplete:g.timing.domComplete,
domContentLoadedEventEnd:g.timing.domContentLoadedEventEnd,domContentLoadedEventStart:g.timing.domContentLoadedEventStart,domInteractive:g.timing.domInteractive,domLoading:g.timing.domLoading,domainLookupEnd:g.timing.domainLookupEnd,domainLookupStart:g.timing.domainLookupStart,fetchStart:g.timing.fetchStart,loadEventEnd:g.timing.loadEventEnd,loadEventStart:g.timing.loadEventStart,navigationStart:g.timing.navigationStart,redirectEnd:g.timing.redirectEnd,redirectStart:g.timing.redirectStart,requestStart:g.timing.requestStart,
responseEnd:g.timing.responseEnd,responseStart:g.timing.responseStart,secureConnectionStart:g.timing.secureConnectionStart,unloadEventEnd:g.timing.unloadEventEnd,unloadEventStart:g.timing.unloadEventStart}),g.navigation&&(P={redirectCount:g.navigation.redirectCount,type:g.navigation.type}),l.performance={memory:w,navigation:P,timing:x});l.actionType=d;l.userCookie=D;l.userSessionCookie=V;l.userDate=new Date;l.currentPath=G;l.browserName=y;l.fullVersion=u;l.majorVersion=L;l.screenWidth=X;l.screenHeight=
Y;l.language=Z;l.osName=aa;l.appName=ba;l.userAgent=ca;l.referrer=da;l.data=e;l.refEvtId=a.Hermes.hrmEvtId}catch(E){r=r+"2."+E.message+"\n"}m.open("POST",n+"/api/CaptureData?userRHKey="+encodeURIComponent(c)+"&actionType="+d+"&cookie="+encodeURIComponent(H)+"&scookie="+encodeURIComponent(I)+"&reqDet=2&eMsg="+encodeURIComponent(k),!0);"withCredentials"in m&&m.setRequestHeader("Content-Type","application/x-www-form-urlencoded; charset=UTF-8");0<r.length&&(l.data={error:r});if(m&&a.JSON){k="userRHKey="+
encodeURIComponent(c)+"&data="+encodeURIComponent(JSON.stringify(l));if(f&&!0===f){D=void 0;if(f){D=document.documentElement.innerHTML;if(q)try{var C=p.replace(/[.*+?^${}()|[\]\\]/g,"\\$&");D=D.replace(new RegExp(C,"g"),"####")}catch(E){console&&console.debug&&console.debug(E)}D=f?encodeURIComponent(D):null}k=k+"&pageSource="+D}else"deferred"===f&&(k=k+"&pageSource="+encodeURIComponent("\x3c!-- Deferred --\x3e"));m.send(k)}}}function w(a,b,c,d){if(T===c)var e="expires=Fri, 31 Dec 9999 23:59:59 GMT";
else c&&(e=new Date,e.setTime(e.getTime()+6E4*c),e="expires="+e.toUTCString());document.cookie=a+"="+b+"; "+e+(d?"; path="+d:"")}function B(a){a+="=";for(var b=document.cookie.split(";"),c=0;c<b.length;c++){for(var d=b[c];" "==d.charAt(0);)d=d.substring(1);if(0===d.indexOf(a))return d.substring(a.length,d.length)}return""}var e=a.sessionStorage&&a.sessionStorage.getItem("hermes_config")||a.localStorage&&a.localStorage.getItem("hermes_config");e&&(e=JSON.parse(e));for(var C in e)b[C]=e[C];b.captureBase&&
(n=b.captureBase);var F=null==b.sendBodyLevel?!0:3<=b.sendBodyLevel?!0:2===b.sendBodyLevel?"deferred":!1;var U=b.detectors;e=null;a.location.search&&0<a.location.search.indexOf("rmqSelect=")&&(e=a.location.search.indexOf("rmqSelect=")+10,C=a.location.search.indexOf("&",e),e=-1!=C?a.location.search.substring(e,C):a.location.search.substring(e),e=decodeURIComponent(e),console.log("Picking rmqSelect:"+e));if(e&&("stage"===e?(b.installRemarq="https://rmrqstage.redlink.com/groveMain.bundle.js",b.rmqApiBase=
"https://rmrqstage.redlink.com/api"):"beta"===e?(b.installRemarq="https://rmrqbeta.redlink.com/groveMain.bundle.js",b.rmqApiBase="https://rmrqbeta.redlink.com/api"):(b.installRemarq="https://"+e+"/groveMain.bundle.js",b.rmqApiBase="https://"+e+"/api"),a.sessionStorage))try{a.sessionStorage.setItem("hermes_config",JSON.stringify(b))}catch(P){}if(b.installRemarq)e=A(b.installRemarq,{apiBase:b.rmqApiBase}),e.onload=function(c){b.sendPiwik&&h();if(b.sendPost||b.sendGet)m("hermesDocReady",a),hermesDocReady(q,
{evalPage:!0,detectors:U,sendPageSrc:F})},e.onerror=e.onload;else if(b.sendPiwik&&h(),b.sendPost||b.sendGet)m("hermesDocReady",a),hermesDocReady(q,{evalPage:!0,detectors:U,sendPageSrc:F});var J="hrmTracker",K="hrmTracker_S",T="forever",H=B(J),I=B(K);H||(w(J,R(10),T,"/"),H=B(J));I||(w(K,R(10),null,"/"),I=B(K));var x={OPEN:"open",CLOSE:"close",ACTIVE:"active",INACTIVE:"inactive",ERROR:"error"},O=new Date,N=new Date,G=a.location.href,g=a.performance,Q=g&&g.timing&&g.timing.requestStart||(new Date).getTime();
e=navigator.userAgent;var y=navigator.appName,u=""+parseFloat(navigator.appVersion),L=parseInt(navigator.appVersion,10),k,M;var X=a.screen?screen.width:0;var Y=a.screen?screen.height:0;var Z=navigator.language||navigator.userLanguage||"(Not supported)",aa=-1!=navigator.appVersion.indexOf("Win")?"Windows":-1!=navigator.appVersion.indexOf("Mac")?"MacOS":-1!=navigator.appVersion.indexOf("X11")?"UNIX":-1!=navigator.appVersion.indexOf("Linux")?"Linux":-1!=navigator.appVersion.indexOf("Android")?"Android":
-1!=navigator.appVersion.indexOf("Iphone")?"Iphone":"Unknown OS",ba=navigator.appName,ca=navigator.userAgent,da=document.referrer;-1!=(k=e.indexOf("OPR/"))?(y="Opera",u=e.substring(k+4)):-1!=(k=e.indexOf("Opera"))?(y="Opera",u=e.substring(k+6),-1!=(k=e.indexOf("Version"))&&(u=e.substring(k+8))):-1!=(k=e.indexOf("MSIE"))?(y="Microsoft Internet Explorer",u=e.substring(k+5)):-1!=(k=e.indexOf("Chrome"))?(y="Chrome",u=e.substring(k+7)):-1!=(k=e.indexOf("Safari"))?(y="Safari",u=e.substring(k+7),-1!=(k=
e.indexOf("Version"))&&(u=e.substring(k+8))):-1!=(k=e.indexOf("Firefox"))?(y="Firefox",u=e.substring(k+8)):(C=e.lastIndexOf(" ")+1)<(k=e.lastIndexOf("/"))&&(y=e.substring(C,k),u=e.substring(k+1),y.toLowerCase()==y.toUpperCase()&&(y=navigator._appName));-1!=(M=u.indexOf(";"))&&(u=u.substring(0,M));-1!=(M=u.indexOf(" "))&&(u=u.substring(0,M));L=parseInt(""+u,10);isNaN(L)&&(u=""+parseFloat(navigator.appVersion),L=parseInt(navigator.appVersion,10))},installDetector:function(a){var b=_getCookie("detector"),
c=JSON.stringify(a);b!==c&&(_setCookie("detector",JSON.stringify(a),null,"/"),q.detector=a)}},d=document.domain;d&&0==d.indexOf("www.")&&(d=d.substr(4));d=encodeURIComponent(d);A(b+"/api/config?userRHKey="+c+"&domain="+d);return q}for(var m=document.getElementsByTagName("script"),v,c=0;c<m.length;c++){var r=m.item(c);if(r.src&&-1!=r.src.indexOf("hermes")){v=r;break}}if(v){c=v.src.indexOf("?");var z=v.src.indexOf("/hermes.js");v.src.substring(0,z);z={};if(-1!=c)for(m=v.src.substring(c+1).split("&"),
c=0;c<m.length;c++){r=m[c].substring(0,m[c].indexOf("="));var Q=m[c].substring(m[c].indexOf("=")+1);z[r]=Q}(z=z.userRHKey)||(z=v.data&&v.data.userRHKey);z||(z="None")}else console&&console.error&&console.error("Cannot find script tag. Is script included as hermes.js");c="//hermes.redlink.com";v.dataset&&v.dataset.captureBase&&(c=v.dataset.captureBase);(m=window.sessionStorage&&window.sessionStorage.hermes_captureBase||window.localStorage&&window.localStorage.hermes_captureBase)&&(c=m);m=c;(r=window.sessionStorage&&
window.sessionStorage.hermes_configBase||window.localStorage&&window.localStorage.hermes_configBase)&&(m=r);a.Hermes=F(z,c,m)})(window);
