var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.arrayIteratorImpl=function(a){var p=0;return function(){return p<a.length?{done:!1,value:a[p++]}:{done:!0}}};$jscomp.arrayIterator=function(a){return{next:$jscomp.arrayIteratorImpl(a)}};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,p,u){a!=Array.prototype&&a!=Object.prototype&&(a[p]=u.value)};$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);$jscomp.SYMBOL_PREFIX="jscomp_symbol_";$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};
$jscomp.Symbol=function(){var a=0;return function(p){return $jscomp.SYMBOL_PREFIX+(p||"")+a++}}();$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var a=$jscomp.global.Symbol.iterator;a||(a=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("iterator"));"function"!=typeof Array.prototype[a]&&$jscomp.defineProperty(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return $jscomp.iteratorPrototype($jscomp.arrayIteratorImpl(this))}});$jscomp.initSymbolIterator=function(){}};
$jscomp.initSymbolAsyncIterator=function(){$jscomp.initSymbol();var a=$jscomp.global.Symbol.asyncIterator;a||(a=$jscomp.global.Symbol.asyncIterator=$jscomp.global.Symbol("asyncIterator"));$jscomp.initSymbolAsyncIterator=function(){}};$jscomp.iteratorPrototype=function(a){$jscomp.initSymbolIterator();a={next:a};a[$jscomp.global.Symbol.iterator]=function(){return this};return a};
$jscomp.iteratorFromArray=function(a,p){$jscomp.initSymbolIterator();a instanceof String&&(a+="");var u=0,l={next:function(){if(u<a.length){var B=u++;return{value:p(B,a[B]),done:!1}}l.next=function(){return{done:!0,value:void 0}};return l.next()}};l[Symbol.iterator]=function(){return l};return l};
$jscomp.polyfill=function(a,p,u,l){if(p){u=$jscomp.global;a=a.split(".");for(l=0;l<a.length-1;l++){var B=a[l];B in u||(u[B]={});u=u[B]}a=a[a.length-1];l=u[a];p=p(l);p!=l&&null!=p&&$jscomp.defineProperty(u,a,{configurable:!0,writable:!0,value:p})}};$jscomp.polyfill("Array.prototype.keys",function(a){return a?a:function(){return $jscomp.iteratorFromArray(this,function(a){return a})}},"es6","es3");
(function(a){function p(a){try{var e={};Object.keys(a).filter(function(a){return-1==["domain","test","version","schemaVersion"].indexOf(a)}).forEach(function(c){var g=a[c]||{},n=[];Object.keys(g).forEach(function(a){g[a].forEach(function(b){b.type=a;n.push(b)})});var b=u(n,"denial"===c||"fullPage"===c||"error"===c?"node":"text");b[0]&&(e[c]="string"===typeof b[0]||"number"===typeof b[0]?b[0]:!!b[0])})}catch(c){console&&console.debug&&console.debug("While calculating detector values",c)}return e}function u(a,
e,c){function g(b,c,g){if("node"===c)return b;if("text"===c)return b.map(function(b){var c=a.field||a.attribute,e=b;c?(c&&c.split(".")).forEach(function(a){e=e[a]}):e=b.text||b.innerText||b.textContent;return g?p(g,e):e})}function p(a,b){if(2<a.length){var c=new RegExp(a[0],a[1]);var e=a[2]}else c=new RegExp(a[0]),e=a[1];if(e){var g=c.exec(b),n=/^\$([0-9]+)$/.exec(e);if(g)return n[1]?(c=parseInt(n[1]),g[c]):b.replace(c,e)}else return console.warn("Sed without substitution",a),null}c=c||window.location.href;
if(Array.isArray(a))return a.map(function(a){var b=u(a,e,c);b&&Array.isArray(b)&&a.exclude&&(b=b.filter(function(b){return-1===a.exclude.indexOf(b)}));return b}).reduce(function(a,b){null!=b&&(Array.isArray(b)?b.forEach(function(b){null!=b&&a.push(b)}):a.push(b));return a},[]);if(!a)return null;c=c&&decodeURIComponent(c);var b=a.type,n=a.value,v=a.sed;"string"===typeof a&&(b="css",n=a);if("constant"===b)return[n];if("css"===b||"jquery"===b){e=e||(v?"text":"node");if(n){var h;"css"===b?h=document.querySelectorAll(n):
"jquery"===b&&window.$&&(h=window.$(n));b=Array.prototype.slice.call(h);return g(b,e,v)}throw"CSS selector value nto specified"+JSON.stringify(a);}if("url"===b){if(e&&"text"!==e)throw"URL selectors can only return text";e="text";b=c?c:decodeURIComponent(window.location.pathname);v&&(b=p(v,b));return[b]}if("xpath"===b){e=e||(v?"text":"node");b=l(n);if("string"===typeof b)return v?[p(v,b)]:[b];if(Array.isArray(b))return g(b,e,v)}else{if("meta"===b)return e=e||"text",v=document.getElementsByTagName("meta"),
v=_.filter(v,function(a){return a.property===n||a.name===n}),_.map(v,function(a){return a.content});throw"Cannot evaluate type:"+b;}}function l(a,e){e=e||document;if(document.evaluate){var c=document.evaluate(a,e,null,0,null);if(0<c.resultType&&4>c.resultType){var g=null;2===c.resultType?g=c.stringValue:3===c.resultType?g=""+c.booleanValue:1===c.resultType&&(g=""+c.numberValue);return g}if(4<=c.resultType){g=null;if(4===c.resultType||5===c.resultType){g=[];for(var n;null!=(n=c.iterateNext());)g.push(n)}else if(8===
c.resultType||9===c.resultType)g=[c.singleNodeValue];else if(6===c.resultType||7===c.resultType)g=[c.snapshotItem()];return g}}else return[]}function B(a,e){var c=document.createElement("script");c.src=a;c.type="text/javascript";c.async=!0;if(e)for(var g in e)if(null!=g)if(c.dataset)c.dataset[g]=e[g];else{var n=e[g],b=g.replace(/[A-Z]/g,function(a){return"-"+a[0].toLowerCase()});c.setAttribute("data-"+b,n)}(g=document.getElementsByTagName("script"))&&0<g.length?g[0].parentNode.insertBefore(c,g[0]):
document.head.appendChild(c);return c}function Q(a){return(Math.random().toString(36)+"00000000000000000").slice(2,a+2)}function F(n,e){function c(){console.log("Piwik is not available")}if(a.Hermes)return a.Hermes;var g={userRHKey:n,install:F,config:function(b){function e(){if(document.hidden){N=new Date;var a={activePageDuration:N.getTime()-O.getTime(),activeElementHref:document.activeElement&&document.activeElement.href};q(r.INACTIVE,a)}else O=new Date,a={inactivePageDuration:O.getTime()-N.getTime(),
activeElementHref:document.activeElement&&document.activeElement.href},q(r.ACTIVE,a)}function g(){if(""===D(G+r.CLOSE)){y(G+r.CLOSE,!0,1);var a={openPageDuration:(new Date).getTime()-P,activeElementHref:document.activeElement&&document.activeElement.href};q(r.CLOSE,a)}}function h(a){try{var b=a&&a.sendPageSrc,c=a.evalPage&&a.detectors;try{var d=c&&p(a.detectors)||{}}catch(S){d={}}""===D(G+r.OPEN)&&y(G+r.OPEN,!0,1);q(r.OPEN,d,b)}catch(S){q(r.ERROR,{error:"3."+S.message},!1)}}function l(a,b){function c(){if(!h){h=
!0;for(var a=0;a<f.length;a++)f[a].fn.call(b,f[a].ctx);f=[]}}function d(){"complete"===document.readyState&&c()}b.addEventListener?b.addEventListener("beforeunload",g):b.onbeforeunload=g;document.addEventListener&&document.addEventListener("visibilitychange",e);b=b||b;var f=[],h=!1,n=!1;b[a||"hermesDocReady"]=function(a,e){h?setTimeout(function(){a(e)},1):(f.push({fn:a,ctx:e}),"complete"===document.readyState||!document.attachEvent&&"interactive"===document.readyState?setTimeout(c,1):n||(document.addEventListener?
(document.addEventListener("DOMContentLoaded",c,!1),b.addEventListener("load",c,!1)):(document.attachEvent("onreadystatechange",d),b.attachEvent("onload",c)),n=!0))}}function z(){for(var a=document.getElementsByTagName("script"),b,c=0;c<a.length;c++){var d=a.item(c);if(d.src&&-1!=d.src.indexOf("CaptureData")){b=d;break}}b&&b.parentNode&&b.parentNode.removeChild(b)}function q(c,d,e){function g(){if(a.XMLHttpRequest){var b=new XMLHttpRequest;if("withCredentials"in b)b.withCredentials=!0;else if("undefined"!=
typeof XDomainRequest)b=new XDomainRequest;else return}else b=new ActiveXObject("Microsoft.XMLHTTP");return b}var h=d&&d.id,p=h&&0<(""+h.trim()).length;p&&(d.id="####");b.sendGet&&z();var k="NA";try{k=d.error||""}catch(E){}var l=null;try{var m=D("detector");if(m&&(m=JSON.parse(m),m.denial&&m.denial.xpath)){var q=u(m.denial.xpath);q&&0<q.length&&(l=!0)}}catch(E){}b.sendGet&&B(C+"/api/CaptureData?userRHKey="+encodeURIComponent(n)+"&actionType="+c+"&cookie="+encodeURIComponent(H)+"&scookie="+encodeURIComponent(I)+
"&eMsg="+encodeURIComponent(k)+(e?"&reqDet=true":"")+(l?"&den=true":""));if(b.sendPost){m={};q="";l=g();try{l.onload=function(b){function f(a,b,d,e,k){e=e||document.documentElement.innerHTML;if(p)try{var l=h.replace(/[.*+?^${}()|[\]\\]/g,"\\$&");e=e.replace(new RegExp(l,"g"),"####")}catch(W){console&&console.debug&&console.debug(W)}d=d||0;b=b||4E5;k=k||Math.ceil(e.length/b);l=e.slice(d*b,Math.min((d+1)*b,e.length));l="userRHKey="+encodeURIComponent(n)+"&hrmEvtId="+a+"&maxLength="+b+"&chunkNo="+d+
"&numOfChunks="+k+"&pageSource="+encodeURIComponent(l);var m=g();m.onload=function(c){d<k-1&&f(a,b,d+1,e,k)};m.open("POST",C+"/api/CaptureData?userRHKey="+encodeURIComponent(n)+"&actionType="+c+"&cookie="+encodeURIComponent(H)+"&scookie="+encodeURIComponent(I),!0);"withCredentials"in m&&m.setRequestHeader("Content-Type","application/x-www-form-urlencoded; charset=UTF-8");m.send(l)}b&&b.target&&(b.target.response&&(b=JSON.parse(b.target.response),b.evtId&&"open"==c&&(a.Hermes.hrmEvtId=b.evtId,"deferred"===
e&&f(b.evtId,4E5))),x&&x.dataset&&x.dataset.chromeExtId&&(a.postMessage({msg:"R!",actionType:c,data:d},"*"),chrome.runtime.sendMessage(x.dataset.chromeExtId,{msg:"R"},function(a){})))}}catch(E){q=q+"1."+E.message+"\n"}try{var v=null,w=null,y=null,r=D(J),R=D(K);f&&(f.memory&&(v={jsHeapSizeLimit:f.memory.jsHeapSizeLimit,totalJSHeapSize:f.memory.totalJSHeapSize,usedJSHeapSize:f.memory.usedJSHeapSize}),f.timing&&(w={connectEnd:f.timing.connectEnd,connectStart:f.timing.connectStart,domComplete:f.timing.domComplete,
domContentLoadedEventEnd:f.timing.domContentLoadedEventEnd,domContentLoadedEventStart:f.timing.domContentLoadedEventStart,domInteractive:f.timing.domInteractive,domLoading:f.timing.domLoading,domainLookupEnd:f.timing.domainLookupEnd,domainLookupStart:f.timing.domainLookupStart,fetchStart:f.timing.fetchStart,loadEventEnd:f.timing.loadEventEnd,loadEventStart:f.timing.loadEventStart,navigationStart:f.timing.navigationStart,redirectEnd:f.timing.redirectEnd,redirectStart:f.timing.redirectStart,requestStart:f.timing.requestStart,
responseEnd:f.timing.responseEnd,responseStart:f.timing.responseStart,secureConnectionStart:f.timing.secureConnectionStart,unloadEventEnd:f.timing.unloadEventEnd,unloadEventStart:f.timing.unloadEventStart}),f.navigation&&(y={redirectCount:f.navigation.redirectCount,type:f.navigation.type}),m.performance={memory:v,navigation:y,timing:w});m.actionType=c;m.userCookie=r;m.userSessionCookie=R;m.userDate=new Date;m.currentPath=G;m.browserName=A;m.fullVersion=t;m.majorVersion=L;m.screenWidth=X;m.screenHeight=
Y;m.language=Z;m.osName=aa;m.appName=ba;m.userAgent=ca;m.referrer=da;m.data=d;m.refEvtId=a.Hermes.hrmEvtId}catch(E){q=q+"2."+E.message+"\n"}l.open("POST",C+"/api/CaptureData?userRHKey="+encodeURIComponent(n)+"&actionType="+c+"&cookie="+encodeURIComponent(H)+"&scookie="+encodeURIComponent(I)+"&reqDet=2&eMsg="+encodeURIComponent(k),!0);"withCredentials"in l&&l.setRequestHeader("Content-Type","application/x-www-form-urlencoded; charset=UTF-8");0<q.length&&(m.data={error:q});if(l&&a.JSON){k="userRHKey="+
encodeURIComponent(n)+"&data="+encodeURIComponent(JSON.stringify(m));if(e&&!0===e){r=void 0;if(e){r=document.documentElement.innerHTML;if(p)try{var V=h.replace(/[.*+?^${}()|[\]\\]/g,"\\$&");r=r.replace(new RegExp(V,"g"),"####")}catch(E){console&&console.debug&&console.debug(E)}r=e?encodeURIComponent(r):null}k=k+"&pageSource="+r}else"deferred"===e&&(k=k+"&pageSource="+encodeURIComponent("\x3c!-- Deferred --\x3e"));l.send(k)}}}function y(a,b,c,d){if(T===c)var e="expires=Fri, 31 Dec 9999 23:59:59 GMT";
else c&&(e=new Date,e.setTime(e.getTime()+6E4*c),e="expires="+e.toUTCString());document.cookie=a+"="+b+"; "+e+(d?"; path="+d:"")}function D(a){a+="=";for(var b=document.cookie.split(";"),c=0;c<b.length;c++){for(var d=b[c];" "==d.charAt(0);)d=d.substring(1);if(0===d.indexOf(a))return d.substring(a.length,d.length)}return""}var C=null,w=window.sessionStorage&&window.sessionStorage.hermes_captureBase||window.localStorage&&window.localStorage.hermes_captureBase;w&&(C=w);!C&&x.dataset&&x.dataset.captureBase&&
(C=x.dataset.captureBase);C||(C=b.captureBase);C||(C="//hermes.redlink.com");(w=a.sessionStorage&&a.sessionStorage.getItem("hermes_config")||a.localStorage&&a.localStorage.getItem("hermes_config"))&&(w=JSON.parse(w));for(var d in w)b[d]=w[d];var F=null==b.sendBodyLevel?!0:3<=b.sendBodyLevel?!0:2===b.sendBodyLevel?"deferred":!1;var U=b.detectors;d=null;a.location.search&&0<a.location.search.indexOf("rmqSelect=")&&(d=a.location.search.indexOf("rmqSelect=")+10,w=a.location.search.indexOf("&",d),d=-1!==
w?a.location.search.substring(d,w):a.location.search.substring(d),d=decodeURIComponent(d),console.log("Picking rmqSelect:"+d));if(d&&("stage"===d?(b.installRemarq="https://rmrqstage.redlink.com/groveMain.bundle.js",b.rmqApiBase="https://rmrqstage.redlink.com/api"):"beta"===d?(b.installRemarq="https://rmrqbeta.redlink.com/groveMain.bundle.js",b.rmqApiBase="https://rmrqbeta.redlink.com/api"):(b.installRemarq="https://"+d+"/groveMain.bundle.js",b.rmqApiBase="https://"+d+"/api"),a.sessionStorage))try{a.sessionStorage.setItem("hermes_config",
JSON.stringify(b))}catch(R){}if(b.installRemarq)d=B(b.installRemarq,{apiBase:b.rmqApiBase}),d.onload=function(d){b.sendPiwik&&c();if(b.sendPost||b.sendGet)l("hermesDocReady",a),hermesDocReady(h,{evalPage:!0,detectors:U,sendPageSrc:F})},d.onerror=d.onload;else if(b.sendPiwik&&c(),b.sendPost||b.sendGet)l("hermesDocReady",a),hermesDocReady(h,{evalPage:!0,detectors:U,sendPageSrc:F});var J="hrmTracker",K="hrmTracker_S",T="forever",H=D(J),I=D(K);H||(y(J,Q(10),T,"/"),H=D(J));I||(y(K,Q(10),null,"/"),I=D(K));
var r={OPEN:"open",CLOSE:"close",ACTIVE:"active",INACTIVE:"inactive",ERROR:"error"},O=new Date,N=new Date,G=a.location.href,f=a.performance,P=f&&f.timing&&f.timing.requestStart||(new Date).getTime();d=navigator.userAgent;var A=navigator.appName,t=""+parseFloat(navigator.appVersion),L=parseInt(navigator.appVersion,10),k,M;var X=a.screen?screen.width:0;var Y=a.screen?screen.height:0;var Z=navigator.language||navigator.userLanguage||"(Not supported)",aa=-1!=navigator.appVersion.indexOf("Win")?"Windows":
-1!=navigator.appVersion.indexOf("Mac")?"MacOS":-1!=navigator.appVersion.indexOf("X11")?"UNIX":-1!=navigator.appVersion.indexOf("Linux")?"Linux":-1!=navigator.appVersion.indexOf("Android")?"Android":-1!=navigator.appVersion.indexOf("Iphone")?"Iphone":"Unknown OS",ba=navigator.appName,ca=navigator.userAgent,da=document.referrer;-1!=(k=d.indexOf("OPR/"))?(A="Opera",t=d.substring(k+4)):-1!=(k=d.indexOf("Opera"))?(A="Opera",t=d.substring(k+6),-1!=(k=d.indexOf("Version"))&&(t=d.substring(k+8))):-1!=(k=
d.indexOf("MSIE"))?(A="Microsoft Internet Explorer",t=d.substring(k+5)):-1!=(k=d.indexOf("Chrome"))?(A="Chrome",t=d.substring(k+7)):-1!=(k=d.indexOf("Safari"))?(A="Safari",t=d.substring(k+7),-1!=(k=d.indexOf("Version"))&&(t=d.substring(k+8))):-1!=(k=d.indexOf("Firefox"))?(A="Firefox",t=d.substring(k+8)):(w=d.lastIndexOf(" ")+1)<(k=d.lastIndexOf("/"))&&(A=d.substring(w,k),t=d.substring(k+1),A.toLowerCase()==A.toUpperCase()&&(A=navigator._appName));-1!=(M=t.indexOf(";"))&&(t=t.substring(0,M));-1!=(M=
t.indexOf(" "))&&(t=t.substring(0,M));L=parseInt(""+t,10);isNaN(L)&&(t=""+parseFloat(navigator.appVersion),L=parseInt(navigator.appVersion,10))},installDetector:function(a){var b=_getCookie("detector"),c=JSON.stringify(a);b!==c&&(_setCookie("detector",JSON.stringify(a),null,"/"),g.detector=a)}},h=document.domain;h&&0==h.indexOf("www.")&&(h=h.substr(4));h=encodeURIComponent(h);B(e+"/api/config?userRHKey="+n+"&domain="+h);return g}for(var z=document.getElementsByTagName("script"),x,h=0;h<z.length;h++){var y=
z.item(h);if(y.src&&-1!=y.src.indexOf("hermes")){x=y;break}}if(x){h=x.src.indexOf("?");var q=x.src.indexOf("/hermes.js");x.src.substring(0,q);q={};if(-1!=h)for(z=x.src.substring(h+1).split("&"),h=0;h<z.length;h++){y=z[h].substring(0,z[h].indexOf("="));var P=z[h].substring(z[h].indexOf("=")+1);q[y]=P}(q=q.userRHKey)||(q=x.data&&x.data.userRHKey);q||(q="None")}else console&&console.error&&console.error("Cannot find script tag. Is script included as hermes.js");h="//hermes.redlink.com";(z=window.sessionStorage&&
window.sessionStorage.hermes_configBase||window.localStorage&&window.localStorage.hermes_configBase)&&(h=z);a.Hermes=F(q,h)})(window);
