
// Copyright 2012 Google Inc. All rights reserved.
(function(){

var data = {
"resource": {
  "version":"1",
  
  "macros":[],
  "tags":[],
  "predicates":[],
  "rules":[]
},
"runtime":[
[],[]
]



};
var ba,ca=this||self,da=/^[\w+/_-]+[=]{0,2}$/,fa=null;var ha=function(){},ia=function(a){return"function"==typeof a},ja=function(a){return"string"==typeof a},ka=function(a){return"number"==typeof a&&!isNaN(a)},la=function(a){return"[object Array]"==Object.prototype.toString.call(Object(a))},ma=function(a,b){if(Array.prototype.indexOf){var c=a.indexOf(b);return"number"==typeof c?c:-1}for(var d=0;d<a.length;d++)if(a[d]===b)return d;return-1},na=function(a,b){if(a&&la(a))for(var c=0;c<a.length;c++)if(a[c]&&b(a[c]))return a[c]},oa=function(a,b){if(!ka(a)||
!ka(b)||a>b)a=0,b=2147483647;return Math.floor(Math.random()*(b-a+1)+a)},ra=function(a,b){for(var c=new qa,d=0;d<a.length;d++)c.set(a[d],!0);for(var e=0;e<b.length;e++)if(c.get(b[e]))return!0;return!1},sa=function(a,b){for(var c in a)Object.prototype.hasOwnProperty.call(a,c)&&b(c,a[c])},ta=function(a){return Math.round(Number(a))||0},ua=function(a){return"false"==String(a).toLowerCase()?!1:!!a},va=function(a){var b=[];if(la(a))for(var c=0;c<a.length;c++)b.push(String(a[c]));return b},wa=function(a){return a?
a.replace(/^\s+|\s+$/g,""):""},xa=function(){return(new Date).getTime()},qa=function(){this.prefix="gtm.";this.values={}};qa.prototype.set=function(a,b){this.values[this.prefix+a]=b};qa.prototype.get=function(a){return this.values[this.prefix+a]};qa.prototype.contains=function(a){return void 0!==this.get(a)};
var ya=function(a,b,c){return a&&a.hasOwnProperty(b)?a[b]:c},za=function(a){var b=!1;return function(){if(!b)try{a()}catch(c){}b=!0}},Aa=function(a,b){for(var c in b)b.hasOwnProperty(c)&&(a[c]=b[c])},Ca=function(a){for(var b in a)if(a.hasOwnProperty(b))return!0;return!1},Da=function(a,b){for(var c=[],d=0;d<a.length;d++)c.push(a[d]),c.push.apply(c,b[a[d]]||[]);return c};/*
 jQuery v1.9.1 (c) 2005, 2012 jQuery Foundation, Inc. jquery.org/license. */
var Ea=/\[object (Boolean|Number|String|Function|Array|Date|RegExp)\]/,Ga=function(a){if(null==a)return String(a);var b=Ea.exec(Object.prototype.toString.call(Object(a)));return b?b[1].toLowerCase():"object"},Ha=function(a,b){return Object.prototype.hasOwnProperty.call(Object(a),b)},Ia=function(a){if(!a||"object"!=Ga(a)||a.nodeType||a==a.window)return!1;try{if(a.constructor&&!Ha(a,"constructor")&&!Ha(a.constructor.prototype,"isPrototypeOf"))return!1}catch(c){return!1}for(var b in a);return void 0===
b||Ha(a,b)},f=function(a,b){var c=b||("array"==Ga(a)?[]:{}),d;for(d in a)if(Ha(a,d)){var e=a[d];"array"==Ga(e)?("array"!=Ga(c[d])&&(c[d]=[]),c[d]=f(e,c[d])):Ia(e)?(Ia(c[d])||(c[d]={}),c[d]=f(e,c[d])):c[d]=e}return c};var u=window,A=document,Ka=navigator,La=A.currentScript&&A.currentScript.src,Ma=function(a,b){var c=u[a];u[a]=void 0===c?b:c;return u[a]},Oa=function(a,b){b&&(a.addEventListener?a.onload=b:a.onreadystatechange=function(){a.readyState in{loaded:1,complete:1}&&(a.onreadystatechange=null,b())})},Pa=function(a,b,c){var d=A.createElement("script");d.type="text/javascript";d.async=!0;d.src=a;Oa(d,b);c&&(d.onerror=c);var e;if(null===fa)b:{var g=ca.document,h=g.querySelector&&g.querySelector("script[nonce]");
if(h){var k=h.nonce||h.getAttribute("nonce");if(k&&da.test(k)){fa=k;break b}}fa=""}e=fa;e&&d.setAttribute("nonce",e);var l=A.getElementsByTagName("script")[0]||A.body||A.head;l.parentNode.insertBefore(d,l);return d},Qa=function(){if(La){var a=La.toLowerCase();if(0===a.indexOf("https://"))return 2;if(0===a.indexOf("http://"))return 3}return 1},Ra=function(a,b){var c=A.createElement("iframe");c.height="0";c.width="0";c.style.display="none";c.style.visibility="hidden";var d=A.body&&A.body.lastChild||
A.body||A.head;d.parentNode.insertBefore(c,d);Oa(c,b);void 0!==a&&(c.src=a);return c},Sa=function(a,b,c){var d=new Image(1,1);d.onload=function(){d.onload=null;b&&b()};d.onerror=function(){d.onerror=null;c&&c()};d.src=a;return d},Ta=function(a,b,c,d){a.addEventListener?a.addEventListener(b,c,!!d):a.attachEvent&&a.attachEvent("on"+b,c)},Ua=function(a,b,c){a.removeEventListener?a.removeEventListener(b,c,!1):a.detachEvent&&a.detachEvent("on"+b,c)},D=function(a){u.setTimeout(a,0)},Va=function(a,b){return a&&
b&&a.attributes&&a.attributes[b]?a.attributes[b].value:null},Wa=function(a){var b=a.innerText||a.textContent||"";b&&" "!=b&&(b=b.replace(/^[\s\xa0]+|[\s\xa0]+$/g,""));b&&(b=b.replace(/(\xa0+|\s{2,}|\n|\r\t)/g," "));return b},Xa=function(a){var b=A.createElement("div");b.innerHTML="A<div>"+a+"</div>";b=b.lastChild;for(var c=[];b.firstChild;)c.push(b.removeChild(b.firstChild));return c},Za=function(a,b,c){c=c||100;for(var d={},e=0;e<b.length;e++)d[b[e]]=!0;for(var g=a,h=0;g&&h<=c;h++){if(d[String(g.tagName).toLowerCase()])return g;
g=g.parentElement}return null},$a=function(a,b){var c=a[b];c&&"string"===typeof c.animVal&&(c=c.animVal);return c};var ab=/^(?:(?:https?|mailto|ftp):|[^:/?#]*(?:[/?#]|$))/i;var bb={},cb=function(a,b){bb[a]=bb[a]||[];bb[a][b]=!0},db=function(a){for(var b=[],c=bb[a]||[],d=0;d<c.length;d++)c[d]&&(b[Math.floor(d/6)]^=1<<d%6);for(var e=0;e<b.length;e++)b[e]="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_".charAt(b[e]||0);return b.join("")};var eb=/:[0-9]+$/,fb=function(a,b,c){for(var d=a.split("&"),e=0;e<d.length;e++){var g=d[e].split("=");if(decodeURIComponent(g[0]).replace(/\+/g," ")===b){var h=g.slice(1).join("=");return c?h:decodeURIComponent(h).replace(/\+/g," ")}}},ib=function(a,b,c,d,e){b&&(b=String(b).toLowerCase());if("protocol"===b||"port"===b)a.protocol=gb(a.protocol)||gb(u.location.protocol);"port"===b?a.port=String(Number(a.hostname?a.port:u.location.port)||("http"==a.protocol?80:"https"==a.protocol?443:"")):"host"===b&&
(a.hostname=(a.hostname||u.location.hostname).replace(eb,"").toLowerCase());var g=b,h,k=gb(a.protocol);g&&(g=String(g).toLowerCase());switch(g){case "url_no_fragment":h=hb(a);break;case "protocol":h=k;break;case "host":h=a.hostname.replace(eb,"").toLowerCase();if(c){var l=/^www\d*\./.exec(h);l&&l[0]&&(h=h.substr(l[0].length))}break;case "port":h=String(Number(a.port)||("http"==k?80:"https"==k?443:""));break;case "path":a.pathname||a.hostname||cb("TAGGING",1);h="/"==a.pathname.substr(0,1)?a.pathname:
"/"+a.pathname;var m=h.split("/");0<=ma(d||[],m[m.length-1])&&(m[m.length-1]="");h=m.join("/");break;case "query":h=a.search.replace("?","");e&&(h=fb(h,e,void 0));break;case "extension":var n=a.pathname.split(".");h=1<n.length?n[n.length-1]:"";h=h.split("/")[0];break;case "fragment":h=a.hash.replace("#","");break;default:h=a&&a.href}return h},gb=function(a){return a?a.replace(":","").toLowerCase():""},hb=function(a){var b="";if(a&&a.href){var c=a.href.indexOf("#");b=0>c?a.href:a.href.substr(0,c)}return b},
jb=function(a){var b=A.createElement("a");a&&(b.href=a);var c=b.pathname;"/"!==c[0]&&(a||cb("TAGGING",1),c="/"+c);var d=b.hostname.replace(eb,"");return{href:b.href,protocol:b.protocol,host:b.host,hostname:d,pathname:c,search:b.search,hash:b.hash,port:b.port}};var kb=function(a,b,c){for(var d=[],e=String(b||document.cookie).split(";"),g=0;g<e.length;g++){var h=e[g].split("="),k=h[0].replace(/^\s*|\s*$/g,"");if(k&&k==a){var l=h.slice(1).join("=").replace(/^\s*|\s*$/g,"");l&&c&&(l=decodeURIComponent(l));d.push(l)}}return d},nb=function(a,b,c,d){var e=lb(a,d);if(1===e.length)return e[0].id;if(0!==e.length){e=mb(e,function(g){return g.Fb},b);if(1===e.length)return e[0].id;e=mb(e,function(g){return g.Wa},c);return e[0]?e[0].id:void 0}};
function ob(a,b,c){var d=document.cookie;document.cookie=a;var e=document.cookie;return d!=e||void 0!=c&&0<=kb(b,e).indexOf(c)}
var rb=function(a,b,c,d,e,g){d=d||"auto";var h={path:c||"/"};e&&(h.expires=e);"none"!==d&&(h.domain=d);var k;a:{var l=b,m;if(void 0==l)m=a+"=deleted; expires="+(new Date(0)).toUTCString();else{g&&(l=encodeURIComponent(l));var n=l;n&&1200<n.length&&(n=n.substring(0,1200));l=n;m=a+"="+l}var q=void 0,t=void 0,p;for(p in h)if(h.hasOwnProperty(p)){var r=h[p];if(null!=r)switch(p){case "secure":r&&(m+="; secure");break;case "domain":q=r;break;default:"path"==p&&(t=r),"expires"==p&&r instanceof Date&&(r=
r.toUTCString()),m+="; "+p+"="+r}}if("auto"===q){for(var v=pb(),w=0;w<v.length;++w){var y="none"!=v[w]?v[w]:void 0;if(!qb(y,t)&&ob(m+(y?"; domain="+y:""),a,l)){k=!0;break a}}k=!1}else q&&"none"!=q&&(m+="; domain="+q),k=!qb(q,t)&&ob(m,a,l)}return k};function mb(a,b,c){for(var d=[],e=[],g,h=0;h<a.length;h++){var k=a[h],l=b(k);l===c?d.push(k):void 0===g||l<g?(e=[k],g=l):l===g&&e.push(k)}return 0<d.length?d:e}
function lb(a,b){for(var c=[],d=kb(a),e=0;e<d.length;e++){var g=d[e].split("."),h=g.shift();if(!b||-1!==b.indexOf(h)){var k=g.shift();k&&(k=k.split("-"),c.push({id:g.join("."),Fb:1*k[0]||1,Wa:1*k[1]||1}))}}return c}
var sb=/^(www\.)?google(\.com?)?(\.[a-z]{2})?$/,tb=/(^|\.)doubleclick\.net$/i,qb=function(a,b){return tb.test(document.location.hostname)||"/"===b&&sb.test(a)},pb=function(){var a=[],b=document.location.hostname.split(".");if(4===b.length){var c=b[b.length-1];if(parseInt(c,10).toString()===c)return["none"]}for(var d=b.length-2;0<=d;d--)a.push(b.slice(d).join("."));a.push("none");return a};var Qb=[],Rb=[],Sb=[],Tb=[],Ub=[],Vb={},Wb,Xb,Yb,Zb=function(a,b){var c={};c["function"]="__"+a;for(var d in b)b.hasOwnProperty(d)&&(c["vtp_"+d]=b[d]);return c},$b=function(a,b){var c=a["function"];if(!c)throw Error("Error: No function name given for function call.");var d=!!Vb[c],e={},g;for(g in a)a.hasOwnProperty(g)&&0===g.indexOf("vtp_")&&(e[d?g:g.substr(4)]=a[g]);return d?Vb[c](e):(void 0)(c,e,b)},bc=function(a,b,c){c=c||[];var d={},e;for(e in a)a.hasOwnProperty(e)&&(d[e]=ac(a[e],b,c));return d},
cc=function(a){var b=a["function"];if(!b)throw"Error: No function name given for function call.";var c=Vb[b];return c?c.priorityOverride||0:0},ac=function(a,b,c){if(la(a)){var d;switch(a[0]){case "function_id":return a[1];case "list":d=[];for(var e=1;e<a.length;e++)d.push(ac(a[e],b,c));return d;case "macro":var g=a[1];if(c[g])return;var h=Qb[g];if(!h||b.zc(h))return;c[g]=!0;try{var k=bc(h,b,c);k.vtp_gtmEventId=b.id;d=$b(k,b);Yb&&(d=Yb.wf(d,k))}catch(w){b.Sd&&b.Sd(w,Number(g)),d=!1}c[g]=!1;return d;
case "map":d={};for(var l=1;l<a.length;l+=2)d[ac(a[l],b,c)]=ac(a[l+1],b,c);return d;case "template":d=[];for(var m=!1,n=1;n<a.length;n++){var q=ac(a[n],b,c);Xb&&(m=m||q===Xb.tb);d.push(q)}return Xb&&m?Xb.zf(d):d.join("");case "escape":d=ac(a[1],b,c);if(Xb&&la(a[1])&&"macro"===a[1][0]&&Xb.ag(a))return Xb.kg(d);d=String(d);for(var t=2;t<a.length;t++)ub[a[t]]&&(d=ub[a[t]](d));return d;case "tag":var p=a[1];if(!Tb[p])throw Error("Unable to resolve tag reference "+p+".");return d={Ed:a[2],index:p};case "zb":var r=
{arg0:a[2],arg1:a[3],ignore_case:a[5]};r["function"]=a[1];var v=dc(r,b,c);a[4]&&(v=!v);return v;default:throw Error("Attempting to expand unknown Value type: "+a[0]+".");}}return a},dc=function(a,b,c){try{return Wb(bc(a,b,c))}catch(d){JSON.stringify(a)}return null};var ec=function(){var a=function(b){return{toString:function(){return b}}};return{$c:a("convert_case_to"),ad:a("convert_false_to"),bd:a("convert_null_to"),cd:a("convert_true_to"),dd:a("convert_undefined_to"),ia:a("function"),Le:a("instance_name"),Me:a("live_only"),Ne:a("malware_disabled"),Oe:a("metadata"),Vg:a("original_vendor_template_id"),Pe:a("once_per_event"),td:a("once_per_load"),ud:a("setup_tags"),vd:a("tag_id"),wd:a("teardown_tags")}}();var fc=null,ic=function(a){function b(q){for(var t=0;t<q.length;t++)d[q[t]]=!0}var c=[],d=[];fc=gc(a);for(var e=0;e<Rb.length;e++){var g=Rb[e],h=hc(g);if(h){for(var k=g.add||[],l=0;l<k.length;l++)c[k[l]]=!0;b(g.block||[])}else null===h&&b(g.block||[])}for(var m=[],n=0;n<Tb.length;n++)c[n]&&!d[n]&&(m[n]=!0);return m},hc=function(a){for(var b=a["if"]||[],c=0;c<b.length;c++){var d=fc(b[c]);if(!d)return null===d?null:!1}for(var e=a.unless||[],g=0;g<e.length;g++){var h=fc(e[g]);if(null===h)return null;
if(h)return!1}return!0},gc=function(a){var b=[];return function(c){void 0===b[c]&&(b[c]=dc(Sb[c],a));return b[c]}};/*
 Copyright (c) 2014 Derek Brans, MIT license https://github.com/krux/postscribe/blob/master/LICENSE. Portions derived from simplehtmlparser, which is licensed under the Apache License, Version 2.0 */
var xc={},yc=null,zc=Math.random();xc.i="AW-973395369";xc.xb="7f1";var Ac={__cl:!0,__ecl:!0,__ehl:!0,__evl:!0,__fal:!0,__fil:!0,__fsl:!0,__hl:!0,__jel:!0,__lcl:!0,__sdl:!0,__tl:!0,__ytl:!0},Cc="www.googletagmanager.com/gtm.js";Cc="www.googletagmanager.com/gtag/js";var Dc=Cc,Ec=null,Fc=null,Gc=null,Hc="//www.googletagmanager.com/a?id="+xc.i+"&cv=1",Ic={},Jc={},Kc=function(){var a=yc.sequence||0;yc.sequence=a+1;return a};var G=function(a,b,c,d){return(2===Lc()||d||"http:"!=u.location.protocol?a:b)+c},Lc=function(){var a=Qa(),b;if(1===a)a:{var c=Dc;c=c.toLowerCase();for(var d="https://"+c,e="http://"+c,g=1,h=A.getElementsByTagName("script"),k=0;k<h.length&&100>k;k++){var l=h[k].src;if(l){l=l.toLowerCase();if(0===l.indexOf(e)){b=3;break a}1===g&&0===l.indexOf(d)&&(g=2)}}b=g}else b=a;return b};var Mc=!1;var Nc=function(a,b,c,d){if(c){d=d||{};var e=u._googWcmImpl||function(){e.q=e.q||[];e.q.push(arguments)};u._googWcmImpl=e;void 0===u._googWcmAk&&(u._googWcmAk=a);Mc?d.Ba&&D(d.Ba):(Pa(G("https://","http://","www.gstatic.com/wcm/loader.js"),d.Ba,d.Vd),Mc=!0);var g={ak:a,cl:b};void 0===d.me&&(g.autoreplace=c);e(2,d.me,g,c,0,new Date,d.Qg)}};
var Qc=function(){return"&tc="+Tb.filter(function(a){return a}).length},Zc=function(){Rc&&(u.clearTimeout(Rc),Rc=void 0);void 0===Sc||Tc[Sc]&&!Uc||(Vc[Sc]||Wc.cg()||0>=Xc--?(cb("GTM",1),Vc[Sc]=!0):(Wc.wg(),Sa(Yc()),Tc[Sc]=!0,Uc=""))},Yc=function(){var a=Sc;if(void 0===a)return"";var b=db("GTM"),c=db("TAGGING");return[$c,Tc[a]?"":"&es=1",ad[a],b?"&u="+b:"",c?"&ut="+c:"",Qc(),Uc,"&z=0"].join("")},bd=function(){return[Hc,"&v=3&t=t","&pid="+oa(),"&rv="+xc.xb].join("")},cd="0.005000">
Math.random(),$c=bd(),dd=function(){$c=bd()},Tc={},Uc="",Sc=void 0,ad={},Vc={},Rc=void 0,Wc=function(a,b){var c=0,d=0;return{cg:function(){if(c<a)return!1;xa()-d>=b&&(c=0);return c>=a},wg:function(){xa()-d>=b&&(c=0);c++;d=xa()}}}(2,1E3),Xc=1E3,ed=function(a,b){if(cd&&!Vc[a]&&Sc!==a){Zc();Sc=a;Uc="";var c;c=0===b.indexOf("gtm.")?encodeURIComponent(b):"*";ad[a]="&e="+c+"&eid="+a;Rc||(Rc=u.setTimeout(Zc,500))}},fd=function(a,b,c){if(cd&&!Vc[a]&&b){a!==Sc&&(Zc(),Sc=a);var d=String(b[ec.ia]||"").replace(/_/g,
"");0===d.indexOf("cvt")&&(d="cvt");var e=c+d;Uc=Uc?Uc+"."+e:"&tr="+e;Rc||(Rc=u.setTimeout(Zc,500));2022<=Yc().length&&Zc()}};var gd={},hd=new qa,id={},jd={},nd={name:"dataLayer",set:function(a,b){f(kd(a,b),id);ld()},get:function(a){return md(a,2)},reset:function(){hd=new qa;id={};ld()}},md=function(a,b){if(2!=b){var c=hd.get(a);if(cd){var d=od(a);c!==d&&cb("GTM",5)}return c}return od(a)},od=function(a,b,c){var d=a.split("."),e=!1,g=void 0;var h=function(k,l){for(var m=0;void 0!==k&&m<d.length;m++){if(null===k)return!1;k=k[d[m]]}return void 0!==k||1<m?k:l.length?h(pd(l.pop()),l):qd(d)};
e=!0;g=h(id.eventModel,[b,c]);return e?g:qd(d)},qd=function(a){for(var b=id,c=0;c<a.length;c++){if(null===b)return!1;if(void 0===b)break;b=b[a[c]]}return b};
var rd=function(a,b){return od(a,b,void 0)},pd=function(a){if(a){var b=qd(["gtag","targets",a]);return Ia(b)?b:void 0}},sd=function(a,b){function c(g){g&&sa(g,function(h){d[h]=null})}var d={};c(id);delete d.eventModel;c(pd(a));c(pd(b));c(id.eventModel);var e=[];sa(d,function(g){e.push(g)});return e};
var td=function(a,b){jd.hasOwnProperty(a)||(hd.set(a,b),f(kd(a,b),id),ld())},kd=function(a,b){for(var c={},d=c,e=a.split("."),g=0;g<e.length-1;g++)d=d[e[g]]={};d[e[e.length-1]]=b;return c},ld=function(a){sa(jd,function(b,c){hd.set(b,c);f(kd(b,void 0),id);f(kd(b,c),id);a&&delete jd[b]})},ud=function(a,b,c){gd[a]=gd[a]||{};var d=1!==c?od(b):hd.get(b);"array"===Ga(d)||"object"===Ga(d)?gd[a][b]=f(d):gd[a][b]=d},vd=function(a,b){if(gd[a])return gd[a][b]};var wd=new RegExp(/^(.*\.)?(google|youtube|blogger|withgoogle)(\.com?)?(\.[a-z]{2})?\.?$/),xd={cl:["ecl"],customPixels:["nonGooglePixels"],ecl:["cl"],ehl:["hl"],hl:["ehl"],html:["customScripts","customPixels","nonGooglePixels","nonGoogleScripts","nonGoogleIframes"],customScripts:["html","customPixels","nonGooglePixels","nonGoogleScripts","nonGoogleIframes"],nonGooglePixels:[],nonGoogleScripts:["nonGooglePixels"],nonGoogleIframes:["nonGooglePixels"]},yd={cl:["ecl"],customPixels:["customScripts","html"],
ecl:["cl"],ehl:["hl"],hl:["ehl"],html:["customScripts"],customScripts:["html"],nonGooglePixels:["customPixels","customScripts","html","nonGoogleScripts","nonGoogleIframes"],nonGoogleScripts:["customScripts","html"],nonGoogleIframes:["customScripts","html","nonGoogleScripts"]},zd="google customPixels customScripts html nonGooglePixels nonGoogleScripts nonGoogleIframes".split(" ");
var Bd=function(a){var b=md("gtm.whitelist");b&&cb("GTM",9);b="google gtagfl lcl zone oid op".split(" ");var c=b&&Da(va(b),xd),d=md("gtm.blacklist");d||(d=md("tagTypeBlacklist"))&&cb("GTM",3);
d?cb("GTM",8):d=[];Ad()&&(d=va(d),d.push("nonGooglePixels","nonGoogleScripts"));0<=ma(va(d),"google")&&cb("GTM",2);var e=d&&Da(va(d),yd),g={};return function(h){var k=h&&h[ec.ia];if(!k||"string"!=typeof k)return!0;k=k.replace(/^_*/,"");if(void 0!==g[k])return g[k];var l=Jc[k]||[],m=a(k);if(b){var n;if(n=m)a:{if(0>ma(c,k))if(l&&0<l.length)for(var q=0;q<l.length;q++){if(0>
ma(c,l[q])){cb("GTM",11);n=!1;break a}}else{n=!1;break a}n=!0}m=n}var t=!1;if(d){var p=0<=ma(e,k);if(p)t=p;else{var r=ra(e,l||[]);r&&cb("GTM",10);t=r}}var v=!m||t;v||!(0<=ma(l,"sandboxedScripts"))||c&&-1!==ma(c,"sandboxedScripts")||(v=ra(e,zd));return g[k]=v}},Ad=function(){return wd.test(u.location&&u.location.hostname)};var Cd={wf:function(a,b){b[ec.$c]&&"string"===typeof a&&(a=1==b[ec.$c]?a.toLowerCase():a.toUpperCase());b.hasOwnProperty(ec.bd)&&null===a&&(a=b[ec.bd]);b.hasOwnProperty(ec.dd)&&void 0===a&&(a=b[ec.dd]);b.hasOwnProperty(ec.cd)&&!0===a&&(a=b[ec.cd]);b.hasOwnProperty(ec.ad)&&!1===a&&(a=b[ec.ad]);return a}};var Dd={active:!0,isWhitelisted:function(){return!0}},Ed=function(a){var b=yc.zones;!b&&a&&(b=yc.zones=a());return b};var Fd=!1,Gd=0,Hd=[];function Id(a){if(!Fd){var b=A.createEventObject,c="complete"==A.readyState,d="interactive"==A.readyState;if(!a||"readystatechange"!=a.type||c||!b&&d){Fd=!0;for(var e=0;e<Hd.length;e++)D(Hd[e])}Hd.push=function(){for(var g=0;g<arguments.length;g++)D(arguments[g]);return 0}}}function Jd(){if(!Fd&&140>Gd){Gd++;try{A.documentElement.doScroll("left"),Id()}catch(a){u.setTimeout(Jd,50)}}}var Kd=function(a){Fd?a():Hd.push(a)};var Ld={},Md={},Nd=function(a,b,c,d){if(!Md[a]||Ac[b]||"__zone"===b)return-1;var e={};Ia(d)&&(e=f(d,e));e.id=c;e.status="timeout";return Md[a].tags.push(e)-1},Od=function(a,b,c,d){if(Md[a]){var e=Md[a].tags[b];e&&(e.status=c,e.executionTime=d)}};function Pd(a){for(var b=Ld[a]||[],c=0;c<b.length;c++)b[c]();Ld[a]={push:function(d){d(xc.i,Md[a])}}}
var Sd=function(a,b,c){Md[a]={tags:[]};ia(b)&&Qd(a,b);c&&u.setTimeout(function(){return Pd(a)},Number(c));return Rd(a)},Qd=function(a,b){Ld[a]=Ld[a]||[];Ld[a].push(za(function(){return D(function(){b(xc.i,Md[a])})}))};function Rd(a){var b=0,c=0,d=!1;return{add:function(){c++;return za(function(){b++;d&&b>=c&&Pd(a)})},cf:function(){d=!0;b>=c&&Pd(a)}}};var Td=function(){function a(d){return!ka(d)||0>d?0:d}if(!yc._li&&u.performance&&u.performance.timing){var b=u.performance.timing.navigationStart,c=ka(nd.get("gtm.start"))?nd.get("gtm.start"):0;yc._li={cst:a(c-b),cbt:a(Fc-b)}}};var Xd=!1,Yd=function(){return u.GoogleAnalyticsObject&&u[u.GoogleAnalyticsObject]},Zd=!1;
var $d=function(a){u.GoogleAnalyticsObject||(u.GoogleAnalyticsObject=a||"ga");var b=u.GoogleAnalyticsObject;if(u[b])u.hasOwnProperty(b)||cb("GTM",12);else{var c=function(){c.q=c.q||[];c.q.push(arguments)};c.l=Number(new Date);u[b]=c}Td();return u[b]},ae=function(a,b,c,d){b=String(b).replace(/\s+/g,"").split(",");var e=Yd();e(a+"require","linker");e(a+"linker:autoLink",b,c,d)};
var ce=function(){},be=function(){return u.GoogleAnalyticsObject||"ga"},de=!1;
var ee=function(a,b,c){if(b){c=c||{};var d=u._gaPhoneImpl||function(){d.q=d.q||[];d.q.push(arguments)};u._gaPhoneImpl=d;void 0===u.ga_wpid&&(u.ga_wpid=a);de?c.Ba&&D(c.Ba):(Pa(G("https://","http://","www.gstatic.com/gaphone/loader.js"),c.Ba,c.Vd),de=!0);var e={};void 0!==c.Hd?e.receiver=c.Hd:e.replace=b;e.ga_wpid=a;e.destination=b;d(2,new Date,e)}};var ke=function(a){};function je(a,b){a.containerId=xc.i;var c={type:"GENERIC",value:a};b.length&&(c.trace=b);return c};function le(a,b,c,d){var e=Tb[a],g=me(a,b,c,d);if(!g)return null;var h=ac(e[ec.ud],c,[]);if(h&&h.length){var k=h[0];g=le(k.index,{J:g,O:1===k.Ed?b.terminate:g,terminate:b.terminate},c,d)}return g}
function me(a,b,c,d){function e(){if(g[ec.Ne])k();else{var w=bc(g,c,[]),y=Nd(c.id,String(g[ec.ia]),Number(g[ec.vd]),w[ec.Oe]),x=!1;w.vtp_gtmOnSuccess=function(){if(!x){x=!0;var B=xa()-C;fd(c.id,Tb[a],"5");Od(c.id,y,"success",B);h()}};w.vtp_gtmOnFailure=function(){if(!x){x=!0;var B=xa()-C;fd(c.id,Tb[a],"6");Od(c.id,y,"failure",B);k()}};w.vtp_gtmTagId=g.tag_id;
w.vtp_gtmEventId=c.id;fd(c.id,g,"1");var z=function(B){var E=xa()-C;ke(B);fd(c.id,g,"7");Od(c.id,y,"exception",E);x||(x=!0,k())};var C=xa();try{$b(w,c)}catch(B){z(B)}}}var g=Tb[a],h=b.J,k=b.O,l=b.terminate;if(c.zc(g))return null;var m=ac(g[ec.wd],c,[]);if(m&&m.length){var n=m[0],q=le(n.index,{J:h,O:k,terminate:l},c,d);if(!q)return null;h=q;k=2===n.Ed?l:q}if(g[ec.td]||g[ec.Pe]){var t=g[ec.td]?Ub:c.Gg,p=h,r=k;if(!t[a]){e=za(e);var v=ne(a,t,e);h=v.J;k=v.O}return function(){t[a](p,r)}}return e}
function ne(a,b,c){var d=[],e=[];b[a]=oe(d,e,c);return{J:function(){b[a]=pe;for(var g=0;g<d.length;g++)d[g]()},O:function(){b[a]=qe;for(var g=0;g<e.length;g++)e[g]()}}}function oe(a,b,c){return function(d,e){a.push(d);b.push(e);c()}}function pe(a){a()}function qe(a,b){b()};var te=function(a,b){for(var c=[],d=0;d<Tb.length;d++)if(a.Va[d]){var e=Tb[d];var g=b.add();try{var h=le(d,{J:g,O:g,terminate:g},a,d);h?c.push({je:d,$d:cc(e),Hf:h}):(re(d,a),g())}catch(l){g()}}b.cf();c.sort(se);for(var k=0;k<c.length;k++)c[k].Hf();return 0<c.length};function se(a,b){var c,d=b.$d,e=a.$d;c=d>e?1:d<e?-1:0;var g;if(0!==c)g=c;else{var h=a.je,k=b.je;g=h>k?1:h<k?-1:0}return g}
function re(a,b){if(!cd)return;var c=function(d){var e=b.zc(Tb[d])?"3":"4",g=ac(Tb[d][ec.ud],b,[]);g&&g.length&&c(g[0].index);fd(b.id,Tb[d],e);var h=ac(Tb[d][ec.wd],b,[]);h&&h.length&&c(h[0].index)};c(a);}
var ue=!1,ve=function(a,b,c,d,e){if("gtm.js"==b){if(ue)return!1;ue=!0}ed(a,b);var g=Sd(a,d,e);ud(a,"event",1);ud(a,"ecommerce",1);ud(a,"gtm");var h={id:a,name:b,zc:Bd(c),Va:[],Gg:[],Sd:function(n){cb("GTM",6);ke(n)}};h.Va=ic(h);var k=te(h,g);"gtm.js"!==b&&"gtm.sync"!==b||ce();if(!k)return k;for(var l=0;l<h.Va.length;l++)if(h.Va[l]){var m=
Tb[l];if(m&&!Ac[String(m[ec.ia])])return!0}return!1};var we=function(a,b){var c=Zb(a,b);Tb.push(c);return Tb.length-1};var xe=function(a,b,c){var d=this;this.eventModel=a;this.targetConfig=b||{};this.globalConfig=c||{};this.getWithConfig=function(e){if(d.eventModel.hasOwnProperty(e))return d.eventModel[e];if(d.targetConfig.hasOwnProperty(e))return d.targetConfig[e];if(d.globalConfig.hasOwnProperty(e))return d.globalConfig[e]}};var H={Ub:"event_callback",Wb:"event_timeout",R:"gtag.config"};
H.Sb="page_view",H.ne="user_engagement",H.U="allow_ad_personalization_signals",H.oe="allow_custom_scripts",H.pe="allow_display_features",H.qe="allow_enhanced_conversions",H.gb="client_id",H.N="cookie_domain",H.W="cookie_expires",H.hb="cookie_name",H.qa="cookie_path",H.te="cookie_update",H.ra="currency",H.ib="custom_params",H.ve="custom_map",H.Yb="groups",H.Ja="language",H.ue="country",H.Ug="non_interaction",H.ob="page_location",H.pb="page_referrer",H.pd="page_title",H.La="send_page_view",H.sa="send_to",
H.qb="session_duration",H.cc="session_engaged",H.rb="session_id",H.fc="session_number",H.Je="tracking_id",H.sb="user_properties",H.Ka="linker",H.lb="accept_incoming",H.I="domains",H.nb="url_position",H.mb="decorate_forms",H.bc="phone_conversion_number",H.$b="phone_conversion_callback",H.ac="phone_conversion_css_class",H.qd="phone_conversion_options",H.ed="aw_remarketing",H.fd="aw_remarketing_only",H.fa="value",H.He="quantity",H.ye="affiliation",H.Ce="tax",H.Be="shipping",H.Tb="list_name",H.od="checkout_step",
H.nd="checkout_option",H.ze="coupon",H.Ae="promotions",H.Ma="transaction_id",H.X="user_id",H.Ia="conversion_linker",H.Ha="conversion_cookie_prefix",H.H="cookie_prefix",H.V="items",H.kd="aw_merchant_id",H.hd="aw_feed_country",H.jd="aw_feed_language",H.gd="discount",H.md="disable_merchant_reported_purchases",H.Zb="new_customer",H.ld="customer_lifetime_value",H.xe="dc_natural_search",H.we="dc_custom_params",H.Ke="trip_type",H.Ge="passengers",H.Ee="method",H.Ie="search_term",H.se="content_type",H.Fe=
"optimize_id",H.De="experiments",H.kb="google_signals",H.Xb="google_tld",H.jb="ga_restrict_domain",H.Vb="event_settings",H.rd=[H.U,H.N,H.W,H.hb,H.qa,H.H,H.ib,H.Ub,H.Vb,H.Wb,H.jb,H.kb,H.Xb,H.Yb,H.sa,H.La,H.qb,H.X,H.sb],H.Zc=[H.sa,H.ed,H.fd,H.ib,H.La,H.Ja,H.fa,H.ra,H.Ma,H.X,H.Ia,H.Ha,H.H,H.ob,H.pb,H.bc,H.$b,H.ac,H.qd,H.V,H.kd,H.hd,H.jd,H.gd,H.md,H.Zb,H.ld,H.U];var ye=function(){var a=!1;return a};function ze(){var a=yc;return a.gcq=a.gcq||new Ae}var Be=function(a,b){ze().register(a,b)},Ce=function(){this.status=1;this.oc={};this.ae=null},De=function(a,b,c,d,e){this.type=a;this.Lg=b;this.ca=c||"";this.zb=d;this.defer=e},Ae=function(){this.ke={};this.Kd={};this.Qa=[]},Ee=function(a,b){return a.ke[b]=a.ke[b]||new Ce},Fe=function(a,b,c,d){var e=Ee(a,d.ca).ae;if(e){var g=f(c),h=f(Ee(a,d.ca).oc),k=f(a.Kd),l=new xe(g,h,k);try{e(b,d.Lg,l)}catch(m){}}};
Ae.prototype.register=function(a,b){3!==Ee(this,a).status&&(Ee(this,a).ae=b,Ee(this,a).status=3,this.flush())};Ae.prototype.push=function(a,b,c,d){var e=Math.floor(xa()/1E3);if(c&&1===Ee(this,c).status&&(Ee(this,c).status=2,this.push("require",[],c),!ye())){var g=encodeURIComponent(c);Pa(("http:"!=u.location.protocol?"https:":"http:")+("//www.googletagmanager.com/gtag/js?id="+g+"&l=dataLayer&cx=c"))}this.Qa.push(new De(a,e,c,b,d));d||this.flush()};
Ae.prototype.flush=function(a){for(var b=this;this.Qa.length;){var c=this.Qa[0];if(c.defer)c.defer=!1,this.Qa.push(c);else switch(c.type){case "require":if(3!==Ee(this,c.ca).status&&!a)return;break;case "set":sa(c.zb[0],function(e,g){b.Kd[e]=g});break;case "config":var d=c.zb[0];Ee(this,c.ca).oc={};Fe(this,H.R,d,c);Ee(this,c.ca).oc=d;break;case "event":Fe(this,c.zb[1],c.zb[0],c)}this.Qa.shift()}};var Ge=/[A-Z]+/,He=/\s/,Ie=function(a){if(ja(a)&&(a=wa(a),!He.test(a))){var b=a.indexOf("-");if(!(0>b)){var c=a.substring(0,b);if(Ge.test(c)){for(var d=a.substring(b+1).split("/"),e=0;e<d.length;e++)if(!d[e])return;return{id:a,prefix:c,containerId:c+"-"+d[0],ja:d}}}}},Ke=function(a){for(var b={},c=0;c<a.length;++c){var d=Ie(a[c]);d&&(b[d.id]=d)}Je(b);var e=[];sa(b,function(g,h){e.push(h)});return e};
function Je(a){var b=[],c;for(c in a)if(a.hasOwnProperty(c)){var d=a[c];"AW"===d.prefix&&d.ja[1]&&b.push(d.containerId)}for(var e=0;e<b.length;++e)delete a[b[e]]};var Le={};var Me=null,Ne={},Oe={},Qe,Re=function(a,b){var c={event:a};b&&(c.eventModel=f(b),b[H.Ub]&&(c.eventCallback=b[H.Ub]),b[H.Wb]&&(c.eventTimeout=b[H.Wb]));return c};
var Se=function(){Me=Me||!yc.gtagRegistered;yc.gtagRegistered=!0;return Me},Te=function(a){if(void 0===Oe[a.id]){var b;switch(a.prefix){case "UA":b=we("gtagua",{trackingId:a.id});break;case "AW":b=we("gtagaw",{conversionId:a});break;case "DC":b=we("gtagfl",{targetId:a.id});break;case "GF":b=we("gtaggf",{conversionId:a});break;case "G":b=we("get",{trackingId:a.id,isAutoTag:!0});break;case "HA":b=we("gtagha",{conversionId:a});break;default:return}if(!Qe){var c=Zb("v",{name:"send_to",dataLayerVersion:2});
Qb.push(c);Qe=["macro",Qb.length-1]}var d={arg0:Qe,arg1:a.id,ignore_case:!1};d[ec.ia]="_lc";Sb.push(d);var e={"if":[Sb.length-1],add:[b]};e["if"]&&(e.add||e.block)&&Rb.push(e);Oe[a.id]=b}},Ue=function(a){sa(Ne,function(b,c){var d=ma(c,a);0<=d&&c.splice(d,1)})},Ve=za(function(){}),We=function(a){if(a.containerId!==xc.i&&"G"!==a.prefix){var b;switch(a.prefix){case "UA":b=14;break;case "AW":b=15;break;case "DC":b=16;break;default:b=17}cb("GTM",b)}};
var Xe={config:function(a){var b=a[2]||{};if(2>a.length||!ja(a[1])||!Ia(b))return;var c=Ie(a[1]);if(!c)return;Se()?(Te(c),We(c)):Ve();Ue(c.id);var d=c.id,e=b[H.Yb]||"default";e=e.toString().split(",");for(var g=0;g<e.length;g++)Ne[e[g]]=Ne[e[g]]||[],Ne[e[g]].push(d);delete b[H.Yb];td("gtag.targets."+c.id,void 0);td("gtag.targets."+c.id,f(b));var h={};h[H.sa]=c.id;return Re(H.R,h);},event:function(a){var b=a[1];if(ja(b)&&!(3<a.length)){var c;
if(2<a.length){if(!Ia(a[2]))return;c=a[2]}var d=Re(b,c);var e;var g=c,h=md("gtag.fields.send_to",2);ja(h)||(h=H.sa);var k=g&&g[h];void 0===k&&(k=md(h,2),void 0===k&&(k="default"));if(ja(k)||la(k)){for(var l=k.toString().replace(/\s+/g,"").split(","),m=[],n=0;n<l.length;n++)0<=l[n].indexOf("-")?m.push(l[n]):m=m.concat(Ne[l[n]]||[]);e=Ke(m)}else e=void 0;var q=e;if(!q)return;var t=Se();t||Ve();for(var p=[],r=0;t&&r<q.length;r++){var v=q[r];We(v);p.push(v.id);Te(v)}d.eventModel=
d.eventModel||{};0<q.length?d.eventModel[H.sa]=p.join():delete d.eventModel[H.sa];return d}},js:function(a){if(2==a.length&&a[1].getTime)return{event:"gtm.js","gtm.start":a[1].getTime()}},policy:function(a){if(3===a.length){var b=a[1],c=a[2];Le[b]||(Le[b]=[]);Le[b].push(c)}},set:function(a){var b;2==a.length&&Ia(a[1])?b=f(a[1]):3==a.length&&ja(a[1])&&(b={},b[a[1]]=a[2]);if(b){b.eventModel=f(b);b.event="gtag.set";b._clear=!0;return b}}},Ye={policy:!0};var $e=function(a){return Ze?A.querySelectorAll(a):null},af=function(a,b){if(!Ze)return null;if(Element.prototype.closest)try{return a.closest(b)}catch(e){return null}var c=Element.prototype.matches||Element.prototype.webkitMatchesSelector||Element.prototype.mozMatchesSelector||Element.prototype.msMatchesSelector||Element.prototype.oMatchesSelector,d=a;if(!A.documentElement.contains(d))return null;do{try{if(c.call(d,b))return d}catch(e){break}d=d.parentElement||d.parentNode}while(null!==d&&1===d.nodeType);
return null},bf=!1;if(A.querySelectorAll)try{var cf=A.querySelectorAll(":root");cf&&1==cf.length&&cf[0]==A.documentElement&&(bf=!0)}catch(a){}var Ze=bf;var kf=function(a){if(jf(a))return a;this.Og=a};kf.prototype.Of=function(){return this.Og};var jf=function(a){return!a||"object"!==Ga(a)||Ia(a)?!1:"getUntrustedUpdateValue"in a};kf.prototype.getUntrustedUpdateValue=kf.prototype.Of;var lf=!1,mf=[];function nf(){if(!lf){lf=!0;for(var a=0;a<mf.length;a++)D(mf[a])}}var of=function(a){lf?D(a):mf.push(a)};var pf=[],qf=!1,rf=function(a){return u["dataLayer"].push(a)},sf=function(a){var b=yc["dataLayer"],c=b?b.subscribers:1,d=0;return function(){++d===c&&a()}},uf=function(a){var b=a._clear;sa(a,function(g,h){"_clear"!==g&&(b&&td(g,void 0),td(g,h))});Ec||(Ec=a["gtm.start"]);var c=a.event;if(!c)return!1;var d=a["gtm.uniqueEventId"];d||(d=Kc(),a["gtm.uniqueEventId"]=d,td("gtm.uniqueEventId",d));Gc=c;var e=tf(a);
Gc=null;switch(c){case "gtag.set":e&&cb("GTM",18);break;case "gtm.init":cb("GTM",19),e&&cb("GTM",20)}return e};function tf(a){var b=a.event,c=a["gtm.uniqueEventId"],d,e=yc.zones;d=e?e.checkState(xc.i,c):Dd;return d.active?ve(c,b,d.isWhitelisted,a.eventCallback,a.eventTimeout)?!0:!1:!1}
var vf=function(){for(var a=!1;!qf&&0<pf.length;){qf=!0;delete id.eventModel;ld();var b=pf.shift();if(null!=b){var c=jf(b);if(c){var d=b;b=jf(d)?d.getUntrustedUpdateValue():void 0;for(var e=["gtm.whitelist","gtm.blacklist","tagTypeBlacklist"],g=0;g<e.length;g++){var h=e[g],k=md(h,1);if(la(k)||Ia(k))k=f(k);jd[h]=k}}try{if(ia(b))try{b.call(nd)}catch(v){}else if(la(b)){var l=b;if(ja(l[0])){var m=
l[0].split("."),n=m.pop(),q=l.slice(1),t=md(m.join("."),2);if(void 0!==t&&null!==t)try{t[n].apply(t,q)}catch(v){}}}else{var p=b;if(p&&("[object Arguments]"==Object.prototype.toString.call(p)||Object.prototype.hasOwnProperty.call(p,"callee"))){a:{if(b.length&&ja(b[0])){var r=Xe[b[0]];if(r&&(!c||!Ye[b[0]])){b=r(b);break a}}b=void 0}if(!b){qf=!1;continue}}a=uf(b)||a}}finally{c&&ld(!0)}}qf=!1}
return!a},wf=function(){var a=vf();try{var b=xc.i,c=u["dataLayer"].hide;if(c&&void 0!==c[b]&&c.end){c[b]=!1;var d=!0,e;for(e in c)if(c.hasOwnProperty(e)&&!0===c[e]){d=!1;break}d&&(c.end(),c.end=null)}}catch(g){}return a},xf=function(){var a=Ma("dataLayer",[]),b=Ma("google_tag_manager",{});b=b["dataLayer"]=b["dataLayer"]||{};Kd(function(){b.gtmDom||(b.gtmDom=!0,a.push({event:"gtm.dom"}))});of(function(){b.gtmLoad||(b.gtmLoad=!0,a.push({event:"gtm.load"}))});b.subscribers=(b.subscribers||
0)+1;var c=a.push;a.push=function(){var d;if(0<yc.SANDBOXED_JS_SEMAPHORE){d=[];for(var e=0;e<arguments.length;e++)d[e]=new kf(arguments[e])}else d=[].slice.call(arguments,0);var g=c.apply(a,d);pf.push.apply(pf,d);if(300<this.length)for(cb("GTM",4);300<this.length;)this.shift();var h="boolean"!==typeof g||g;return vf()&&h};pf.push.apply(pf,a.slice(0));D(wf)};var yf;var Uf={};Uf.tb=new String("undefined");
var Vf=function(a){this.resolve=function(b){for(var c=[],d=0;d<a.length;d++)c.push(a[d]===Uf.tb?b:a[d]);return c.join("")}};Vf.prototype.toString=function(){return this.resolve("undefined")};Vf.prototype.valueOf=Vf.prototype.toString;Uf.Qe=Vf;Uf.hc={};Uf.zf=function(a){return new Vf(a)};var Wf={};Uf.xg=function(a,b){var c=Kc();Wf[c]=[a,b];return c};Uf.Bd=function(a){var b=a?0:1;return function(c){var d=Wf[c];if(d&&"function"===typeof d[b])d[b]();Wf[c]=void 0}};Uf.ag=function(a){for(var b=!1,c=!1,
d=2;d<a.length;d++)b=b||8===a[d],c=c||16===a[d];return b&&c};Uf.kg=function(a){if(a===Uf.tb)return a;var b=Kc();Uf.hc[b]=a;return'google_tag_manager["'+xc.i+'"].macro('+b+")"};Uf.eg=function(a,b,c){a instanceof Uf.Qe&&(a=a.resolve(Uf.xg(b,c)),b=ha);return{xc:a,J:b}};var Xf=function(a,b,c){function d(g,h){var k=g[h];return k}var e={event:b,"gtm.element":a,"gtm.elementClasses":d(a,"className"),"gtm.elementId":a["for"]||Va(a,"id")||"","gtm.elementTarget":a.formTarget||d(a,"target")||""};c&&(e["gtm.triggers"]=c.join(","));e["gtm.elementUrl"]=(a.attributes&&a.attributes.formaction?a.formAction:"")||a.action||d(a,"href")||a.src||a.code||a.codebase||
"";return e},Yf=function(a){yc.hasOwnProperty("autoEventsSettings")||(yc.autoEventsSettings={});var b=yc.autoEventsSettings;b.hasOwnProperty(a)||(b[a]={});return b[a]},Zf=function(a,b,c){Yf(a)[b]=c},$f=function(a,b,c,d){var e=Yf(a),g=ya(e,b,d);e[b]=c(g)},ag=function(a,b,c){var d=Yf(a);return ya(d,b,c)};var bg=function(){for(var a=Ka.userAgent+(A.cookie||"")+(A.referrer||""),b=a.length,c=u.history.length;0<c;)a+=c--^b++;var d=1,e,g,h;if(a)for(d=0,g=a.length-1;0<=g;g--)h=a.charCodeAt(g),d=(d<<6&268435455)+h+(h<<14),e=d&266338304,d=0!=e?d^e>>21:d;return[Math.round(2147483647*Math.random())^d&2147483647,Math.round(xa()/1E3)].join(".")},eg=function(a,b,c,d){var e=cg(b);return nb(a,e,dg(c),d)},cg=function(a){if(!a)return 1;a=0===a.indexOf(".")?a.substr(1):a;return a.split(".").length},dg=function(a){if(!a||
"/"===a)return 1;"/"!==a[0]&&(a="/"+a);"/"!==a[a.length-1]&&(a+="/");return a.split("/").length-1};function fg(a,b){var c=""+cg(a),d=dg(b);1<d&&(c+="-"+d);return c};var gg=["1"],hg={},lg=function(a,b,c,d){var e=ig(a);hg[e]||jg(e,b,c)||(kg(e,bg(),b,c,d),jg(e,b,c))};function kg(a,b,c,d,e){var g;g=["1",fg(d,c),b].join(".");rb(a,g,c,d,0==e?void 0:new Date(xa()+1E3*(void 0==e?7776E3:e)))}function jg(a,b,c){var d=eg(a,b,c,gg);d&&(hg[a]=d);return d}function ig(a){return(a||"_gcl")+"_au"};var mg=function(){for(var a=[],b=A.cookie.split(";"),c=/^\s*_gac_(UA-\d+-\d+)=\s*(.+?)\s*$/,d=0;d<b.length;d++){var e=b[d].match(c);e&&a.push({Tc:e[1],value:e[2]})}var g={};if(!a||!a.length)return g;for(var h=0;h<a.length;h++){var k=a[h].value.split(".");"1"==k[0]&&3==k.length&&k[1]&&(g[a[h].Tc]||(g[a[h].Tc]=[]),g[a[h].Tc].push({timestamp:k[1],Lf:k[2]}))}return g};function ng(){for(var a=og,b={},c=0;c<a.length;++c)b[a[c]]=c;return b}function pg(){var a="ABCDEFGHIJKLMNOPQRSTUVWXYZ";a+=a.toLowerCase()+"0123456789-_";return a+"."}
var og,qg,rg=function(a){og=og||pg();qg=qg||ng();for(var b=[],c=0;c<a.length;c+=3){var d=c+1<a.length,e=c+2<a.length,g=a.charCodeAt(c),h=d?a.charCodeAt(c+1):0,k=e?a.charCodeAt(c+2):0,l=g>>2,m=(g&3)<<4|h>>4,n=(h&15)<<2|k>>6,q=k&63;e||(q=64,d||(n=64));b.push(og[l],og[m],og[n],og[q])}return b.join("")},sg=function(a){function b(l){for(;d<a.length;){var m=a.charAt(d++),n=qg[m];if(null!=n)return n;if(!/^[\s\xa0]*$/.test(m))throw Error("Unknown base64 encoding at char: "+m);}return l}og=og||pg();qg=qg||
ng();for(var c="",d=0;;){var e=b(-1),g=b(0),h=b(64),k=b(64);if(64===k&&-1===e)return c;c+=String.fromCharCode(e<<2|g>>4);64!=h&&(c+=String.fromCharCode(g<<4&240|h>>2),64!=k&&(c+=String.fromCharCode(h<<6&192|k)))}};var tg;function ug(a,b){if(!a||b===A.location.hostname)return!1;for(var c=0;c<a.length;c++)if(a[c]instanceof RegExp){if(a[c].test(b))return!0}else if(0<=b.indexOf(a[c]))return!0;return!1}
var yg=function(){var a=vg,b=wg,c=xg(),d=function(h){a(h.target||h.srcElement||{})},e=function(h){b(h.target||h.srcElement||{})};if(!c.init){Ta(A,"mousedown",d);Ta(A,"keyup",d);Ta(A,"submit",e);var g=HTMLFormElement.prototype.submit;HTMLFormElement.prototype.submit=function(){b(this);g.call(this)};c.init=!0}},xg=function(){var a=Ma("google_tag_data",{}),b=a.gl;b&&b.decorators||(b={decorators:[]},a.gl=b);return b};var zg=/(.*?)\*(.*?)\*(.*)/,Ag=/^https?:\/\/([^\/]*?)\.?cdn\.ampproject\.org\/?(.*)/,Bg=/^(?:www\.|m\.|amp\.)+/,Cg=/([^?#]+)(\?[^#]*)?(#.*)?/,Dg=/(.*?)(^|&)_gl=([^&]*)&?(.*)/,Fg=function(a){var b=[],c;for(c in a)if(a.hasOwnProperty(c)){var d=a[c];void 0!==d&&d===d&&null!==d&&"[object Object]"!==d.toString()&&(b.push(c),b.push(rg(String(d))))}var e=b.join("*");return["1",Eg(e),e].join("*")},Eg=function(a,b){var c=[window.navigator.userAgent,(new Date).getTimezoneOffset(),window.navigator.userLanguage||
window.navigator.language,Math.floor((new Date).getTime()/60/1E3)-(void 0===b?0:b),a].join("*"),d;if(!(d=tg)){for(var e=Array(256),g=0;256>g;g++){for(var h=g,k=0;8>k;k++)h=h&1?h>>>1^3988292384:h>>>1;e[g]=h}d=e}tg=d;for(var l=4294967295,m=0;m<c.length;m++)l=l>>>8^tg[(l^c.charCodeAt(m))&255];return((l^-1)>>>0).toString(36)},Hg=function(){return function(a){var b=jb(u.location.href),c=b.search.replace("?",""),d=fb(c,"_gl",!0)||"";a.query=Gg(d)||{};var e=ib(b,"fragment").match(Dg);a.fragment=Gg(e&&e[3]||
"")||{}}},Gg=function(a){var b;b=void 0===b?3:b;try{if(a){var c;a:{for(var d=a,e=0;3>e;++e){var g=zg.exec(d);if(g){c=g;break a}d=decodeURIComponent(d)}c=void 0}var h=c;if(h&&"1"===h[1]){var k=h[3],l;a:{for(var m=h[2],n=0;n<b;++n)if(m===Eg(k,n)){l=!0;break a}l=!1}if(l){for(var q={},t=k?k.split("*"):[],p=0;p<t.length;p+=2)q[t[p]]=sg(t[p+1]);return q}}}}catch(r){}};
function Ig(a,b,c){function d(m){var n=m,q=Dg.exec(n),t=n;if(q){var p=q[2],r=q[4];t=q[1];r&&(t=t+p+r)}m=t;var v=m.charAt(m.length-1);m&&"&"!==v&&(m+="&");return m+l}c=void 0===c?!1:c;var e=Cg.exec(b);if(!e)return"";var g=e[1],h=e[2]||"",k=e[3]||"",l="_gl="+a;c?k="#"+d(k.substring(1)):h="?"+d(h.substring(1));return""+g+h+k}
function Jg(a,b,c){for(var d={},e={},g=xg().decorators,h=0;h<g.length;++h){var k=g[h];(!c||k.forms)&&ug(k.domains,b)&&(k.fragment?Aa(e,k.callback()):Aa(d,k.callback()))}if(Ca(d)){var l=Fg(d);if(c){if(a&&a.action){var m=(a.method||"").toLowerCase();if("get"===m){for(var n=a.childNodes||[],q=!1,t=0;t<n.length;t++){var p=n[t];if("_gl"===p.name){p.setAttribute("value",l);q=!0;break}}if(!q){var r=A.createElement("input");r.setAttribute("type","hidden");r.setAttribute("name","_gl");r.setAttribute("value",
l);a.appendChild(r)}}else if("post"===m){var v=Ig(l,a.action);ab.test(v)&&(a.action=v)}}}else Kg(l,a,!1)}if(!c&&Ca(e)){var w=Fg(e);Kg(w,a,!0)}}function Kg(a,b,c){if(b.href){var d=Ig(a,b.href,void 0===c?!1:c);ab.test(d)&&(b.href=d)}}
var vg=function(a){try{var b;a:{for(var c=a,d=100;c&&0<d;){if(c.href&&c.nodeName.match(/^a(?:rea)?$/i)){b=c;break a}c=c.parentNode;d--}b=null}var e=b;if(e){var g=e.protocol;"http:"!==g&&"https:"!==g||Jg(e,e.hostname,!1)}}catch(h){}},wg=function(a){try{if(a.action){var b=ib(jb(a.action),"host");Jg(a,b,!0)}}catch(c){}},Lg=function(a,b,c,d){yg();var e={callback:a,domains:b,fragment:"fragment"===c,forms:!!d};xg().decorators.push(e)},Mg=function(){var a=A.location.hostname,b=Ag.exec(A.referrer);if(!b)return!1;
var c=b[2],d=b[1],e="";if(c){var g=c.split("/"),h=g[1];e="s"===h?decodeURIComponent(g[2]):decodeURIComponent(h)}else if(d){if(0===d.indexOf("xn--"))return!1;e=d.replace(/-/g,".").replace(/\.\./g,"-")}return a.replace(Bg,"")===e.replace(Bg,"")},Ng=function(a,b){return!1===a?!1:a||b||Mg()};var Og={};var Pg=/^\w+$/,Qg=/^[\w-]+$/,Rg=/^~?[\w-]+$/,Sg={aw:"_aw",dc:"_dc",gf:"_gf",ha:"_ha"};function Tg(a){return a&&"string"==typeof a&&a.match(Pg)?a:"_gcl"}var Vg=function(){var a=jb(u.location.href),b=ib(a,"query",!1,void 0,"gclid"),c=ib(a,"query",!1,void 0,"gclsrc"),d=ib(a,"query",!1,void 0,"dclid");if(!b||!c){var e=a.hash.replace("#","");b=b||fb(e,"gclid",void 0);c=c||fb(e,"gclsrc",void 0)}return Ug(b,c,d)};
function Ug(a,b,c){var d={},e=function(g,h){d[h]||(d[h]=[]);d[h].push(g)};if(void 0!==a&&a.match(Qg))switch(b){case void 0:e(a,"aw");break;case "aw.ds":e(a,"aw");e(a,"dc");break;case "ds":e(a,"dc");break;case "3p.ds":(void 0==Og.gtm_3pds?0:Og.gtm_3pds)&&e(a,"dc");break;case "gf":e(a,"gf");break;case "ha":e(a,"ha")}c&&e(c,"dc");return d}
function Wg(a,b,c){function d(q,t){var p=Xg(q,e);p&&rb(p,t,h,g,l,!0)}b=b||{};var e=Tg(b.prefix),g=b.domain||"auto",h=b.path||"/",k=void 0==b.Td?7776E3:b.Td;c=c||xa();var l=0==k?void 0:new Date(c+1E3*k),m=Math.round(c/1E3),n=function(q){return["GCL",m,q].join(".")};a.aw&&(!0===b.vh?d("aw",n("~"+a.aw[0])):d("aw",n(a.aw[0])));a.dc&&d("dc",n(a.dc[0]));a.gf&&d("gf",n(a.gf[0]));a.ha&&d("ha",n(a.ha[0]))}
var Xg=function(a,b){var c=Sg[a];if(void 0!==c)return b+c},Yg=function(a){var b=a.split(".");return 3!==b.length||"GCL"!==b[0]?0:1E3*(Number(b[1])||0)};function Zg(a){var b=a.split(".");if(3==b.length&&"GCL"==b[0]&&b[1])return b[2]}
var $g=function(a,b,c,d,e){if(la(b)){var g=Tg(e);Lg(function(){for(var h={},k=0;k<a.length;++k){var l=Xg(a[k],g);if(l){var m=kb(l,A.cookie);m.length&&(h[l]=m.sort()[m.length-1])}}return h},b,c,d)}},ah=function(a){return a.filter(function(b){return Rg.test(b)})},bh=function(a){for(var b=["aw","dc"],c=Tg(a&&a.prefix),d={},e=0;e<b.length;e++)Sg[b[e]]&&(d[b[e]]=Sg[b[e]]);sa(d,function(g,h){var k=kb(c+h,A.cookie);if(k.length){var l=k[0],m=Yg(l),n={};n[g]=[Zg(l)];Wg(n,a,m)}})};var ch=/^\d+\.fls\.doubleclick\.net$/;function dh(a){var b=jb(u.location.href),c=ib(b,"host",!1);if(c&&c.match(ch)){var d=ib(b,"path").split(a+"=");if(1<d.length)return d[1].split(";")[0].split("?")[0]}}
function fh(a,b){if("aw"==a||"dc"==a){var c=dh("gcl"+a);if(c)return c.split(".")}var d=Tg(b);if("_gcl"==d){var e;e=Vg()[a]||[];if(0<e.length)return e}var g=Xg(a,d),h;if(g){var k=[];if(A.cookie){var l=kb(g,A.cookie);if(l&&0!=l.length){for(var m=0;m<l.length;m++){var n=Zg(l[m]);n&&-1===ma(k,n)&&k.push(n)}h=ah(k)}else h=k}else h=k}else h=[];return h}
var gh=function(){var a=dh("gac");if(a)return decodeURIComponent(a);var b=mg(),c=[];sa(b,function(d,e){for(var g=[],h=0;h<e.length;h++)g.push(e[h].Lf);g=ah(g);g.length&&c.push(d+":"+g.join(","))});return c.join(";")},hh=function(a,b,c,d,e){lg(b,c,d,e);var g=hg[ig(b)],h=Vg().dc||[],k=!1;if(g&&0<h.length){var l=yc.joined_au=yc.joined_au||{},m=b||"_gcl";if(!l[m])for(var n=0;n<h.length;n++){var q="https://adservice.google.com/ddm/regclk",t=q=q+"?gclid="+h[n]+"&auiddc="+g;Ka.sendBeacon&&Ka.sendBeacon(t)||Sa(t);k=l[m]=
!0}}null==a&&(a=k);if(a&&g){var p=ig(b),r=hg[p];r&&kg(p,r,c,d,e)}};var ih;if(3===xc.xb.length)ih="g";else{var jh="G";jh="g";ih=jh}
var kh={"":"n",UA:"u",AW:"a",DC:"d",G:"e",GF:"f",HA:"h",GTM:ih,OPT:"o"},lh=function(a){var b=xc.i.split("-"),c=b[0].toUpperCase(),d=kh[c]||"i",e=a&&"GTM"===c?b[1]:"OPT"===c?b[1]:"",g;if(3===xc.xb.length){var h=void 0;h=h||(ye()?"s":"o");g="2"+(h||"w")}else g=
"";return g+d+xc.xb+e};
var mh=function(a){return!(void 0===a||null===a||0===(a+"").length)},nh=function(a,b){var c;if(2===b.M)return a("ord",oa(1E11,1E13)),!0;if(3===b.M)return a("ord","1"),a("num",oa(1E11,1E13)),!0;if(4===b.M)return mh(b.sessionId)&&a("ord",b.sessionId),!0;if(5===b.M)c="1";else if(6===b.M)c=b.Oc;else return!1;mh(c)&&a("qty",c);mh(b.Bb)&&a("cost",b.Bb);mh(b.transactionId)&&a("ord",b.transactionId);return!0},oh=encodeURIComponent,ph=function(a,b){function c(n,q,t){g.hasOwnProperty(n)||(q+="",e+=";"+n+"="+
(t?q:oh(q)))}var d=a.uc,e=a.protocol;e+=a.Lb?"//"+d+".fls.doubleclick.net/activityi":"//ad.doubleclick.net/activity";e+=";src="+oh(d)+(";type="+oh(a.wc))+(";cat="+oh(a.Pa));var g=a.Bf||{};sa(g,function(n,q){e+=";"+oh(n)+"="+oh(q+"")});if(nh(c,a)){mh(a.Qb)&&c("u",a.Qb);mh(a.Pb)&&c("tran",a.Pb);c("gtm",lh());!1===a.Ze&&c("npa","1");if(a.qc){var h=fh("dc",a.xa);h&&h.length&&c("gcldc",h.join("."));var k=fh("aw",a.xa);k&&k.length&&c("gclaw",k.join("."));var l=gh();l&&c("gac",l);lg(a.xa,void 0,a.xf,a.yf);
var m=hg[ig(a.xa)];m&&c("auiddc",m)}mh(a.Kc)&&c("prd",a.Kc,!0);sa(a.Vc,function(n,q){c(n,q)});e+=b||"";mh(a.Jb)&&c("~oref",a.Jb);a.Lb?Ra(e+"?",a.J):Sa(e+"?",a.J,a.O)}else D(a.O)};var qh=["input","select","textarea"],rh=["button","hidden","image","reset","submit"],sh=function(a){var b=a.tagName.toLowerCase();return!na(qh,function(c){return c===b})||"input"===b&&na(rh,function(c){return c===a.type.toLowerCase()})?!1:!0},th=function(a){return a.form?a.form.tagName?a.form:A.getElementById(a.form):Za(a,["form"],100)},uh=function(a,b,c){if(!a.elements)return 0;for(var d=b.getAttribute(c),e=0,g=1;e<a.elements.length;e++){var h=a.elements[e];if(sh(h)){if(h.getAttribute(c)===d)return g;
g++}}return 0};var wh=function(a){var b="/pagead/conversion/"+vh(a.conversion_id)+"/?",c=vh(JSON.stringify(a.conversion_data)),d="https://www.googletraveladservices.com/travel/flights/clk"+b+"conversion_data="+c;if(a.conversionLinkerEnabled){var e=fh("gf",a.cookiePrefix);if(e&&e.length)for(var g=0;g<e.length;g++)d+="&gclgf="+vh(e[g])}Sa(d,a.onSuccess,a.onFailure)},vh=function(a){return null===a||void 0===a||0===String(a).length?"":encodeURIComponent(String(a))};
var xh=!!u.MutationObserver,yh=void 0,zh=function(a){if(!yh){var b=function(){var c=A.body;if(c)if(xh)(new MutationObserver(function(){for(var e=0;e<yh.length;e++)D(yh[e])})).observe(c,{childList:!0,subtree:!0});else{var d=!1;Ta(c,"DOMNodeInserted",function(){d||(d=!0,D(function(){d=!1;for(var e=0;e<yh.length;e++)D(yh[e])}))})}};yh=[];A.body?b():D(b)}yh.push(a)};var ai=u.clearTimeout,bi=u.setTimeout,K=function(a,b,c){if(ye()){b&&D(b)}else return Pa(a,b,c)},ci=function(){return new Date},di=function(){return u.location.href},ei=function(a){return ib(jb(a),"fragment")},fi=function(a){return hb(jb(a))},gi=null;
var hi=function(a,b){return md(a,b||2)},ii=function(a,b,c){b&&(a.eventCallback=b,c&&(a.eventTimeout=c));return rf(a)},ji=function(a,b){u[a]=b},L=function(a,b,c){b&&(void 0===u[a]||c&&!u[a])&&(u[a]=b);return u[a]},ki=function(a,b,c){return kb(a,b,void 0===c?!0:!!c)},li=function(a,b,c,d){var e={prefix:a,path:b,domain:c,Td:d},g=Vg();Wg(g,e);bh(e)},mi=function(a,b,c,d,e){var g=Hg(),h=xg();h.data||(h.data={query:{},fragment:{}},g(h.data));var k={},l=h.data;l&&
(Aa(k,l.query),Aa(k,l.fragment));for(var m=Tg(b),n=0;n<a.length;++n){var q=a[n];if(void 0!==Sg[q]){var t=Xg(q,m),p=k[t];if(p){var r=Math.min(Yg(p),xa()),v;b:{for(var w=r,y=kb(t,A.cookie),x=0;x<y.length;++x)if(Yg(y[x])>w){v=!0;break b}v=!1}v||rb(t,p,c,d,0==e?void 0:new Date(r+1E3*(null==e?7776E3:e)),!0)}}}var z={prefix:b,path:c,domain:d};Wg(Ug(k.gclid,k.gclsrc),z);},ni=function(a,b,c,d,e){$g(a,b,c,d,e);},
oi=function(a,b){if(ye()){b&&D(b)}else Ra(a,b)},pi=function(a){return!!ag(a,"init",!1)},qi=function(a){Zf(a,"init",!0)},ri=function(a,b,c){var d=(void 0===c?0:c)?"www.googletagmanager.com/gtag/js":Dc;d+="?id="+encodeURIComponent(a)+"&l=dataLayer";b&&sa(b,function(e,g){g&&(d+="&"+e+"="+encodeURIComponent(g))});K(G("https://","http://",d))},si=function(a,b){var c=a[b];return c};
var ti=function(a,b,c,d,e,g){var h={config:a,gtm:lh()};c&&(lg(d,void 0,e,g),h.auiddc=hg[ig(d)]);b&&(h.loadInsecure=b);L("__dc_ns_processor",[]).push(h);K((b?"http":"https")+"://www.googletagmanager.com/dclk/ns/v1.js")};
var ui=Uf.eg;var vi=new qa,wi=function(a,b){function c(h){var k=jb(h),l=ib(k,"protocol"),m=ib(k,"host",!0),n=ib(k,"port"),q=ib(k,"path").toLowerCase().replace(/\/$/,"");if(void 0===l||"http"==l&&"80"==n||"https"==l&&"443"==n)l="web",n="default";return[l,m,n,q]}for(var d=c(String(a)),e=c(String(b)),g=0;g<d.length;g++)if(d[g]!==e[g])return!1;return!0},xi=function(a){var b=a.arg0,c=a.arg1;if(a.any_of&&la(c)){for(var d=0;d<c.length;d++)if(xi({"function":a["function"],arg0:b,arg1:c[d]}))return!0;return!1}switch(a["function"]){case "_cn":return 0<=
String(b).indexOf(String(c));case "_css":var e;a:{if(b){var g=["matches","webkitMatchesSelector","mozMatchesSelector","msMatchesSelector","oMatchesSelector"];try{for(var h=0;h<g.length;h++)if(b[g[h]]){e=b[g[h]](c);break a}}catch(v){}}e=!1}return e;case "_ew":var k,l;k=String(b);l=String(c);var m=k.length-l.length;return 0<=m&&k.indexOf(l,m)==m;case "_eq":return String(b)==String(c);case "_ge":return Number(b)>=Number(c);case "_gt":return Number(b)>Number(c);case "_lc":var n;n=String(b).split(",");
return 0<=ma(n,String(c));case "_le":return Number(b)<=Number(c);case "_lt":return Number(b)<Number(c);case "_re":var q;var t=a.ignore_case?"i":void 0;try{var p=String(c)+t,r=vi.get(p);r||(r=new RegExp(c,t),vi.set(p,r));q=r.test(b)}catch(v){q=!1}return q;case "_sw":return 0==String(b).indexOf(String(c));case "_um":return wi(b,c)}return!1};var zi=function(a,b){var c=function(){};c.prototype=a.prototype;var d=new c;a.apply(d,Array.prototype.slice.call(arguments,1));return d};var Ai={},Bi=encodeURI,Y=encodeURIComponent,Ci=Sa;var Di=function(a,b){if(!a)return!1;var c=ib(jb(a),"host");if(!c)return!1;for(var d=0;b&&d<b.length;d++){var e=b[d]&&b[d].toLowerCase();if(e){var g=c.length-e.length;0<g&&"."!=e.charAt(0)&&(g--,e="."+e);if(0<=g&&c.indexOf(e,g)==g)return!0}}return!1};
var Ei=function(a,b,c){for(var d={},e=!1,g=0;a&&g<a.length;g++)a[g]&&a[g].hasOwnProperty(b)&&a[g].hasOwnProperty(c)&&(d[a[g][b]]=a[g][c],e=!0);return e?d:null};Ai.bg=function(){var a=!1;return a};var Fi=function(){var a=!1;return a};var ej=function(){var a=u.gaGlobal=u.gaGlobal||{};a.hid=a.hid||oa();return a.hid};var wj=function(a,b,c,d){this.n=a;this.t=b;this.p=c;this.d=d},xj=function(){this.c=1;this.e=[];this.p2=this.p=null};function yj(a){var b=yc,c=b.gss=b.gss||{};return c[a]=c[a]||new xj}
var zj=function(a){if(yj(a).p&&!yj(a).p2){var b=yj(a).p;yj(a).p2=function(c,d,e){b(c,d,e.eventModel)}}return yj(a).p2},Aj=function(a,b){yj(a).p2=b;yj(a).p=function(c,d,e){return b(c,d,new xe(e))}},Bj=function(a){var b=yj(a),c=zj(a);if(c){var d=b.e,e=[];b.e=[];var g=function(h){for(var k=0;k<h.length;k++)try{var l=h[k];l.d?(l.d=!1,e.push(l)):c(l.n,l.t,new xe(l.p))}catch(m){}};g(d);g(e)}};var Mj=window,Nj=document,Oj=function(a){var b=Mj._gaUserPrefs;if(b&&b.ioo&&b.ioo()||a&&!0===Mj["ga-disable-"+a])return!0;try{var c=Mj.external;if(c&&c._gaUserPrefs&&"oo"==c._gaUserPrefs)return!0}catch(g){}for(var d=kb("AMP_TOKEN",Nj.cookie,!0),e=0;e<d.length;e++)if("$OPT_OUT"==d[e])return!0;return Nj.getElementById("__gaOptOutExtension")?!0:!1};var Tj=!1;
var Vj=function(a,b,c){if(Tj)ze().push("event",[c,b],a,void 0);else{Uj(a);var d=Math.floor(xa()/1E3);yj(a).e.push(new wj(b,d,c,void 0));Bj(a)}},Wj=function(a,b,c){if(Tj)ze().push("event",[c,b],a,!0);else{Uj(a);var d=Math.floor(xa()/1E3);yj(a).e.push(new wj(b,d,c,!0))}},Uj=function(a){if(1===yj(a).c&&(yj(a).c=2,!ye())){var b=encodeURIComponent(a);Pa(("http:"!=u.location.protocol?"https:":"http:")+("//www.googletagmanager.com/gtag/js?id="+b+"&l=dataLayer&cx=c"))}},Yj=function(a,b){},Xj=function(a,b){},Zj=function(a){return"_"===a.charAt(0)},ak=function(a){sa(a,function(c){Zj(c)&&
delete a[c]});var b=a[H.sb]||{};sa(b,function(c){Zj(c)&&delete b[c]})};var Z={a:{}};

Z.a.gtagha=["google"],function(){function a(h){function k(m,n){void 0!==n&&l.push(m+"="+n)}if(void 0===h)return"";var l=[];k("hct_base_price",h.Ld);k("hct_booking_xref",h.Md);k("hct_checkin_date",h.Rf);k("hct_checkout_date",h.Sf);k("hct_currency_code",h.Tf);k("hct_partner_hotel_id",h.Nd);k("hct_total_price",h.Od);return l.join(";")}function b(h,k,l,m){var n=Y(h),q=Y(a(k)),t="https://www.googletraveladservices.com/travel/clk/pagead/conversion/"+n+"/?data="+q;l&&(t+=fh("ha",m).map(function(p){return"&gclha="+
Y(p)}).join(""));return t}function c(h,k,l,m,n,q){/^\d+$/.test(h)?Ci(b(h,k,l,m),n,q):D(q)}function d(h,k,l,m){var n={};ja(h)?n.Md=h:"number"===typeof h&&(n.Md=String(h));ja(l)&&(n.Tf=l);ja(k)?n.Od=n.Ld=k:"number"===typeof k&&(n.Od=n.Ld=String(k));if(!la(m)||0==m.length)return n;var q=m[0];if(!Ia(q))return n;ja(q.id)?n.Nd=q.id:"number"===typeof q.id&&(n.Nd=String(q.id));ja(q.start_date)&&(n.Rf=q.start_date);ja(q.end_date)&&(n.Sf=q.end_date);return n}function e(h){var k=Gc,l=h.vtp_gtmOnSuccess,m=h.vtp_gtmOnFailure,
n=h.vtp_conversionId,q=n.containerId,t=function(z){return od(z,q,n.id)},p=!1!==t(H.Ia),r=t(H.Ha)||t(H.H),v=t(H.N),w=t(H.W);if(k===H.R){var y=t(H.Ka)||{};p&&(Ng(y[H.lb],!!y[H.I])&&mi(g,r,void 0,v,w),li(r,void 0,v,w));y[H.I]&&ni(g,y[H.I],y[H.nb],!!y[H.mb],r);D(l)}else if("purchase"===k){var x=d(t(H.Ma),t(H.fa),t(H.ra),t(H.V));c(n.ja[0],x,p,r,l,m)}else D(m)}var g=["ha"];Z.__gtagha=e;Z.__gtagha.b="gtagha";Z.__gtagha.g=!0;Z.__gtagha.priorityOverride=0;}();
Z.a.e=["google"],function(){(function(a){Z.__e=a;Z.__e.b="e";Z.__e.g=!0;Z.__e.priorityOverride=0})(function(a){return String(vd(a.vtp_gtmEventId,"event"))})}();


Z.a.v=["google"],function(){(function(a){Z.__v=a;Z.__v.b="v";Z.__v.g=!0;Z.__v.priorityOverride=0})(function(a){var b=a.vtp_name;if(!b||!b.replace)return!1;var c=hi(b.replace(/\\\./g,"."),a.vtp_dataLayerVersion||1);return void 0!==c?c:a.vtp_defaultValue})}();





Z.a.gtagaw=["google"],function(){var a=!1,b=[],c=["aw","dc"],d=function(m){var n=L("google_trackConversion"),q=m.gtm_onFailure;"function"==typeof n?n(m)||q():q()},e=function(){for(;0<b.length;)d(b.shift())},g=function(){a||(a=!0,Td(),K(G("https://","http://","www.googleadservices.com/pagead/conversion_async.js"),function(){e();b={push:d}},function(){e();a=!1}))},h=function(m,n,q,t){if(ye()){}else{la(n)||(n=[n]);for(var p=
0;p<n.length;p++)1>p&&Nc(m.ja[0],m.ja[1],n[p],{me:q,Qg:t})}},k=function(m){if(m){for(var n=[],q=0;q<m.length;++q){var t=m[q];t&&n.push({item_id:t.id,quantity:t.quantity,value:t.price,start_date:t.start_date,end_date:t.end_date})}return n}},l=function(m){var n=m.vtp_conversionId,q=Gc,t=q==H.R,p=n.ja[0],r=n.ja[1],v=void 0!==r,w=n.containerId,y=v?n.id:void 0,x=function(X){return od(X,w,y)},z=!1!==x(H.Ia),C=x(H.Ha)||x(H.H),B=x(H.N),E=x(H.W);if(t){var F=x(H.Ka)||{};z&&(Ng(F[H.lb],!!F[H.I])&&mi(c,C,void 0,
B,E),li(C,void 0,B,E));F[H.I]&&ni(c,F[H.I],F[H.nb],!!F[H.mb],C);if(v){var P=x(H.bc),U=x(H.$b),R=x(H.ac),T=x(H.qd);h(n,P,U||R,T)}}var O=!1===x(H.ed)||!1===x(H.La);if(!t||!v&&!O)if(!0===x(H.fd)&&(v=!1),!1!==x(H.U)||v){var M={google_conversion_id:p,google_remarketing_only:!v,onload_callback:m.vtp_gtmOnSuccess,gtm_onFailure:m.vtp_gtmOnFailure,google_conversion_format:"3",google_conversion_color:"ffffff",google_conversion_domain:"",google_conversion_label:r,google_conversion_language:x(H.Ja),google_conversion_value:x(H.fa),
google_conversion_currency:x(H.ra),google_conversion_order_id:x(H.Ma),google_user_id:x(H.X),google_conversion_page_url:x(H.ob),google_conversion_referrer_url:x(H.pb),google_gtm:lh()};ye()&&(M.opt_image_generator=function(){return new Image},M.google_enable_display_cookie_match=!1);!1===x(H.U)&&(M.google_allow_ad_personalization_signals=!1);M.google_read_gcl_cookie_opt_out=!z;z&&C&&(M.google_gcl_cookie_prefix=C);var I=function(){var X=x(H.ib),W={event:q};if(la(X)){for(var ea=0;ea<X.length;++ea){var V=
X[ea],N=x(V);void 0!==N&&(W[V]=N)}return W}var aa=x("eventModel");if(!aa)return null;f(aa,W);for(var pa=0;pa<H.Zc.length;++pa)delete W[H.Zc[pa]];return W}();I&&(M.google_custom_params=I);!v&&x(H.V)&&(M.google_gtag_event_data={items:x(H.V),value:x(H.fa)});if(v&&"purchase"==q){M.google_conversion_merchant_id=x(H.kd);M.google_basket_feed_country=x(H.hd);M.google_basket_feed_language=x(H.jd);M.google_basket_discount=x(H.gd);M.google_basket_transaction_type=q;M.google_disable_merchant_reported_conversions=
!0===x(H.md);ye()&&(M.google_disable_merchant_reported_conversions=!0);var J=k(x(H.V));J&&(M.google_conversion_items=J)}var Q=function(X,W){void 0!=W&&""!==W&&(M.google_additional_conversion_params=M.google_additional_conversion_params||{},M.google_additional_conversion_params[X]=W)};v&&("boolean"==typeof x(H.Zb)&&Q("vdnc",x(H.Zb)),Q("vdltv",x(H.ld)));var S=!0;
S&&b.push(M)}g()};Z.__gtagaw=l;Z.__gtagaw.b="gtagaw";Z.__gtagaw.g=!0;Z.__gtagaw.priorityOverride=0}();


Z.a.get=["google"],function(){function a(e,g){var h=od(H.ib,e,void 0);if(la(h))for(var k=0;k<h.length;k++){var l=h[k],m=od(l,e,void 0);void 0!==m&&(g[l]=m)}else{var n=hi("eventModel");f(n,g)}}function b(e,g){for(var h=H.rd,k=0;k<h.length;k++){var l=od(h[k],e,void 0);void 0!==l&&(g[h[k]]=l)}}var c=!0;var d=function(e){if(e.vtp_isAutoTag){var g=String(e.vtp_trackingId),h=Gc||"";if(Zj(h))return;var k={};
c?(b(g,k),a(g,k),ak(k),Vj(g,h,f(k))):h===H.R?(b(g,k),ze().push("config",[k],g)):(a(g,k),ak(k),Vj(g,h,k))}else{var l=e.vtp_settings,m=l.eventParameters,n=l.userProperties;f(Ei(e.vtp_eventParameters,"name","value"),m);f(Ei(e.vtp_userProperties,"name","value"),n);m[H.sb]=n;var q=String(e.vtp_eventName),t=e.vtp_allowSystemNames;if(!t&&Zj(q))return;t||ak(m);(e.vtp_deferrable?Wj:Vj)(String(l.streamId),q,m)}e.vtp_gtmOnSuccess()};Z.__get=d;Z.__get.b="get";Z.__get.g=!0;Z.__get.priorityOverride=0;}();


Z.a.gtagfl=[],function(){function a(e){var g=/^DC-(\d+)(\/([\w-]+)\/([\w-]+)\+(\w+))?$/.exec(e);if(g){var h={standard:2,unique:3,per_session:4,transactions:5,items_sold:6,"":1}[(g[5]||"").toLowerCase()];if(h)return{containerId:"DC-"+g[1],ca:g[3]?e:"",Te:g[1],Se:g[3]||"",Pa:g[4]||"",M:h}}}function b(e,g){function h(t,p,r){void 0!==r&&0!==(r+"").length&&k.push(t+p+":"+e(r+""))}var k=[],l=g(H.V)||[];if(la(l))for(var m=0;m<l.length;m++){var n=l[m],q=m+1;h("i",q,n.id);h("p",q,n.price);h("q",q,n.quantity);
h("c",q,g(H.ue));h("l",q,g(H.Ja))}return k.join("|")}function c(e,g,h){var k=/^u([1-9]\d?|100)$/,l=e(H.ve)||{},m=sd(g,h),n={},q={};if(Ia(l))for(var t in l)if(l.hasOwnProperty(t)&&k.test(t)){var p=l[t];ja(p)&&(n[t]=p)}for(var r=0;r<m.length;r++){var v=m[r];k.test(v)&&(n[v]=v)}for(var w in n)n.hasOwnProperty(w)&&(q[w]=e(n[w]));return q}var d=["aw","dc"];(function(e){Z.__gtagfl=e;Z.__gtagfl.b="gtagfl";Z.__gtagfl.g=!0;Z.__gtagfl.priorityOverride=0})(function(e){var g=e.vtp_gtmOnSuccess,h=e.vtp_gtmOnFailure,
k=a(e.vtp_targetId);if(k){var l=function(R){return od(R,k.containerId,k.ca||void 0)},m=!1!==l(H.Ia),n=l(H.Ha)||l(H.H),q=l(H.N),t=l(H.W),p=l(H.xe),r=3===Lc();if(Gc===H.R){var v=l(H.Ka)||{},w=l(H.te),y=void 0===w?!0:!!w;m&&(Ng(v[H.lb],!!v[H.I])&&mi(d,n,void 0,q,t),li(n,void 0,q,t),hh(y,n,void 0,q,t));v[H.I]&&ni(d,v[H.I],v[H.nb],!!v[H.mb],n);p&&p.exclusion_parameters&&p.engines&&ti(p,r,m,n,q,t);D(g)}else{var x={},z=l(H.we);if(Ia(z))for(var C in z)if(z.hasOwnProperty(C)){var B=z[C];void 0!==B&&null!==
B&&(x[C]=B)}var E="";if(5===k.M||6===k.M)E=b(Y,l);var F=c(l,k.containerId,k.ca),P=!0===l(H.oe);if(ye()&&P){P=!1}var U={Pa:k.Pa,qc:m,xf:q,yf:t,xa:n,Bb:l(H.fa),M:k.M,Bf:x,uc:k.Te,wc:k.Se,O:h,J:g,Jb:fi(di()),Kc:E,protocol:r?"http:":"https:",Oc:l(H.He),Lb:P,sessionId:l(H.rb),Pb:void 0,transactionId:l(H.Ma),Qb:void 0,Vc:F,Ze:!1!==l(H.U)};ph(U)}}else D(h)})}();


Z.a.gtaggf=["google"],function(){var a=/.*\.google\.com(:\d+)?\/booking\/flights.*/,b=function(c){if(c){for(var d=[],e=0,g=0;g<c.length;++g){var h=c[g];!h||void 0!==h.category&&""!==h.category&&"FlightSegment"!==h.category||(d[e]={cabin:h.travel_class,fare_product:h.fare_product,booking_code:h.booking_code,flight_number:h.flight_number,origin:h.origin,destination:h.destination,departure_date:h.start_date},e++)}return d}};(function(c){Z.__gtaggf=c;Z.__gtaggf.b="gtaggf";Z.__gtaggf.g=!0;Z.__gtaggf.priorityOverride=
0})(function(c){var d=Gc,e=c.vtp_gtmOnSuccess,g=c.vtp_gtmOnFailure,h=c.vtp_conversionId,k=h.ja[0],l=h.containerId,m=function(x){return od(x,l,h.id)},n=!1!==m(H.Ia),q=m(H.Ha)||m(H.H),t=m(H.N),p=m(H.W);if(d===H.R)n&&li(q,void 0,t,p),D(e);else{var r={conversion_id:k,onFailure:g,onSuccess:e,conversionLinkerEnabled:n,cookiePrefix:q};if("purchase"===d){var v=a.test(di()),w={partner_id:k,trip_type:m(H.Ke),total_price:m(H.fa),currency:m(H.ra),is_direct_booking:v,flight_segment:b(m(H.V))},y=m(H.Ge);y&&"object"===
typeof y&&(w.passengers_total=y.total,w.passengers_adult=y.adult,w.passengers_child=y.child,w.passengers_infant_in_seat=y.infant_in_seat,w.passengers_infant_in_lap=y.infant_in_lap);r.conversion_data=w}wh(r)}})}();




Z.a.gtagua=["google"],function(){var a,b={client_id:1,client_storage:"storage",cookie_name:1,cookie_domain:1,cookie_expires:1,cookie_path:1,cookie_update:1,sample_rate:1,site_speed_sample_rate:1,use_amp_client_id:1,store_gac:1,conversion_linker:"storeGac"},c={anonymize_ip:1,app_id:1,app_installer_id:1,app_name:1,app_version:1,campaign:{name:"campaignName",source:"campaignSource",medium:"campaignMedium",term:"campaignTerm",content:"campaignContent",id:"campaignId"},currency:"currencyCode",description:"exDescription",
fatal:"exFatal",language:1,non_interaction:1,page_hostname:"hostname",page_referrer:"referrer",page_path:"page",page_location:"location",page_title:"title",screen_name:1,transport_type:"transport",user_id:1},d={content_id:1,event_category:1,event_action:1,event_label:1,link_attribution:1,linker:1,method:1,name:1,send_page_view:1,value:1},e={cookie_name:1,cookie_expires:"duration",levels:1},g={anonymize_ip:1,fatal:1,non_interaction:1,use_amp_client_id:1,send_page_view:1,store_gac:1,conversion_linker:1},
h=function(r,v,w,y){if(void 0!==w)if(g[v]&&(w=ua(w)),"anonymize_ip"!=v||w||(w=void 0),1===r)y[k(v)]=w;else if(ja(r))y[r]=w;else for(var x in r)r.hasOwnProperty(x)&&void 0!==w[x]&&(y[r[x]]=w[x])},k=function(r){return r&&ja(r)?r.replace(/(_[a-z])/g,function(v){return v[1].toUpperCase()}):r},l=function(r,v,w){r.hasOwnProperty(v)||(r[v]=w)},m=function(r,v,w){var y={},x={},z={},C;var B=rd(H.De,r);if(la(B)){for(var E=[],F=0;F<B.length;F++){var P=B[F];if(void 0!=P){var U=P.id,R=P.variant;void 0!=U&&void 0!=
R&&E.push(String(U)+"."+String(R))}}C=0<E.length?E.join("!"):void 0}else C=void 0;var T=C;T&&l(x,"exp",T);var O=rd("custom_map",r);if(Ia(O))for(var M in O)if(O.hasOwnProperty(M)&&/^(dimension|metric)\d+$/.test(M)&&void 0!=O[M]){var I=rd(String(O[M]),r);void 0!==I&&l(x,M,I)}for(var J=sd(r),Q=0;Q<J.length;++Q){var S=J[Q],X=rd(S,r);d.hasOwnProperty(S)?h(d[S],S,X,y):c.hasOwnProperty(S)?h(c[S],S,X,x):b.hasOwnProperty(S)?h(b[S],S,X,z):/^(dimension|metric|content_group)\d+$/.test(S)?h(1,S,X,x):S===H.H&&
0>ma(J,H.hb)&&(z.cookieName=X+"_ga")}var W=String(Gc);l(z,"cookieDomain","auto");l(x,"forceSSL",!0);var ea="general";0<=ma("add_payment_info add_to_cart add_to_wishlist begin_checkout checkout_progress purchase refund remove_from_cart set_checkout_option".split(" "),W)?ea="ecommerce":0<=ma("generate_lead login search select_content share sign_up view_item view_item_list view_promotion view_search_results".split(" "),W)?ea="engagement":"exception"==W&&(ea="error");l(y,"eventCategory",ea);0<=ma(["view_item",
"view_item_list","view_promotion","view_search_results"],W)&&l(x,"nonInteraction",!0);"login"==W||"sign_up"==W||"share"==W?l(y,"eventLabel",rd(H.Ee,r)):"search"==W||"view_search_results"==W?l(y,"eventLabel",rd(H.Ie,r)):"select_content"==W&&l(y,"eventLabel",rd(H.se,r));var V=y[H.Ka]||{},N=V[H.lb];N||0!=N&&V[H.I]?z.allowLinker=!0:!1===N&&l(z,"useAmpClientId",!1);if(!1===rd(H.pe,r)||!1===rd(H.U,r))x.allowAdFeatures=!1;z.name=v;x["&gtm"]=lh(!0);x.hitCallback=w;y.aa=x;y.sc=z;return y},n=function(r){function v(I){var J=
f(I);J.list=I.list_name;J.listPosition=I.list_position;J.position=I.list_position||I.creative_slot;J.creative=I.creative_name;return J}function w(I){for(var J=[],Q=0;I&&Q<I.length;Q++)I[Q]&&J.push(v(I[Q]));return J.length?J:void 0}function y(I){return{id:z(x.Ma),affiliation:z(x.ye),revenue:z(x.fa),tax:z(x.Ce),shipping:z(x.Be),coupon:z(x.ze),list:z(x.Tb)||I}}for(var x=H,z=function(I){return od(I,r,void 0)},C=z(x.V),B,E=0;C&&E<C.length&&!(B=C[E][x.Tb]);E++);var F=z("custom_map");if(Ia(F))for(var P=
0;C&&P<C.length;++P){var U=C[P],R;for(R in F)F.hasOwnProperty(R)&&/^(dimension|metric)\d+$/.test(R)&&void 0!=F[R]&&l(U,R,U[F[R]])}var T=null,O=Gc,M=z(x.Ae);"purchase"==O||"refund"==O?T={action:O,Oa:y(),Da:w(C)}:"add_to_cart"==O?T={action:"add",Da:w(C)}:"remove_from_cart"==O?T={action:"remove",Da:w(C)}:"view_item"==O?T={action:"detail",Oa:y(B),Da:w(C)}:"view_item_list"==O?T={action:"impressions",Wf:w(C)}:"view_promotion"==O?T={action:"promo_view",Lc:w(M)}:"select_content"==O&&M&&0<M.length?T={action:"promo_click",
Lc:w(M)}:"select_content"==O?T={action:"click",Oa:{list:z(x.Tb)||B},Da:w(C)}:"begin_checkout"==O||"checkout_progress"==O?T={action:"checkout",Da:w(C),Oa:{step:"begin_checkout"==O?1:z(x.od),option:z(x.nd)}}:"set_checkout_option"==O&&(T={action:"checkout_option",Oa:{step:z(x.od),option:z(x.nd)}});T&&(T.ah=z(x.ra));return T},q={},t=function(r,v){var w=q[r];q[r]=f(v);if(!w)return!1;for(var y in v)if(v.hasOwnProperty(y)&&v[y]!==w[y])return!0;for(var x in w)if(w.hasOwnProperty(x)&&w[x]!==v[x])return!0;
return!1},p=function(r){var v=r.vtp_trackingId,w="https://www.google-analytics.com/analytics.js",y=$d();if(ia(y)){var x="gtag_"+v.split("-").join("_"),z=function(O){var M=[].slice.call(arguments,0);M[0]=x+"."+M[0];y.apply(window,M)},C=function(){var O=function(Q,S){for(var X=0;S&&X<S.length;X++)z(Q,S[X])},M=n(v);if(M){var I=M.action;if("impressions"==I)O("ec:addImpression",M.Wf);else if("promo_click"==I||"promo_view"==I){var J=M.Lc;O("ec:addPromo",M.Lc);J&&0<J.length&&"promo_click"==I&&z("ec:setAction",
I)}else O("ec:addProduct",M.Da),z("ec:setAction",I,M.Oa)}},B=function(){if(ye()){}else{var O=rd(H.Fe,v);O&&(z("require",O,{dataLayer:"dataLayer"}),z("require","render"))}},E=function(){if(ye()){}else{var O=rd(H.bc,v),M=rd(H.ac,v),I=rd(H.$b,v),J;J=la(O)?O:[O];for(var Q=0;Q<J.length;Q++)5>
Q&&ee(v,J[Q],{Hd:I||M});}},F=m(v,x,r.vtp_gtmOnSuccess);(function(){})();t(x,F.sc)&&y(function(){Yd()&&Yd().remove(x)});y("create",v,F.sc);(function(){var O=rd("custom_map",v);y(function(){if(Ia(O)){var M=F.aa,I=Yd().getByName(x),J;for(J in O)if(O.hasOwnProperty(J)&&/^(dimension|metric)\d+$/.test(J)&&void 0!=O[J]){var Q=I.get(k(O[J]));
l(M,J,Q)}}})})();(function(O){if(O){var M={};if(Ia(O))for(var I in e)e.hasOwnProperty(I)&&h(e[I],I,O[I],M);z("require","linkid",M)}})(F.linkAttribution);var P=F[H.Ka];if(P&&P[H.I]){var U=P[H.nb];ae(x+".",P[H.I],void 0===U?!!P.use_anchor:"fragment"===U,!!P[H.mb])}var R=function(O,M,I){I&&(M=""+M);F.aa[O]=M},T=Gc;T==H.Sb?(B(),z("send","pageview",F.aa)):T==H.R?(B(),E(),0!=F.sendPageView&&z("send","pageview",F.aa)):"screen_view"==T?z("send","screenview",F.aa):"timing_complete"==T?(R("timingCategory",
F.eventCategory,!0),R("timingVar",F.name,!0),R("timingValue",ta(F.value)),void 0!==F.eventLabel&&R("timingLabel",F.eventLabel,!0),z("send","timing",F.aa)):"exception"==T?z("send","exception",F.aa):"optimize.callback"!=T&&(0<=ma("view_item_list select_content view_item add_to_cart remove_from_cart begin_checkout set_checkout_option purchase refund view_promotion checkout_progress".split(" "),T)&&(z("require","ec","ec.js"),C()),R("eventCategory",F.eventCategory,!0),R("eventAction",F.eventAction||T,
!0),void 0!==F.eventLabel&&R("eventLabel",F.eventLabel,!0),void 0!==F.value&&R("eventValue",ta(F.value)),z("send","event",F.aa));a||(a=!0,Td(),K(w,function(){Yd().loaded||r.vtp_gtmOnFailure()},r.vtp_gtmOnFailure))}else D(r.vtp_gtmOnFailure)};Z.__gtagua=p;Z.__gtagua.b="gtagua";Z.__gtagua.g=!0;Z.__gtagua.priorityOverride=0}();

var bk={};bk.macro=function(a){if(Uf.hc.hasOwnProperty(a))return Uf.hc[a]},bk.onHtmlSuccess=Uf.Bd(!0),bk.onHtmlFailure=Uf.Bd(!1);bk.dataLayer=nd;bk.callback=function(a){Ic.hasOwnProperty(a)&&ia(Ic[a])&&Ic[a]();delete Ic[a]};bk.jf=function(){yc[xc.i]=bk;Aa(Jc,Z.a);Xb=Xb||Uf;Yb=Cd};
bk.Xf=function(){Og.gtm_3pds=!0;yc=u.google_tag_manager=u.google_tag_manager||{};if(yc[xc.i]){var a=yc.zones;a&&a.unregisterChild(xc.i)}else{for(var b=data.resource||{},c=b.macros||[],d=0;d<c.length;d++)Qb.push(c[d]);for(var e=b.tags||[],g=0;g<e.length;g++)Tb.push(e[g]);for(var h=b.predicates||[],
k=0;k<h.length;k++)Sb.push(h[k]);for(var l=b.rules||[],m=0;m<l.length;m++){for(var n=l[m],q={},t=0;t<n.length;t++)q[n[t][0]]=Array.prototype.slice.call(n[t],1);Rb.push(q)}Vb=Z;Wb=xi;bk.jf();xf();Fd=!1;Gd=0;if("interactive"==A.readyState&&!A.createEventObject||"complete"==A.readyState)Id();else{Ta(A,"DOMContentLoaded",Id);Ta(A,"readystatechange",Id);if(A.createEventObject&&A.documentElement.doScroll){var p=!0;try{p=!u.frameElement}catch(y){}p&&Jd()}Ta(u,"load",Id)}lf=!1;"complete"===A.readyState?nf():
Ta(u,"load",nf);a:{if(!cd)break a;u.setInterval(dd,864E5);}
Fc=(new Date).getTime();}};(0,bk.Xf)();

})()
