var q="function"==typeof Object.create?Object.create:function(d){function f(){}f.prototype=d;return new f},v;if("function"==typeof Object.setPrototypeOf)v=Object.setPrototypeOf;else{var z;a:{var A={Ya:!0},B={};try{B.__proto__=A;z=B.Ya;break a}catch(d){}z=!1}v=z?function(d,f){d.__proto__=f;if(d.__proto__!==f)throw new TypeError(d+" is not extensible");return d}:null}var H=v;
function I(d,f){d.prototype=q(f.prototype);d.prototype.constructor=d;if(H)H(d,f);else for(var b in f)if("prototype"!=b)if(Object.defineProperties){var a=Object.getOwnPropertyDescriptor(f,b);a&&Object.defineProperty(d,b,a)}else d[b]=f[b];d.Lb=f.prototype}var J="function"==typeof Object.defineProperties?Object.defineProperty:function(d,f,b){d!=Array.prototype&&d!=Object.prototype&&(d[f]=b.value)},K="undefined"!=typeof window&&window===this?this:"undefined"!=typeof global&&null!=global?global:this;
function L(){L=function(){};K.Symbol||(K.Symbol=M)}var M=function(){var d=0;return function(f){return"jscomp_symbol_"+(f||"")+d++}}();function N(){L();var d=K.Symbol.iterator;d||(d=K.Symbol.iterator=K.Symbol("iterator"));"function"!=typeof Array.prototype[d]&&J(Array.prototype,d,{configurable:!0,writable:!0,value:function(){return R(this)}});N=function(){}}function R(d){var f=0;return S(function(){return f<d.length?{done:!1,value:d[f++]}:{done:!0}})}
function S(d){N();d={next:d};d[K.Symbol.iterator]=function(){return this};return d}function T(d){N();L();N();var f=d[Symbol.iterator];return f?f.call(d):R(d)}function U(d){for(var f,b=[];!(f=d.next()).done;)b.push(f.value);return b}function V(d){if(d){for(var f=K,b=["Array","prototype","find"],a=0;a<b.length-1;a++){var c=b[a];c in f||(f[c]={});f=f[c]}b=b[b.length-1];a=f[b];d=d(a);d!=a&&null!=d&&J(f,b,{configurable:!0,writable:!0,value:d})}}
V(function(d){return d?d:function(d,b){a:{var a=this;a instanceof String&&(a=String(a));for(var c=a.length,e=0;e<c;e++){var g=a[e];if(d.call(b,g,e,a)){d=g;break a}}d=void 0}return d}});
(function(){function d(f,b,a){function c(g,h){if(!b[g]){if(!f[g]){var n="function"==typeof require&&require;if(!h&&n)return n(g,!0);if(e)return e(g,!0);h=Error("Cannot find module '"+g+"'");throw h.code="MODULE_NOT_FOUND",h;}h=b[g]={i:{}};f[g][0].call(h.i,function(a){return c(f[g][1][a]||a)},h,h.i,d,f,b,a)}return b[g].i}for(var e="function"==typeof require&&require,g=0;g<a.length;g++)c(a[g]);return c}return d})()({1:[function(d,f){f.i={config:{executeImmediately:!1},contentFunction:function(b,a,c){b.settings.iv=
"vet";a.postbidFactory.create(b,a,c).B()}}},{}],2:[function(d,f){d=d(3);f.i=d},{3:3}],3:[function(d,f){function b(a){this.window=a;this.document=this.window.document;this.s=0;this.a={before:this.l.bind(this),after:this.g.bind(this),append:this.b.bind(this),prepend:this.u.bind(this)}}b.prototype.B=function(a,c,e,b){var g=c.settings||{},d=this.ca(g.selector||"body"),f=null,r=e.adSizeService.Ea(g);g.width=r.width;g.height=r.height;if(!b.executeImmediately){if(!d)return;f=this.f(g,d,c)}a(c,e,f)};b.prototype.f=
function(a,c,e){var b=a.method||"append",d=this.m(a.width,a.height,a.customCSS||{});this.o(c,d,b);"onetag-vet-content"===e.type&&this.j(a.height,c);return d};b.prototype.m=function(a,c,e){var b=this.document.createElement("div");b.setAttribute("class","sovrn-onetag-ad");b.setAttribute("id","onetag-wrapper-"+this.s++);b.style.width=a+"px";b.style.height=c+"px";b.style.margin="0 auto";this.c(e,b);return b};b.prototype.o=function(a,c,e){this.a[e](a,c)};b.prototype.j=function(a,c){a=(c.getBoundingClientRect().height-
a)/2;c.style.paddingTop=a+"px";c.style.paddingBottom=a+"px"};b.prototype.ca=function(a){try{var c=this.document.querySelector(a)}catch(e){this.window.console.log("Sovrn OneTag Error:",e.message)}return c};b.prototype.c=function(a,c){Object.keys(a).forEach(function(e){c.style[e]=a[e]})};b.prototype.u=function(a,c){a.insertBefore(c,a.firstChild)};b.prototype.b=function(a,c){a.appendChild(c)};b.prototype.l=function(a,c){a.parentNode.insertBefore(c,a)};b.prototype.g=function(a,c){a.parentNode.insertBefore(c,
a.nextSibling)};f.i=b},{}],4:[function(d,f){var b=d(6),a=d(10),c=d(13),e=d(5),g=d(11),n=d(12);f.i=function(d,f){var h=d.window,l=new e(h,d.httpClient,d.config),w=new a(h);h=new c(h,l,d);if(f)return f=new n(d,h,w),new b(d,f);f=new g(d,h,w);return new b(d,f)}},{10:10,11:11,12:12,13:13,5:5,6:6}],5:[function(d,f){function b(a,c,e){this.window=a;this.c=c;this.b=e;this.a=null}b.prototype.get=function(a){var c=this;this.a?a(this.a):this.c.get(this.b.cookieEndpoint+this.window.location.origin,function(e){c.a=
e.ljt_reader;a(c.a)},!0)};f.i=b},{}],6:[function(d,f){function b(a,c){this.b=a.engagementMonitor;this.l=a.httpClient;this.j=a.config;this.window=a.window;this.c=this.g=!0;this.a=c}b.prototype.start=function(a,c){this.a.start(a,c);this.b.start();this.b.ga("user_active",this.u.bind(this));this.b.ga("user_inactive",this.v.bind(this));this.window.addEventListener("unload",this.f.bind(this,!0));this.a.Na(this.f.bind(this,!1));this.A()};b.prototype.A=function(){this.window.setInterval(this.s.bind(this),
1E3)};b.prototype.s=function(){this.a.Ra(this.g)};b.prototype.ta=function(a,c){var e=this.m(this.window.document.querySelector(a));this.o(a,c,e)&&this.a.da(a,c,e)};b.prototype.o=function(a,c,e){var b=this;return e?!0:(setTimeout(function(){b.ta(a,c)},1E3),!1)};b.prototype.m=function(a){a=a.getElementsByTagName("iframe");for(var c=0;c<a.length;c++){var e=a[c].getBoundingClientRect();if(e.width&&e.height)return e}};b.prototype.u=function(){this.c=this.g=!0};b.prototype.v=function(){this.g=!1;this.c&&
this.f(!1);this.c=!1};b.prototype.f=function(a){var c=this,e=this.a.Fa();this.a.G();this.a.getMetadata(function(b){c.l.yb(c.j.beaconEndpoint,{metadata:b,payloads:e},a)})};f.i=b},{}],7:[function(d,f){function b(a,c){this.window=a;this.D=c.D;this.F=c.F;this.type="LIGHT";this.b=0;this.a=1}b.prototype.ba=function(){return{type:this.type,selector:this.F,contentId:this.D,refreshes:this.b,impressions:this.a}};b.prototype.va=function(){this.b+=1;this.a+=1};b.prototype.G=function(){this.a=this.b=0};f.i=b},
{}],8:[function(d,f){function b(a){this.window=a;this.type="PAGE";this.c=this.b=this.a=0;this.f=null}b.prototype.ba=function(){return{type:this.type,dwellTime:this.a,engagedDwellTime:this.b,scrollDepth:this.c,cmpMetrics:this.f}};b.prototype.ua=function(){this.b+=1};b.prototype.wa=function(){this.a+=1;this.c=Math.max(this.c,this.window.pageYOffset)};b.prototype.G=function(){this.b=this.a=0};b.prototype.Fb=function(a){this.f=a};f.i=b},{}],9:[function(d,f){function b(a,c){this.F=c.F;this.D=c.D;this.R=
c.R;this.window=a;this.type="PLACEMENT";this.f=this.c=0;this.a=1;this.g=this.b=0}b.prototype.ba=function(){var a=this.j();return{type:this.type,secondsInView:this.f,viewableEngagedTime:this.c,dimensions:a,aboveTheFold:this.l(a),refreshes:this.b,impressions:this.a,selector:this.F,contentId:this.D,dwellTime:this.g}};b.prototype.j=function(){return{top:this.R.top+this.window.scrollY,left:this.R.left+this.window.scrollX,height:this.R.height,width:this.R.width}};b.prototype.ua=function(a){a&&(this.c+=
1)};b.prototype.wa=function(a){a&&(this.f+=1);this.g+=1};b.prototype.G=function(){this.b=this.a=this.f=this.c=0};b.prototype.va=function(){this.b+=1;this.a+=1};b.prototype.l=function(a){return 0<=this.window.innerHeight-(a.height/2+a.top)};f.i=b},{}],10:[function(d,f){function b(b){this.window=b;this.a={Placement:e,Page:c,Light:a}}var a=d(7),c=d(8),e=d(9);b.prototype.create=function(a,c){return new this.a[a](this.window,c)};f.i=b},{7:7,8:8,9:9}],11:[function(d,f){function b(a,c,e){this.window=a.window;
this.l=a.viewability;this.m=a.viewableEngagedTime;this.j=a.consentProvider;this.a={};this.c=c;this.f=e;this.b=this.f.create("Page");this.containerId=null;this.g=function(){}}b.prototype.start=function(a,c){this.containerId=a;c&&this.c.za()};b.prototype.da=function(a,c,e){var b=this.a[a];b&&(b.Mb=null);this.s(b,c)&&this.g();this.v(b,c)?b.metrics.va():this.o(a,c,e)};b.prototype.o=function(a,c,e){var b=this.window.document.querySelector(a);e=this.f.create("Placement",{F:a,D:c,R:e});this.a[a]={selector:a,
element:b,contentId:c,metrics:e}};b.prototype.s=function(a,c){return a&&a.contentId!==c};b.prototype.v=function(a,c){return a&&a.contentId===c};b.prototype.Na=function(a){this.g=a};b.prototype.Ra=function(a){a&&this.b.ua();this.b.wa();this.A(a)};b.prototype.A=function(a){for(var c in this.a)if(this.a.hasOwnProperty(c)){var e=this.a[c],b=e.metrics;e=this.l.qa(this.m.Ca(e));a&&b.ua(e);b.wa(e)}};b.prototype.G=function(){for(var a in this.a)this.a.hasOwnProperty(a)&&this.a[a].metrics.G();this.b.G()};
b.prototype.Fa=function(){var a=this;this.j.Ha(function(c){c&&a.b.Fb(a.u(c))});var c=[this.b.ba()],e;for(e in this.a)this.a.hasOwnProperty(e)&&c.push(this.a[e].metrics.ba());return c};b.prototype.getMetadata=function(a){return this.c.get(this.containerId,function(c){return a(c)})};b.prototype.u=function(a){var c=a.vendorConsents,e=Object.keys(c),b=e.reduce(function(a,e){c[e]&&a++;return a},0);return{consentString:a.metadata,cmpId:a.cmpId,globalCookie:a.hasGlobalScope,numberOfVendors:e.length,numberOfConsentedVendors:b}};
f.i=b},{}],12:[function(d,f){function b(a,c,e){this.b=c;this.f=e;this.a={};this.c=function(){}}b.prototype.start=function(a){this.containerId=a;this.b.za()};b.prototype.da=function(a,c){var e=this.a[a];!e||this.j(e,c)?this.g(a,c):e.metrics.va();this.c()};b.prototype.g=function(a,c){var e=this.f.create("Light",{F:a,D:c});this.a[a]={selector:a,contentId:c,metrics:e}};b.prototype.j=function(a,c){return a&&a.contentId!==c};b.prototype.Na=function(a){this.c=a};b.prototype.G=function(){for(var a in this.a)this.a.hasOwnProperty(a)&&
this.a[a].metrics.G()};b.prototype.Fa=function(){var a=[],c;for(c in this.a)this.a.hasOwnProperty(c)&&a.push(this.a[c].metrics.ba());return a};b.prototype.getMetadata=function(a){return this.b.get(this.containerId,function(c){return a({pageViewSalt:c.pageViewSalt,url:c.url,containerId:c.containerId})})};b.prototype.Ra=function(){};f.i=b},{}],13:[function(d,f){function b(a,c,e){this.window=a;this.s=this.l();this.j=c;this.f=!0;this.b=e.geoLocationService;this.g=e.consentProvider;this.a=e.config}b.prototype.get=
function(a,c){var e=this;this.ia(function(b){var g={pageViewSalt:e.s,screenWidth:e.window.screen.width,screenHeight:e.window.screen.height,documentHeight:e.m(),url:e.window.location.href,containerId:a,ljtReader:"",location:b};if(!e.f)return c(g);e.o(function(a){g.ljtReader=a;return c(g)})})};b.prototype.o=function(a){var c=this;this.b.Ka(this.a.noTrackingGeoGroup,function(e,b){return e?a(""):b?c.g.tb(c.a.sovrnVendorId,function(e){return e?c.c(a):a("")}):c.c(a)})};b.prototype.c=function(a){return this.j.get(a)};
b.prototype.ia=function(a){this.b.ia(a)};b.prototype.l=function(){return+new Date+Math.floor(1E3*Math.random())};b.prototype.m=function(){var a=this.window.document.body,c=this.window.document.documentElement;return Math.max(a.scrollHeight,a.offsetHeight,c.clientHeight,c.scrollHeight,c.offsetHeight)};b.prototype.za=function(){this.f=!1};f.i=b},{}],14:[function(d,f){var b=d(15),a=d(17),c=d(18);f.i=function(e,g){var d=new a(e);g=new c(e,g);return new b(d,g,e)}},{15:15,17:17,18:18}],15:[function(d,f){function b(a,
c,e){this.b=a;this.g=c;this.a={};this.f=[];this.j=[];this.c=[];this.window=e;this.m=!1}b.prototype.start=function(){this.m||(this.m=!0,this.b.Pa(this.o.bind(this)),this.b.start(),this.g.Pa(this.o.bind(this)),this.g.start(),this.f.push(this.b),this.f.push(this.g),this.j.push(this.b),this.c.push(this.g),this.c.push(this.b))};b.prototype.ga=function(a,c){"undefined"===typeof this.a[a]&&(this.a[a]=[]);this.a[a].push(c)};b.prototype.o=function(a,c,e){this.l(a,{name:a});c&&this.s()?(a="user_active",this.l(a,
{name:a}),this.v()):!c&&this.u(e.id)&&(a="user_inactive",this.l(a,{name:a}))};b.prototype.v=function(){for(var a=this.f.length;a--;)this.f[a].reset()};b.prototype.s=function(){for(var a=this.j.length;a--;)if(!this.j[a].P)return!1;return!0};b.prototype.u=function(a){for(var c=this.c.length;c--;)if(this.c[c].id===a)return!0;return!1};b.prototype.l=function(a,c){if(this.a[a])for(var e=this.a[a].length;e--;)this.a[a][e](c)};f.i=b},{}],16:[function(d,f){function b(a){this.id=a;this.P=!0;this.a=null}b.prototype.Pa=
function(a){this.a=a};b.prototype.ea=function(a,c){this.a(this.id+"_"+a,c,this)};b.prototype.$=function(a,c,e){function b(a){e(a)}a.addEventListener?a.addEventListener(c,b.bind(this),!1):a.attachEvent("on"+c,b.bind(this))};b.prototype.reset=function(){this.P=!0};f.i=b},{}],17:[function(d,f){function b(c){var e=a.call(this,"focus")||this;e.window=c;return e}var a=d(16);I(b,a);b.prototype.start=function(){this.$(this.window,"focus",this.Ba.bind(this));this.$(this.window,"focusin",this.Ba.bind(this));
this.$(this.window,"blur",this.Aa.bind(this));this.$(this.window,"focusout",this.Aa.bind(this))};b.prototype.Ba=function(){this.P=!0;this.ea("active",!0)};b.prototype.Aa=function(){if(this.window.document.hasFocus())return this.ea("active",!0);this.ea("inactive",!1)};f.i=b},{16:16}],18:[function(d,f){function b(c,e){var b=a.call(this,"input")||this;b.Ia=!1;b.Gb=e||10;b.Qa="mousemove mousedown scroll keyup keypress keydown touchstart touchmove touchend".split(" ");b.window=c;return b}var a=d(16);I(b,
a);b.prototype.start=function(){for(var a=0;a<this.Qa.length;a++)this.$(this.window,this.Qa[a],this.pa.bind(this));this.Ia||(this.Ia=!0,this.pa())};b.prototype.pa=function(){this.P||this.ea("active",!0);clearTimeout(this.Hb);this.Hb=setTimeout(this.pb.bind(this),1E3*this.Gb);this.P=!0};b.prototype.pb=function(){this.P&&this.ea("inactive",!1);this.P=!1};b.prototype.reset=function(){a.prototype.reset.call(this);this.pa()};f.i=b},{16:16}],19:[function(d,f){var b=d(20),a=d(21);f.i=function(c,e){c=new a(c,
e);return new b(c)}},{20:20,21:21}],20:[function(d,f){function b(a){this.f=a}b.prototype.qb=function(a,c){if(this.a(a))c(!0);else{a=this.l(a);var e=this.j(a);c=this.o.bind(this,e,c);for(var b in a)a.hasOwnProperty(b)&&this.b(a[b],c)}};b.prototype.b=function(a,c){var e=this,b={results:[],aa:0};a.forEach(function(g,d){d=e.m.bind(e,d,a,b,c);e.f.create(g).Kb(d)})};b.prototype.m=function(a,c,e,b,d){var g=this;e.results[a]=d;e.aa++;if(e.aa===c.length){var f=this.g(c);e.results.forEach(function(a,b){f=g.c(f,
a,c[b].settings.rule)});return b(f)}};b.prototype.o=function(a,c,b){a.results.push(b);a.aa++;if(a.aa===a.ub)return a=a.results.every(function(a){return a}),c(a)};b.prototype.a=function(a){return!a||0===a.length};b.prototype.g=function(a){return"EXCLUDE"===a[0].settings.rule};b.prototype.c=function(a,c,b){return"EXCLUDE"===b?a&&!c:a||c};b.prototype.l=function(a){var c={};a.forEach(function(a){c[a.type]||(c[a.type]=[]);c[a.type].push(a)});return c};b.prototype.j=function(a){return{results:[],ub:Object.keys(a).length,
aa:0}};f.i=b},{}],21:[function(d,f){function b(a,c){this.a=a;this.b=c}b.prototype.create=function(a){return new this.b[a.type+"@"+a.revision](this.a,a.settings)};f.i=b},{}],22:[function(d,f){d=d(23);f.i=d},{23:23}],23:[function(d,f){function b(){this.a=new a}var a=d(24);b.prototype.yb=function(a,b,g){var c=this.a.create();c.open("POST",a,g?!1:!0);c.setRequestHeader("Content-Type","application/json");c.send(JSON.stringify(b))};b.prototype.get=function(a,b,g){var c=this.a.create();c.onreadystatechange=
function(){if(4===c.readyState){try{var a=JSON.parse(c.responseText)}catch(l){a={}}b(a)}};c.open("GET",a,!0);c.withCredentials=!!g;c.send()};f.i=b},{24:24}],24:[function(d,f){function b(){}b.prototype.create=function(){return new XMLHttpRequest};f.i=b},{}],25:[function(d,f){d=d(26);f.i=d},{26:26}],26:[function(d,f){function b(a,c,b){this.f=c.adRenderingService;this.A=c.adSizeService;this.window=c.window;this.o=c.bidderParamsParser;this.ma=c.config.prebidUrl;this.H=c.geoLocationService;this.a=a.settings;
this.c=this.A.Ea(this.a);this.b=this.f.ya(this.c.width,this.c.height);this.J=this.V();this.j="sovrn-postbid"+this.c.width+"x"+this.c.height;this.Wa=this.O();this.m=this.N();this.ka=this.o.xb(this.a.bidders,this.a.iv);this.Jb=this.a.revShareAdjustments;this.placeholder=b;this.C=this.a.cmpTimeout||1E4;this.L=this.a.allowAuctionWithoutConsent||!0;this.S=this.a.gdprMode||!1}b.prototype.B=function(a){this.g=void 0===a?function(){}:a;this.placeholder.appendChild(this.b);this.eb();this.cb();this.Za()};b.prototype.Za=
function(){var a=this;this.la=this.window.setInterval(function(){if(a.Y()){a.window.clearInterval(a.la);var c=a.b.contentWindow.pbjs;a.Ta(c);a.Xa(c)}},1E3)};b.prototype.Ta=function(a){var c=this;this.a.currencyModule&&a.que.push(function(){a.setConfig({currency:{adServerCurrency:c.a.adServerCurrency||"USD"}})})};b.prototype.Xa=function(a){var c=this;this.H.Ka("EU",function(b,g){if(c.S&&(g||b))return a.que.push(function(){a.setConfig({consentManagement:{cmpApi:"iab",timeout:c.C,allowAuctionWithoutConsent:c.L}});
c.v(a)});c.v(a)})};b.prototype.v=function(a){var c=this;a.que.push(function(){c.a.revShareAdjustments&&c.o.$a(a,c.a.revShareAdjustments);c.K(a);c.X(a)})};b.prototype.K=function(a){a.addAdUnits([{code:this.j,bids:this.ka,mediaTypes:{banner:{sizes:this.J}}}])};b.prototype.X=function(a){a.requestBids({timeout:1E3,bidsBackHandler:this.M.bind(this,a)})};b.prototype.M=function(a){this.l=this.a.passbackHtml;var c=a.getAdserverTargetingForAdUnitCode(this.j);if(c&&c.hb_adid)return this.Va(a,c);if(this.l)return this.Ua();
this.f.Oa(this.a,this.placeholder,this.g);return this.s()};b.prototype.Ua=function(){var a=this.m,c=a.contentWindow.document;if(this.a.isSafeFrame)return this.u(this.l);a.width=this.c.width;a.height=this.c.height;c.write(this.l);c.close();this.g(this.b,this.c)};b.prototype.Va=function(a,c){var b=this.m.contentWindow.document;if(this.a.isSafeFrame)return this.u(this.W(a,c.hb_adid));a.renderAd(b,c.hb_adid);return this.g(this.b,this.U(c.hb_size))};b.prototype.U=function(a){a=a.split("x");return{width:Number(a[0]),
height:Number(a[1])}};b.prototype.u=function(a){var c=this.I(this.a);c.adCode=a;this.f.Oa(c,this.placeholder,this.g);return this.s()};b.prototype.W=function(a,c){a=a.getBidResponses()[this.j].bids.find(function(a){return a.adId===c});return a.ad?a.ad:a.adUrl?this.T(a):""};b.prototype.T=function(a){var c={frameborder:0,scrolling:"no",marginheight:0,marginwidth:0,topmargin:0,leftmargin:0,width:0,height:0,allowTransparency:!0};c.width=a.width;c.height=a.height;c.src=a.adUrl;a="<iframe";for(var b=Object.getOwnPropertyNames(c),
g=0;g<b.length;g++)a+=" "+b[g]+'="'+c[b[g]]+'"';return a+"></iframe>"};b.prototype.Y=function(){return this.b.contentWindow?!!this.b.contentWindow.pbjs:!1};b.prototype.N=function(){for(var a=this.window.document.createElement("iframe"),c={frameborder:0,scrolling:"no",marginheight:0,marginwidth:0,topmargin:0,leftmargin:0,width:0,height:0,allowTransparency:!0,id:"postbid_if"},b=Object.getOwnPropertyNames(c),g=0;g<b.length;g++)a.setAttribute(b[g],c[b[g]]);return a};b.prototype.s=function(){this.b.parentNode.removeChild(this.b)};
b.prototype.cb=function(){this.b.contentDocument.body.appendChild(this.m)};b.prototype.O=function(){var a=this.window.document.createElement("script");a.setAttribute("src",this.ma);a.setAttribute("async","");a.setAttribute("type","text/javascript");return a};b.prototype.eb=function(){var a=this.f.Da(this.b);a.open();a.close();a.body.appendChild(this.Wa)};b.prototype.V=function(){var a=this.a.sizes;return a?a.map(function(a){a=a.split("x");return[Number(a[0]),Number(a[1])]}):[[this.a.width,this.a.height]]};
b.prototype.I=function(a){return JSON.parse(JSON.stringify(a))};f.i=b},{}],27:[function(d,f){d=d(28);f.i=d},{28:28}],28:[function(d,f){function b(a,c){this.b=c;this.window=a}b.prototype.qa=function(a){if("SAFEFRAME"===this.window.state)return this.window.$sf.ext.inViewPercentage()/100>=this.b;a=a.getBoundingClientRect();return this.f(a,this.window.innerWidth)*this.c(a,this.window.innerHeight)/(a.width*a.height)>=this.b};b.prototype.f=function(a,c){return this.a(a.right,c)-this.a(a.left,c)};b.prototype.c=
function(a,c){return this.a(a.bottom,c)-this.a(a.top,c)};b.prototype.a=function(a,c){return Math.max(0,Math.min(a,c))};f.i=b},{}],29:[function(d,f){function b(a,c,b){this.window=a;this.b=b;this.protocol=this.window.location.protocol;this.A=c;this.a={};this.f=null}b.prototype.Oa=function(a,c,b){b=void 0===b?function(){}:b;if(a.isSafeFrame)this.s(a,c,b);else{var e=this.ya(a.width,a.height);c.appendChild(e);var d=this.Da(e);d.open();d.write(this.c(a));setTimeout(function(){d.close();return b(e)},0)}};
b.prototype.ya=function(a,c){var b=this.window.document.createElement("iframe");b.width=a+"px";b.height=c+"px";b.setAttribute("frameBorder","0");b.setAttribute("scrolling","no");b.setAttribute("marginwidth","0");b.setAttribute("marginheight","0");return b};b.prototype.s=function(a,c,b){var e=this;this.A.get(function(g){e.v(g,{width:a.width,height:a.height,adCode:a.adCode||e.c(a)},c,b)})};b.prototype.v=function(a,c,b,g){var e=b.id+"-safe-frame",d=this.window.document.createElement("div");d.setAttribute("id",
e);b.appendChild(d);this.a[e]={placeholder:b,wb:g};this.f||this.g(a);b=new a.PosConfig({id:e,dest:e,w:c.width,h:c.height});a.render(new a.Position(e,c.adCode,null,b));this.l(e)};b.prototype.g=function(a){this.f=new a.Config({auto:!1,renderFile:this.b.safeFrameUrls.html,onEndPosRender:this.u.bind(this)})};b.prototype.l=function(a){var c=this.a[a];c.Ja=0;c.Ma=setInterval(this.m.bind(this,a,c),500)};b.prototype.m=function(a,c){if(c){if(a=this.window.document.getElementById(a))a.dispatchEvent(this.j()),
a.style.display="block",a.style.visibility="inherit";c.Ja++;10<c.Ja&&clearInterval(c.Ma)}};b.prototype.j=function(){if("function"===typeof this.window.Event)return new this.window.Event("load");var a=this.window.document.createEvent("CustomEvent");a.initCustomEvent("load",!1,!1,void 0);return a};b.prototype.c=function(a){return'<script src="'+this.o(a)+'">\x3c/script>'};b.prototype.u=function(a){var c=this.a[a],b=c.placeholder.querySelector("#"+a);clearInterval(c.Ma);c.wb(b);delete this.a[a]};b.prototype.o=
function(a){var c=a.iv;a=this.protocol+this.b.adRenderUrl+a.zoneId+"&width="+a.width+"&height="+a.height;c&&(a=a+"&iv="+c);return a};b.prototype.Da=function(a){return a.contentDocument||a.contentWindow&&a.contentWindow.document||a.document};f.i=b},{}],30:[function(d,f){function b(a,c){this.window=a;this.a=null;this.b=c.unescape.bind(c)}var a=d(32),c=d(31);b.prototype.hb=function(){return this.a?this.a:this.window.googletag?this.a=new a(this.window.pbjs,this.window.googletag,this.b):this.window.apntag?
this.a=new c(this.window.pbjs,this.window.apntag,this.b):null};f.i=b},{31:31,32:32}],31:[function(d,f){function b(a,c,b){this.c=a;this.a=c;this.b=b}b.prototype.Sa=function(a){a=this.b(a);var c=this.f(a);this.a.modifyTag(a,{keywords:c});this.c.setTargetingForAst()};b.prototype.f=function(a){var c={};a=this.a.requests.tags[a].keywords;for(var b=Object.keys(a),g=0;g<b.length;g++)"hb_"!==b[g].substring(0,3).toLowerCase()&&(c[b[g]]=a[b[g]]);return c};b.prototype.reload=function(a){this.a.refresh(this.b(a))};
f.i=b},{}],32:[function(d,f){function b(a,c,b){this.c=a;this.b=c;this.a=b}b.prototype.Sa=function(a){this.c.setTargetingForGPTAsync([this.a(a)])};b.prototype.g=function(a){for(var c=this.b.pubads().getSlots(),b=0;b<c.length;b++)if(a===c[b].getSlotElementId())return c[b]};b.prototype.reload=function(a,c){(a=this.g(this.a(a)))&&c&&this.f(a,c);this.b.pubads().refresh([a])};b.prototype.f=function(a,c){var b=c.reloadCount,g=c.dfpKeyValues;c.enableVetKeyValue&&this.l(a,b);g&&this.j(a,g)};b.prototype.l=
function(a,c){c++;a.setTargeting("sovrn-vet",c)};b.prototype.j=function(a,c){Object.keys(c).forEach(function(b){a.setTargeting(b,c[b])})};f.i=b},{}],33:[function(d,f){function b(){}b.prototype.La=function(a,c){if(a.useNativeReload)return!0;var b=a.sizeTolerance||10;return this.a(a).some(function(a){var e=Math.abs(c.height-a.height)<b;return Math.abs(c.width-a.width)<b&&e})};b.prototype.oa=function(a){return(a=this.ha(a,"iframe")||this.ha(a,"img"))?a.getBoundingClientRect():{width:0,height:0}};b.prototype.Ea=
function(a){return a.sizes?this.a(a).reduce(function(a,b){return a.width*a.height<b.width*b.height?b:a},{width:0,height:0}):{width:a.width,height:a.height}};b.prototype.a=function(a){var c=a.sizes;return c?c.map(function(a){a=a.split("x");return{width:Number(a[0]),height:Number(a[1])}}):[{height:a.height,width:a.width}]};b.prototype.ha=function(a,c){a=a.getElementsByTagName(c);for(c=0;c<a.length;c++){var b=a[c].getBoundingClientRect();if(b.width&&b.height)return a[c]}};f.i=b},{}],34:[function(d,f){function b(){}
b.prototype.$a=function(a,c){Object.keys(c).forEach(function(b){a.bidderSettings[b]={bidCpmAdjustment:function(a){return a*Number(c[b])}}})};b.prototype.xb=function(a,c){var b=this,g=[];Object.keys(a).forEach(function(e){g=g.concat(b.a(e,a,c))});return g};b.prototype.a=function(a,c,b){var e=this;return c[a].map(function(c){return{bidder:a,params:e.b(a,c,b)}})};b.prototype.b=function(a,c,b){b&&"sovrn"===a&&(c.iv=b);return c};f.i=b},{}],35:[function(d,f){function b(a){this.window=a}b.prototype.Ha=function(a,
c){return this.a(void 0===c?null:c,a)};b.prototype.tb=function(a,c){return this.Ha(function(b){return b.vendorConsents?c(b.vendorConsents[a]):c(b)},[a])};b.prototype.a=function(a,c){function b(a){b.a||(b.a=!0,c(a),clearTimeout(d))}var g=this.window.__cmp;if(!g||"function"!==typeof g)return c(!1);var d=null;d=setTimeout(function(){b(!1)},2E3);g("ping",null,function(a){a.cmpLoaded||b(!1)});g("getVendorConsents",a,function(c){if(c)return b(c);g("addEventListener","onSubmit",function(){g("getVendorConsents",
a,function(a){return b(a)})})})};f.i=b},{}],36:[function(d,f){function b(){}b.prototype.escape=function(a){this.b(a)&&(a="\\3"+a.charAt(0)+" "+a.slice(1));return a.replace(/\//g,"\\/").replace(/\./g,"\\.")};b.prototype.unescape=function(a){this.a(a)&&(a=a.substr(2),a=a.charAt(0)+a.substr(2));return a.replace(/\\\//g,"/").replace(/\\\./g,".")};b.prototype.b=function(a){return isNaN(Number(parseInt(a.charAt(0))))?!1:!0};b.prototype.a=function(a){return"\\3"===a.substr(0,2)};f.i=b},{}],37:[function(d,
f){function b(a){this.j=a.config;this.window=a.window;this.l=a.httpClient;this.v=a.config.dfpGatewayUrl;this.g=a.adLocator;this.b=null;this.a={}}b.prototype.C=function(a){if(this.b)return this.b;a=a.getAdUnitPath().split("/");for(var c=0;c<a.length;c++){var b=Number(a[c]);if(b)return this.b=b}return 0};b.prototype.K=function(a,c){for(var b=0;b<a.length;b++){var g=this.g.ca(a[b]);if(g&&g.id===c||g&&g.querySelector("#"+c))return!0}return!1};b.prototype.c=function(a,c,b){var e=this;b=void 0===b?0:b;
if(25<=b)c({});else{var d=a.getResponseInformation();d?c(d):setTimeout(function(){e.c(a,c,++b)},200)}};b.prototype.O=function(a,c,b){this.C(a)&&this.u(c)?b(!0):b(!1)};b.prototype.u=function(a){var c=a.ordersToInclude||[],b=a.lineItemTypes||[],d=a.roadblockingType||!1;return(a.ordersToExclude||[]).length||c.length||b.length||d};b.prototype.J=function(a){a=a.lineItemTypes||[];for(var c=0;c<a.length;c++)if("AD_EXCHANGE"===a[c].type||"ADSENSE"===a[c].type)return!0;return!1};b.prototype.H=function(a,c){var b=
this,d=this.m(a);d?c(d):(this.s(a,c),1===this.a[a].length&&this.f(a,function(c){b.a[a].forEach(function(a){a(c)});b.a[a]=[];b.o(a,c)}))};b.prototype.m=function(a){try{var c=JSON.parse(this.window.localStorage.getItem("onetag-"+a));return c.expiresAt>Date.now()?c.lineItemInfo:!1}catch(e){return!1}};b.prototype.o=function(a,c){c={lineItemInfo:c,expiresAt:Date.now()+1E3*this.j.lineItemInfoTtl};try{this.window.localStorage.setItem("onetag-"+a,JSON.stringify(c))}catch(e){}};b.prototype.f=function(a,c){var b=
this;this.l.get(this.v+"/"+this.b+"/"+a,function(e){b.I(e,a,c)})};b.prototype.s=function(a,c){this.a[a]=this.a[a]||[];this.a[a].push(c)};b.prototype.I=function(a,c,b){var e=this;"PENDING"===a.state&&setTimeout(function(){e.f(c,b)},2E3);"READY"===a.state&&b(a)};b.prototype.sb=function(a,c,b){var e=this,d=a.getSlotElementId();this.K(c.selectorsToExclude||[],d)?b(!0):this.O(a,c,function(d){if(!d)return b(!1);e.c(a,function(a){if(!a.lineItemId)return b(e.J(c));e.H(a.lineItemId,function(a){return b(e.A(a,
c))})})})};b.prototype.A=function(a,c){return this.M(a,c)||this.L(a,c)||this.N(a,c)};b.prototype.M=function(a,c){return c.ordersToInclude?-1===c.ordersToInclude.indexOf(a.orderId):-1<(c.ordersToExclude||[]).indexOf(a.orderId)};b.prototype.L=function(a,c){c=c.lineItemTypes||[];for(var b=0;b<c.length;b++){var d="all"===c[b].priority,f=a.priority===Number(c[b].priority);if(a.lineItemType===c[b].type&&(d||f))return!0}return!1};b.prototype.N=function(a,c){return c.roadblockingType?"CREATIVE_SET"===a.roadblockingType:
!1};f.i=b},{}],38:[function(d,f){function b(a,c,b,d){this.window=a;this.f=c;this.j=b;this.g=d;this.b={}}b.prototype.jb=function(a,c){for(var b=Object.keys(this.b),d=0;d<b.length;d++)this.na(a,this.b[b[d]],c)};b.prototype.na=function(a,c,b){var e=this.a(c);this.j.sb(c,a,this.o.bind(this,e,b))};b.prototype.o=function(a,c,b){b||c("#"+a)};b.prototype.lb=function(){for(var a=this.Ga(),c=[],b=0;b<a.length;b++){var d=a[b],f=this.l(d);this.m(f)&&c.push(d)}return c};b.prototype.ob=function(){for(var a=this.c(),
c=0;c<a.length;c++){var b=a[c],d=this.a(b);this.b[d]=b}};b.prototype.zb=function(a){var c=this.a(a);this.b[c]=a};b.prototype.Ga=function(){for(var a=this.c(),c=[],b=0;b<a.length;b++)c.push(this.a(a[b]));return c};b.prototype.c=function(){var a=this.window.googletag.pubads();return a.getSlots?a.getSlots():this.window.googletag.getSlots()};b.prototype.kb=function(a){return this.b[a]||null};b.prototype.l=function(a){return(a=this.window.document.querySelector("#"+a))?this.f.oa(a):{width:0,height:0}};
b.prototype.rb=function(){var a=this.window.googletag;return!!a&&a.pubadsReady};b.prototype.m=function(a){return 50<=a.width&&50<=a.height};b.prototype.bb=function(a){var c=this;this.window.googletag.cmd.push(function(){c.window.googletag.pubads().addEventListener("slotRenderEnded",function(c){a(c.slot)})})};b.prototype.ab=function(a){var c=this;this.window.googletag.cmd.push(function(){c.window.googletag.pubads().addEventListener("impressionViewable",function(b){b=c.a(b.slot);a("#"+b)})})};b.prototype.nb=
function(){var a=this.window.googletag;a.cmd=a.cmd||[]};b.prototype.a=function(a){a=a.getSlotElementId();return this.g.escape(a)};f.i=b},{}],39:[function(d,f){function b(a,c){this.window=a.window;this.c=a.adSizeService;this.f=a;this.g=c;this.a=null}var a=d(38),c=d(37);b.prototype.get=function(b){if(!this.a){var e=new c(this.f);this.a=new a(this.window,this.c,e,this.g)}return this.b(b)};b.prototype.b=function(a){return this.a.rb()?(this.a.nb(),this.a.ob(),a(this.a)):setTimeout(this.b.bind(this,a),
1E3)};f.i=b},{37:37,38:38}],40:[function(d,f){function b(a){this.a=a.config;this.f=a.httpClient;this.window=a.window;this.c=!1;this.b=[]}b.prototype.Ka=function(a,c){var b=this;this.ia(function(e){b.l(a,function(a){return e?0===a.length?c({message:"Grouping not found"},null):c(null,-1<a.indexOf(e)):c({message:"Location not found"},null)})})};b.prototype.ia=function(a){var c=this,b=this.g("onetag-location");b?a(b):(this.b.push(a),this.c||(this.c=!0,this.f.get(this.a.geoLocationUrl,function(a){var b=
a.country;b&&c.j("onetag-location",b);c.b.forEach(function(a){return a(b)});c.b=[];c.c=!1})))};b.prototype.j=function(a,c){c={value:c,expiresAt:Date.now()+1E3*this.a.geoLocationCacheTtl};try{this.window.localStorage.setItem(a,JSON.stringify(c))}catch(e){}};b.prototype.g=function(a){try{var c=JSON.parse(this.window.localStorage.getItem(a));return c.expiresAt>Date.now()?c.value:!1}catch(e){return!1}};b.prototype.l=function(a,c){var b=this,d="onetag-grouping_"+a,f=this.g(d);f?c(f):this.f.get(this.a.geoGroupingUrl+
"regionalbloc/"+a,function(a){var e=[];a.countries&&(e=a.countries.map(function(a){return a.code}),b.j(d,e));return c(e)})};f.i=b},{}],41:[function(d,f){function b(a,c,b,d){this.H=a;this.window=a.window;this.A=a.adLocator;this.l=a.engagementBeacon;this.C=a.config;this.a=b;this.M=c;this.g=d;this.f={};this.s={};this.containerId=null;this.o={};this.b={}}b.prototype.B=function(a,c){var b=this;this.containerId=a.containerId;this.o=a.settings||{};this.s=c;this.S(a.contents,c);this.O(a.contents)&&(this.a.B(this.b),
this.ma(a.contents)&&this.g.get(function(a){a.ab(b.ka.bind(b))}));this.W()&&this.T()};b.prototype.ib=function(a,c){var b=this,d={},f={},h=this.c(a),l=this.c(a);h.contents=[];l.contents=[];Object.keys(c).forEach(function(e){var g=c[e],n=g.config;g=g.contentFunction;var r=e.split("@")[0],p=b.N(r,a);b.b[r]=n;n.executeImmediately?(d[e]=g,h.contents.push.apply(h.contents,p instanceof Array?p:U(T(p)))):(f[e]=g,l.contents.push.apply(l.contents,p instanceof Array?p:U(T(p))))});return{onStart:{containerDto:h,
contentFunctions:d},onPageLoad:{containerDto:l,contentFunctions:f}}};b.prototype.N=function(a,b){var c=this,d=this.v((b.user||{}).settings,b.settings);return b.contents.reduce(function(b,e){a===e.type&&(e.settings=c.v(d,e.settings),b.push(e));return b},[])};b.prototype.v=function(a,b){a=a||{};var c=this.c(a),d=b||{};Object.keys(d).forEach(function(a){c[a]=d[a]});return c};b.prototype.S=function(a,b){for(var c=0;c<a.length;c++){var d=a[c];this.K(a[c],this.L.bind(this,d,b[d.type+"@"+d.revision]))}};
b.prototype.L=function(a,b,e){e&&this.X(a,b)};b.prototype.K=function(a,b){this.M.qb(a.filters,function(a){return b(a)})};b.prototype.X=function(a,b){this.u(a)?this.U(b,a):this.A.B(b,a,this.H,this.b[a.type])};b.prototype.T=function(){var a=this;this.I||(this.V(function(b){a.l.start(a.containerId,b);a.m()}),this.I=!0)};b.prototype.m=function(){var a=this;return this.g.get(function(b){b=b.lb();0===b.length&&setTimeout(a.m.bind(a),1E3);for(var c=0;c<b.length;c++)a.l.ta("#"+b[c],b[c])})};b.prototype.U=
function(a,b){var c=this,d=b.settings,f=b.contentId;this.a.Eb(this.b);if(d.dfpMode)this.g.get(function(e){var g=e.Ga().map(function(a){return"#"+a});c.j(a,b,g);e.jb(d,function(a){c.a.ja([a],f)});e.bb(c.la.bind(c,a,b,e))});else{var h=this.J(d.selectors||d.selector);this.a.ja(h,f);this.j(a,b,h)}};b.prototype.la=function(a,b,e,d){var c=this,f=b.contentId;e.zb(d);e.na(b.settings,d,function(e){c.j(a,b,[e]);c.a.ja([e],f)})};b.prototype.J=function(a){return[].concat(a)};b.prototype.j=function(a,b,e){if(b.settings.useImpressionViewable)this.Y(e,
b);else for(var c=0;c<e.length;c++){var d=e[c],f=this.c(b);f.settings.selector=d;delete f.settings.selectors;this.a.da(f,a)}};b.prototype.Y=function(a,b){var c=this;a.forEach(function(a){c.f[a]||(c.f[a]=[]);c.f[a].push(b)})};b.prototype.ma=function(a){for(var b=0;b<a.length;b++)if(a[b].settings.useImpressionViewable)return!0;return!1};b.prototype.ka=function(a){for(var b=0;b<this.f[a].length;b++){var e=this.c(this.f[a][b]),d=this.s[e.type+"@"+e.revision];e.settings.selector=a;delete e.settings.selectors;
this.a.da(e,d)}};b.prototype.c=function(a){return JSON.parse(JSON.stringify(a))};b.prototype.O=function(a){for(var b=0;b<a.length;b++)if(this.u(a[b]))return!0;return!1};b.prototype.u=function(a){return-1!==a.type.indexOf("onetag-vet")};b.prototype.W=function(){var a=this.C.featureToggles.engagementBeacon;return this.o.disableEngagementTracking||!a?!1:!0};b.prototype.V=function(a){var b=this.window.navigator.fb||this.window.fb;"1"===b||"yes"===b?a(!0):a(!1)};f.i=b},{}],42:[function(d,f){function b(a){this.a=
a}b.prototype.create=function(a,b,e){return new this.a(a,b,e)};f.i=b},{}],43:[function(d,f){function b(a,b){this.window=a;this.a=!1;this.b=b}b.prototype.get=function(a){var b=this;this.f();this.c()?a(this.window.$sf.host):setTimeout(function(){b.get(a)},500)};b.prototype.f=function(){if(!this.window.$sf&&!this.a){this.a=!0;var a=this.window.document.createElement("script");a.setAttribute("src",this.b.safeFrameUrls.lib);this.window.document.body.appendChild(a)}};b.prototype.c=function(){var a=this.window.$sf;
return a&&a.host&&a.host.boot?!0:!1};f.i=b},{}],44:[function(d,f){function b(a){this.window=a}b.prototype.create=function(a){return new this.window.MutationObserver(a)};f.i=b},{}],45:[function(d,f){function b(a,b){this.window=a;this.b=b;this.a=null}b.prototype.g=function(){var a=this.window.pbjs;return a&&"function"===typeof a.requestBids?a:null};b.prototype.fa=function(a,b){var c=this.g();(this.a=this.b.hb())&&(c?this.j(a,b,c):this.a.reload(a,b))};b.prototype.j=function(a,b,e){var c=this,d=this.f(a,
e),f={adUnitCodes:[a],bidsBackHandler:function(){c.a.Sa(a);c.a.reload(a,b)}};d&&(f.adUnits=[d]);e.requestBids(f)};b.prototype.c=function(a){for(var b=a.bids,e=0;e<b.length;e++)"sovrn"===b[e].bidder&&(b[e].params.iv="vet");return a};b.prototype.f=function(a,b){b=b.adUnits;if(!b)return null;for(var c=0;c<b.length;c++)if(b[c].code===a)return this.c(b[c])};f.i=b},{}],46:[function(d,f){function b(a,b,e,d){this.u=a;this.j=a.viewableEngagedTime;this.A=a.engagementBeacon;this.f=a.adLocator;this.g=a.adSizeService;
this.window=a.window;this.N=b;this.J=a.config.lazyLoadWaitTime||20;this.M=e;this.v=d;this.c={};this.a={}}b.prototype.B=function(){this.j.start()};b.prototype.Eb=function(a){this.b=a};b.prototype.ja=function(a,b){for(var c=0;c<a.length;c++){var d=a[c]+"-"+b;this.c[d]||(this.c[d]=!0)}};b.prototype.da=function(a,b){this.L(a,b);this.s(a,b)};b.prototype.s=function(a,b){var c=this,d={childList:!0,subtree:!0},f=a.settings.selector,h=this.f.ca(f),l=f+"-"+a.contentId;h?(this.l(a,b,h),this.a[l]||this.M.create(function(d,
e){d.forEach(function(){c.l(a,b,h);c.a[l]&&e.disconnect()})}).observe(h,d)):setTimeout(this.s.bind(this,a,b),1E3)};b.prototype.L=function(a,b){var c=a.settings.selector,d=this.f.ca(c),f=c+"-"+a.contentId;d&&this.l(a,b,d);this.a[f]||this.Y(a,b,c)};b.prototype.Y=function(a,b,d){var c=this,e=d+"-"+a.contentId,f=0,l=setInterval(function(){var g=c.f.ca(d);f++;g&&(c.l(a,b,g),(c.a[e]||f>c.J)&&clearInterval(l))},1E3)};b.prototype.l=function(a,b,d){var c=this.g.oa(d);this.W(a,c)&&this.C(a,b,d)};b.prototype.W=
function(a,b){var c=a.settings;return this.a[c.selector+"-"+a.contentId]?!1:this.g.La(c,b)};b.prototype.C=function(a,b,d){this.a[(a.settings||{}).selector+"-"+a.contentId]={gb:b,definition:a,element:d};this.j.Ib(a,d,this.S.bind(this))};b.prototype.S=function(a){var b=a.F,d=b+"-"+a.D,f=this.a[d];if(!this.c[d])return this.V(f)?(this.m(d),!1):!0;f=f.definition.settings;var n=this.g.oa(a.element);if(!this.g.La(f,n))return this.m(d),!1;this.U(d);f.useNativeReload||this.j.Cb(a);this.fa(b,a.ra,d);return!0};
b.prototype.V=function(a){return this.o(a)?!0:!this.I()};b.prototype.o=function(a){return"onetag-vet-header-content"===a.definition.type};b.prototype.I=function(){for(var a=Object.keys(this.a),b=0;b<a.length;b++)if(this.o(this.a[a[b]]))return!0;return!1};b.prototype.m=function(a){delete this.a[a];this.j.Db(a)};b.prototype.U=function(a){a=this.a[a].element;var b=a.getBoundingClientRect(),d=b.width;a.style.minHeight=b.height+"px";a.style.minWidth=d+"px";a.style.boxSizing="border-box"};b.prototype.fa=
function(a,b,d){var c=this.a[d].definition,e=c.contentId;c.settings.useNativeReload?this.O(c,a,b):(this.K(this.a[d]),this.X(a,d));this.A.ta(a,e)};b.prototype.X=function(a,b){var c=this,d=Object.keys(this.a);1>=d.length||d.forEach(function(d){-1!==d.indexOf(a)&&d!==b&&c.m(d)})};b.prototype.O=function(a,b,d){a=a.settings;this.N.fa(b.substring(1),{enableVetKeyValue:a.enableVetKeyValue,dfpKeyValues:a.dfpKeyValues,reloadCount:d});this.T(a.selector)};b.prototype.T=function(a){var b=this;Object.keys(this.c).forEach(function(c){-1!==
c.indexOf(a)&&(delete b.c[c],b.H(a,c))})};b.prototype.H=function(a,b){var c=this;this.v.get(function(d){var e=c.a[b],f=e.definition.contentId;d.na(e.definition.settings,d.kb(a.substring(1)),function(a){c.ja([a],f)})})};b.prototype.K=function(a){this.f.B(a.gb,a.definition,this.u,this.b[a.definition.type])};f.i=b},{}],47:[function(d,f){function b(a,b){this.j=a.viewability;this.c=a.engagementMonitor;this.f=a.adSizeService;this.window=a.window;this.a={};this.b=null;this.g=!1;this.s=b||20}b.prototype.start=
function(){var a=this;this.g||(this.c.start(),this.b=this.m(),this.v(),this.c.ga("user_active",function(){a.b||(a.b=a.m())}),this.c.ga("user_inactive",function(){a.window.clearInterval(a.b);a.b=null}),this.g=!0)};b.prototype.Ib=function(a,b,d){var c=a.settings;a=a.contentId;var e=c.selector;this.a[e+"-"+a]={xa:0,sa:0,Bb:c.reloadTime||20,F:e,D:a,element:b,ra:0,Ab:c.reloadLimit||Infinity,size:{width:c.width,height:c.height},vb:d}};b.prototype.Db=function(a){delete this.a[a]};b.prototype.v=function(){this.window.setInterval(this.l.bind(this,
this.A),1E3)};b.prototype.m=function(){return this.window.setInterval(this.l.bind(this,this.C),1E3)};b.prototype.l=function(a){for(var b in this.a)this.a.hasOwnProperty(b)&&a.call(this,this.a[b])};b.prototype.A=function(a){a.sa++};b.prototype.C=function(a){var b=this.Ca(a);this.j.qa(b)&&a.xa++;this.u(b,a)&&this.fa(a)};b.prototype.Ca=function(a){if(!a.Z||!this.o(a)){var b=this.f.ha(a.element,"iframe");a.Z=b||this.f.ha(a.element,"img")}return a.Z?a.Z:a.element};b.prototype.o=function(a){for(var b=a.Z;b.parentNode;)if(b=
b.parentNode,b===a.element)return!0;return!1};b.prototype.fa=function(a){a.vb(a)&&(a.ra++,a.xa=0,a.sa=0,a.Z=null)};b.prototype.u=function(a,b){a=this.j.qa(a);var c=b.xa>=b.Bb,d=b.sa>=this.s;b=b.ra>=b.Ab;return a&&c&&!b&&d};b.prototype.Cb=function(a){for(var b=a.element.childNodes,d=b.length;0<d;d--)a.element.removeChild(b[d-1])};f.i=b},{}],48:[function(d,f){function b(a){this.window=a}b.prototype.mb=function(){try{var a=this.window.top;a.state="FRIENDLY"}catch(c){a=this.window,a.state="UNFRIENDLY",
a.$sf&&a.$sf.ext&&(a.state="SAFEFRAME")}return a};f.i=b},{}],49:[function(d,f){function b(d,f,D,m){var C=new g(b.window),x=d.containerId,u=d.settings.isVetLicensing,E=d.settings.disengagementThreshold,F=d.settings.minimumAdLoadtime,k=C.mb();k.__onetag||(k.__onetag={});k.__onetag.containerIds=k.__onetag.containerIds||{};if(k.__onetag.containerIds[x])return!1;k.__onetag.containerIds[x]=!0;var Y=new Z,aa=new l,ca=new ba,O=new da;C=new p(k);var P=new r(k,O);x=new W(k,P);var G=new n(k,m);G=new h(k,G,m);
var fa=new ea(k),ia=new ha(k,c(u));E=new ja(k,E);var ma=new ka(la),oa=new na(k);m={config:m,window:k,adLocator:fa,httpClient:Y,viewability:ia,engagementMonitor:E,adRenderingService:G,adSizeService:aa,postbidFactory:ma,bidderParamsParser:ca,adServerHandlerProvider:P,consentProvider:oa};m.geoLocationService=new pa(m);m.viewableEngagedTime=new qa(m,F);m.engagementBeacon=new ra(m,u);u=new X(m,O);D=new sa(m,D);F=new w(m,x,C,u);var y=new e(m,D,F,u),Q=!1,t=y.ib(d,f);y.B(t.onStart.containerDto,t.onStart.contentFunctions);
if(a(k.document))return y.B(t.onPageLoad.containerDto,t.onPageLoad.contentFunctions),!0;k.document.addEventListener("readystatechange",function(){!Q&&a(k.document)&&(y.B(t.onPageLoad.containerDto,t.onPageLoad.contentFunctions),Q=!0)});return!0}function a(a){a=a.readyState;return"interactive"===a||"complete"===a}function c(a){var b=.5;a&&(b=1);return b}var e=d(41),g=d(48),n=d(43),h=d(29),l=d(33),r=d(30),W=d(45),w=d(46),X=d(39),p=d(44),ra=d(4),ea=d(2),Z=d(22),ja=d(14),ha=d(27),sa=d(19),pa=d(40),la=
d(25),ka=d(42),qa=d(47),ba=d(34),da=d(36),na=d(35);b.window=window;f.i=b},{14:14,19:19,2:2,22:22,25:25,27:27,29:29,30:30,33:33,34:34,35:35,36:36,39:39,4:4,40:40,41:41,42:42,43:43,44:44,45:45,46:46,47:47,48:48}],50:[function(d){var f={"onetag-vet-postbid-content@*":d(1)};d(49)({containerId:"c692e01a-b65d-4aa9-aff9-bee34f082a39",contents:[{name:"VET - 300x250",containerId:"c692e01a-b65d-4aa9-aff9-bee34f082a39",contentId:"33855f38-4572-452e-9668-536722c0795d",type:"onetag-vet-postbid-content",revision:"*",
repo:"@onscroll",settings:{integrationType:"vet-reload",demandType:"services",headerBiddingType:"postbid",sizes:["300x250"],passbackHtml:'\x3c!--/* OpenX Asynchronous JavaScript tag */--\x3e\n\n\n<div id="540150133_INSERT_SLOT_ID_HERE" style="width:300px;height:250px;margin:0;padding:0">\n  <noscript><iframe id="7d0a1f48d0" name="7d0a1f48d0" src="//uk-ads.openx.net/w/1.0/afr?auid=540150133&cb=INSERT_RANDOM_NUMBER_HERE" frameborder="0" scrolling="no" width="300" height="250"><a href="//uk-ads.openx.net/w/1.0/rc?cs=7d0a1f48d0&cb=INSERT_RANDOM_NUMBER_HERE" ><img src="//uk-ads.openx.net/w/1.0/ai?auid=540150133&cs=7d0a1f48d0&cb=INSERT_RANDOM_NUMBER_HERE" border="0" alt=""></a></iframe></noscript>\n</div>\n<script type="text/javascript">\n  var OX_ads = OX_ads || [];\n  OX_ads.push({\n     slot_id: "540150133_INSERT_SLOT_ID_HERE",\n     auid: "540150133"\n  });\n\x3c/script>\n\n<script type="text/javascript" src="//uk-ads.openx.net/w/1.0/jstag">\x3c/script>\n',
bidders:{appnexus:[{label:"1019",placementId:"12872533"}],rubicon:[{label:"rubi",accountId:"15380",siteId:"183678",zoneId:"990608",sizes:["15"]}],openx:[{label:"postbid",delDomain:"onscroll-d.openx.net",unit:"540149903"}]},dfpMode:!0,reloadTime:"22",customDeviceTypes:[{name:"Phone",min:"1",max:"768"},{name:"Tablet",min:"769",max:"992"},{name:"Desktop",min:"993",max:"9999"}],gdprMode:!0,useImpressionViewable:!0,lineItemTypes:[{type:"SPONSORSHIP",priority:"all"},{type:"STANDARD",priority:"all"},{type:"HOUSE",
priority:"all"},{type:"NETWORK",priority:"all"},{type:"BULK",priority:"all"},{type:"PRICE_PRIORITY",priority:"all"}],isSafeFrame:!0,currencyModule:!0},filters:[],enabled:!0},{name:"VET - 728x90",containerId:"c692e01a-b65d-4aa9-aff9-bee34f082a39",contentId:"0b959307-6c09-4a95-83ed-6eedf9cda66e",type:"onetag-vet-postbid-content",revision:"*",repo:"@onscroll",settings:{integrationType:"vet-reload",demandType:"services",headerBiddingType:"postbid",sizes:["728x90"],passbackHtml:'\x3c!--/* OpenX Asynchronous JavaScript tag */--\x3e\n\n\n<div id="540150136_INSERT_SLOT_ID_HERE" style="width:728px;height:90px;margin:0;padding:0">\n  <noscript><iframe id="db98545ea0" name="db98545ea0" src="//uk-ads.openx.net/w/1.0/afr?auid=540150136&cb=INSERT_RANDOM_NUMBER_HERE" frameborder="0" scrolling="no" width="728" height="90"><a href="//uk-ads.openx.net/w/1.0/rc?cs=db98545ea0&cb=INSERT_RANDOM_NUMBER_HERE" ><img src="//uk-ads.openx.net/w/1.0/ai?auid=540150136&cs=db98545ea0&cb=INSERT_RANDOM_NUMBER_HERE" border="0" alt=""></a></iframe></noscript>\n</div>\n<script type="text/javascript">\n  var OX_ads = OX_ads || [];\n  OX_ads.push({\n     slot_id: "540150136_INSERT_SLOT_ID_HERE",\n     auid: "540150136"\n  });\n\x3c/script>\n\n<script type="text/javascript" src="//uk-ads.openx.net/w/1.0/jstag">\x3c/script>\n',
bidders:{appnexus:[{label:"1019",placementId:"12872534"}],openx:[{label:"postbid ",unit:"540149904",delDomain:"onscroll-d.openx.net"}],rubicon:[{label:"rubi",accountId:"15380",siteId:"183678",zoneId:"990610",sizes:["2"]}]},dfpMode:!0,reloadTime:"22",customDeviceTypes:[{name:"Phone",min:"1",max:"768"},{name:"Tablet",min:"769",max:"992"},{name:"Desktop",min:"993",max:"9999"}],gdprMode:!0,useImpressionViewable:!0,lineItemTypes:[{type:"SPONSORSHIP",priority:"all"},{type:"STANDARD",priority:"all"},{type:"HOUSE",
priority:"all"},{type:"NETWORK",priority:"all"},{type:"BULK",priority:"all"},{type:"PRICE_PRIORITY",priority:"all"}],isSafeFrame:!0,currencyModule:!0},filters:[],enabled:!0}],settings:{revShareAdjustments:{appnexus:1,rubicon:1,openx:1}},user:{settings:{}}},f,{},{prebidUrl:"https://ap.lijit.com/www/headerauction/prebid.min.js",adRenderUrl:"//ap.lijit.com/www/delivery/fpi.js?z=",cookieEndpoint:"https://ap.lijit.com/readerinfo?loc=",beaconEndpoint:"https://onetag-metrics-collector.onscroll.com/metrics",
dfpGatewayUrl:"https://dfp-gateway.us.onscroll.com/1",featureToggles:{engagementBeacon:!0},safeFrameUrls:{html:"//get.s-onetag.com/safeframe-urls/safe-frame-internal.html",lib:"//get.s-onetag.com/safeframe-urls/safe-frame.js"},safeFrameTarget:"#sf_pos_rel_el_",geoLocationUrl:"//onetag-geo.s-onetag.com/",geoGroupingUrl:"//onetag-geo-grouping.s-onetag.com/",geoLocationCacheTtl:86400,lineItemInfoTtl:86400,noTrackingGeoGroup:"EU",cmpUrl:"//sovrn.mgr.consensu.org",sovrnVendorId:13})},{1:1,49:49}]},{},
[50]);
/* 
date-of-deployment: UTC2018-09-13T15:29:33Z 
contents:
onetag-vet-postbid-content: 3.0.180604170611
filters:
*/